import fs from 'node:fs';
import crypto from 'node:crypto';
import { buildR19Core, parseAnnotated, sha } from '../0.10.5-r1.9/r19_quotient_core.mjs';

const ROOT=process.env.R113_ROOT||'/tmp/r113'; fs.mkdirSync(ROOT,{recursive:true});
const fixture=JSON.parse(fs.readFileSync(`${ROOT}/ROTATION_GAUGE_TRANSPORT_FIXTURE.json`,'utf8'));
if(fixture.status!=='PASS_ROTATION_GAUGE_ALGEBRA') throw new Error('G3_ROTATION_FIXTURE_NOT_PASS');
const T=fixture.transport_table;
const core=await buildR19Core();
const {defaultPattern,EDGE,CORNER,ORIENT,faces,faceSupport,opposite}=core;
const attemptKey=r=>`${r.result_id}:${r.attempt_number}`;
const foldOf=k=>parseInt(crypto.createHash('sha256').update(`R113FOLD:${k}`).digest('hex').slice(0,8),16)%5;
const intersect=(a,b)=>{const s=new Set(b);return a.filter(x=>s.has(x));};
const moveBin=n=>n<=4?'1-4':n<=8?'5-8':n<=12?'9-12':'13+';

function blockMask(bottom,side){const top=opposite[bottom];return {bottom,side,top,edges:faceSupport[side].edges.filter(i=>!faceSupport[top].edges.includes(i)),corners:intersect(faceSupport[bottom].corners,faceSupport[side].corners)};}
const frames=[];
for(const bottom of faces)for(const side of faces){if(side===bottom||side===opposite[bottom])continue;frames.push({key:`${bottom}|${side}`,bottom,top:opposite[bottom],first_side:side,second_side:opposite[side],first:blockMask(bottom,side),second:blockMask(bottom,opposite[side])});}
const allCorners=defaultPattern.patternData[CORNER].pieces.map((_,i)=>i);
const allEdges=defaultPattern.patternData[EDGE].pieces.map((_,i)=>i);
function coordSolved(p,orbit,i){const a=p.patternData[orbit],b=defaultPattern.patternData[orbit];return a.pieces[i]===b.pieces[i]&&a.orientation[i]===b.orientation[i];}
function blockSolved(p,m){return m.edges.every(i=>coordSolved(p,EDGE,i))&&m.corners.every(i=>coordSolved(p,CORNER,i));}
function masksForBlock(b){return [{orbit:EDGE,positions:b.edges},{orbit:CORNER,positions:b.corners}];}
function twoBlockMasks(f){return [{orbit:EDGE,positions:[...f.first.edges,...f.second.edges]},{orbit:CORNER,positions:[...f.first.corners,...f.second.corners]}];}
function lseEdges(f){const s=new Set([...f.first.edges,...f.second.edges]);return allEdges.filter(i=>!s.has(i));}
function dist(p,target,masks){let bad=0,total=0;for(const m of masks)for(const i of m.positions){total+=2;const a=p.patternData[m.orbit],b=target.patternData[m.orbit];if(a.pieces[i]!==b.pieces[i])bad++;if(a.orientation[i]!==b.orientation[i])bad++;}return total?bad/total:null;}
function minDist(p,targets,masks){return Math.min(...targets.map(t=>dist(p,t,masks)));}
function objectiveBacktrack(ds){let frontier=Infinity,amp=0;for(const d of ds){frontier=Math.min(frontier,d);amp=Math.max(amp,d-frontier);}return amp;}
function anchorBreak(states,masks){if(!states.length)return null;const vals=states.map(p=>dist(p,defaultPattern,masks)),a0=vals[0];return Math.max(...vals.map(x=>Math.max(0,x-a0)));}
function aufVariants(p,face){const out=[p];let q=p;for(let i=1;i<4;i++){q=q.applyMove(face);out.push(q);}return out;}
function cornersSolvedAUF(p,face){let q=p;for(let i=0;i<4;i++){if(allCorners.every(j=>coordSolved(q,CORNER,j)))return true;q=q.applyMove(face);}return false;}
function ordinaryFb(c){const s=String(c||'');return /\bfb\b/i.test(s)&&!/\bpseudo\s+fb\b/i.test(s)&&!/\bfbdr\b/i.test(s);}
function span(lines,phase,after=-1){let first=-1;for(let i=0;i<lines.length;i++)if(lines[i].phase===phase&&lines[i].end>lines[i].start&&lines[i].start>=after){first=i;break;}if(first<0)return null;let last=first;for(let i=first+1;i<lines.length;i++){if(lines[i].phase!==phase||lines[i].end<=lines[i].start)break;last=i;}return {first_line_index:first,last_line_index:last,start:lines[first].start,end:lines[last].end,lines:lines.slice(first,last+1)};}
function firstLineAfter(lines,phase,after){return lines.find(x=>x.phase===phase&&x.end>x.start&&x.start>=after)||null;}
function normRot(m){const s=String(m);const a=s[0];if(!'xyz'.includes(a))return null;if(s.includes('2'))return `${a}2`;return s.includes("'")?`${a}'`:a;}
const inverse={};for(const rot of fixture.rotation_tokens){inverse[rot]={};for(let g=0;g<24;g++){const h=T[g][rot];if(h===null||h===undefined)throw new Error('TRANSPORT_TABLE_NULL');if(inverse[rot][h]!==undefined)throw new Error('TRANSPORT_NOT_PERMUTATION');inverse[rot][h]=g;}}
function buildGaugePath(tokens,fbEnd,g0,nStates){const g=Array(nStates).fill(null);g[fbEnd]=g0;let x=g0;for(let j=fbEnd-1;j>=0;j--){const r=normRot(tokens[j].move);if(r)x=inverse[r][x];g[j]=x;}x=g0;for(let j=fbEnd;j<tokens.length;j++){const r=normRot(tokens[j].move);if(r)x=T[x][r];g[j+1]=x;}return g;}
function transformed(states,gauges,i){const g=gauges[i];if(!Number.isInteger(g))throw new Error(`GAUGE_MISSING_AT_STATE_${i}`);return states[i].applyTransformation(ORIENT[g]);}

function loadRecords(){const c=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-census/SEALED_ROUTE_CENSUS.json','utf8'));const a=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-acquisition/ROUX_EXPANSION_ROUTE_MANIFEST.json','utf8'));const z=[];for(const r of c.all_clean_attempts)z.push({...r,source:'SEALED_R111'});for(const r of a.records)if(r.route_source_status==='RAW_ALG_CUBING_LINK')z.push({...r,source:'R112_EXPANSION'});const m=new Map();for(const r of z)m.set(attemptKey(r),r);return [...m.values()].sort((a,b)=>attemptKey(a).localeCompare(attemptKey(b)));}

const records=loadRecords(),rows=[],features=[];
const counts={raw_unique_attempts:records.length,parse_ok:0,state_certified:0,ordinary_fb:0,forked_pseudo_fb:0,forked_fbdr:0,geometry_eligible:0,prefix_any:0,prefix_unique:0,prefix_multi:0,g3_admitted:0,rotation_present_prefix_unique:0,rotation_present_completed:0,no_rotation_prefix_unique:0,no_rotation_completed:0,cmll_opportunities:0,cmll_consistent:0,lse_opportunities:0,lse_consistent:0,first_block_break_failures:0,errors:0};
const rejection={},frameCounts={},sourceCounts={};const inc=k=>rejection[k]=(rejection[k]||0)+1;
for(const r of records){const rec={attempt_key:attemptKey(r),result_id:r.result_id,attempt_number:r.attempt_number,reco_id:r.reco_id??null,source:r.source,status:'START'};sourceCounts[r.source]??={eligible:0,prefix_unique:0,admitted:0};try{
  const parsed=parseAnnotated(r.raw_alg,'Roux');counts.parse_ok++;const moves=parsed.tokens.map(x=>x.move);let s=defaultPattern.applyAlg(r.raw_setup),states=[s];for(const m of moves){s=s.applyMove(m);states.push(s);}rec.final_solved=s.experimentalIsSolved({ignorePuzzleOrientation:true,ignoreCenterOrientation:true});if(!rec.final_solved){rec.status='FINAL_NOT_SOLVED';inc(rec.status);rows.push(rec);continue;}counts.state_certified++;
  const fbLines=parsed.lines.filter(x=>x.phase==='ROUX_FB'&&x.end>x.start);if(fbLines.length!==1){rec.status='FB_LINE_COUNT_NOT_ONE';inc(rec.status);rows.push(rec);continue;}const fb=fbLines[0];rec.fb_comment=fb.comment;if(/\bpseudo\s+fb\b/i.test(fb.comment)){counts.forked_pseudo_fb++;rec.status='FORK_PSEUDO_FB';rows.push(rec);continue;}if(/\bfbdr\b/i.test(fb.comment)){counts.forked_fbdr++;rec.status='FORK_FBDR';rows.push(rec);continue;}if(!ordinaryFb(fb.comment)){rec.status='FB_NONORDINARY';inc(rec.status);rows.push(rec);continue;}counts.ordinary_fb++;
  const sb=span(parsed.lines,'ROUX_SB',fb.end);if(!sb){rec.status='NO_SB_SPAN';inc(rec.status);rows.push(rec);continue;}counts.geometry_eligible++;sourceCounts[r.source].eligible++;
  const prefix=[];for(let gi=0;gi<24;gi++){const q=states[fb.end].applyTransformation(ORIENT[gi]);for(const f of frames)if(blockSolved(q,f.first)&&!blockSolved(q,f.second))prefix.push({gauge:gi,frame:f});}
  rec.prefix_candidate_n=prefix.length;if(prefix.length)counts.prefix_any++;if(prefix.length!==1){if(prefix.length>1)counts.prefix_multi++;rec.status=prefix.length?'PREFIX_MULTI':'PREFIX_NONE';inc(rec.status);rows.push(rec);continue;}counts.prefix_unique++;sourceCounts[r.source].prefix_unique++;
  const init=prefix[0],frame=init.frame;frameCounts[frame.key]=(frameCounts[frame.key]||0)+1;rec.initial_gauge=init.gauge;rec.frame_key=frame.key;
  const gauges=buildGaugePath(parsed.tokens,fb.end,init.gauge,states.length);let completion=null,firstBlockBreak=false;
  for(let i=sb.start;i<=sb.end;i++){const q=transformed(states,gauges,i);if(!blockSolved(q,frame.first))firstBlockBreak=true;if(blockSolved(q,frame.first)&&blockSolved(q,frame.second)){completion=i;break;}}
  const searchEnd=completion??sb.end;const rots=[];for(let j=fb.end;j<searchEnd;j++){const rr=normRot(parsed.tokens[j].move);if(rr)rots.push({token_index:j,move:parsed.tokens[j].move,normalized:rr});}
  const rotationPresent=rots.length>0;rec.rotation_present=rotationPresent;rec.rotation_tokens=rots;rec.first_block_break_before_completion=firstBlockBreak;if(rotationPresent)counts.rotation_present_prefix_unique++;else counts.no_rotation_prefix_unique++;
  if(completion===null){if(firstBlockBreak)counts.first_block_break_failures++;rec.status='NO_TRANSPORTED_SB_COMPLETION';inc(rec.status);rows.push(rec);continue;}
  if(rotationPresent)counts.rotation_present_completed++;else counts.no_rotation_completed++;counts.g3_admitted++;sourceCounts[r.source].admitted++;rec.sb_completion_index=completion;
  const qAt=i=>transformed(states,gauges,i);function addFeature(phase,channel,start,end,amp){features.push({generation:'ROUX-MEASUREMENT-G3',result_id:r.result_id,attempt_number:r.attempt_number,reco_id:r.reco_id??null,source:r.source,method:'Roux',phase,channel,move_count:end-start,move_bin:moveBin(end-start),observed_amplitude:amp,frame_key:frame.key,initial_gauge:init.gauge,rotation_present:rotationPresent,fold:foldOf(attemptKey(r))});}
  const fbStates=[];for(let i=fb.start;i<=fb.end;i++)fbStates.push(qAt(i));const fbDs=fbStates.map(p=>dist(p,defaultPattern,masksForBlock(frame.first)));addFeature('FB','objective',fb.start,fb.end,objectiveBacktrack(fbDs));
  const sbStates=[];for(let i=sb.start;i<=completion;i++)sbStates.push(qAt(i));const sbDs=sbStates.map(p=>dist(p,defaultPattern,masksForBlock(frame.second)));addFeature('SB','objective',sb.start,completion,objectiveBacktrack(sbDs));addFeature('SB','anchor',sb.start,completion,anchorBreak(sbStates,masksForBlock(frame.first)));
  const cmll=firstLineAfter(parsed.lines,'ROUX_CMLL',completion);if(cmll){counts.cmll_opportunities++;const ep=qAt(cmll.end),consistent=blockSolved(ep,frame.first)&&blockSolved(ep,frame.second)&&cornersSolvedAUF(ep,frame.top);rec.cmll_consistent=consistent;if(consistent)counts.cmll_consistent++;const targets=aufVariants(ep,frame.top),ms=[{orbit:CORNER,positions:allCorners}],ps=[];for(let i=cmll.start;i<=cmll.end;i++)ps.push(qAt(i));addFeature('CMLL','objective',cmll.start,cmll.end,objectiveBacktrack(ps.map(p=>minDist(p,targets,ms))));addFeature('CMLL','anchor',cmll.start,cmll.end,anchorBreak(ps,twoBlockMasks(frame)));}
  const lse=span(parsed.lines,'ROUX_LSE',completion);if(lse){counts.lse_opportunities++;const ep=qAt(lse.end),consistent=blockSolved(ep,frame.first)&&blockSolved(ep,frame.second);rec.lse_consistent=consistent;if(consistent)counts.lse_consistent++;const ms=[{orbit:EDGE,positions:lseEdges(frame)}],ps=[];for(let i=lse.start;i<=lse.end;i++)ps.push(qAt(i));addFeature('LSE','objective',lse.start,lse.end,objectiveBacktrack(ps.map(p=>dist(p,ep,ms))));addFeature('LSE','anchor',lse.start,lse.end,anchorBreak(ps,twoBlockMasks(frame)));}
  rec.status='G3_ADMITTED';rows.push(rec);
}catch(e){counts.errors++;rec.status='ERROR';rec.error=String(e?.stack||e?.message||e).slice(0,700);inc(rec.status);rows.push(rec);}}
const rate=(n,d)=>d?n/d:0;const rates={prefix_unique_rate:rate(counts.prefix_unique,counts.geometry_eligible),sb_completion_rate:rate(counts.g3_admitted,counts.prefix_unique),rotation_present_sb_completion_rate:rate(counts.rotation_present_completed,counts.rotation_present_prefix_unique),no_rotation_sb_completion_rate:rate(counts.no_rotation_completed,counts.no_rotation_prefix_unique),cmll_consistency_rate:rate(counts.cmll_consistent,counts.cmll_opportunities),lse_consistency_rate:rate(counts.lse_consistent,counts.lse_opportunities),geometry_failure_rate:1-rate(counts.g3_admitted,counts.geometry_eligible)};
const objectiveN=features.filter(x=>x.channel==='objective').length;const checks={rotation_fixture_pass:fixture.status==='PASS_ROTATION_GAUGE_ALGEBRA',state_certified_ge_100:counts.state_certified>=100,prefix_unique_rate_ge_0_95:rates.prefix_unique_rate>=.95,sb_completion_rate_ge_0_90:rates.sb_completion_rate>=.90,no_rotation_sb_completion_rate_ge_0_90:rates.no_rotation_sb_completion_rate>=.90,rotation_present_sb_completion_rate_ge_0_75:rates.rotation_present_sb_completion_rate>=.75,cmll_consistency_rate_ge_0_80:rates.cmll_consistency_rate>=.80,lse_consistency_rate_ge_0_90:rates.lse_consistency_rate>=.90,geometry_failure_rate_le_0_10:rates.geometry_failure_rate<=.10,g3_admitted_ge_100:counts.g3_admitted>=100,total_features_ge_350:features.length>=350,objective_features_ge_275:objectiveN>=275,all_features_g3:features.every(x=>x.generation==='ROUX-MEASUREMENT-G3')};
const pass=Object.values(checks).every(Boolean);const audit={schema_version:'CR0105R113-ROUX-G3-ROTATION-COVARIANT-GEOMETRY-1',generation:'ROUX-MEASUREMENT-G3',status:pass?'PASS_ROUX_G3_DEVELOPMENT_GEOMETRY':'HOLD_ROUX_G3_DEVELOPMENT_GEOMETRY',fixture_semantic_sha256:fixture.semantic_sha256,counts,rates,checks,rejection_reasons:rejection,feature_counts:{total:features.length,objective:objectiveN,anchor:features.length-objectiveN,eligible_attempts:new Set(features.map(attemptKey)).size,phase:Object.fromEntries(['FB','SB','CMLL','LSE'].map(p=>[p,features.filter(x=>x.phase===p).length]))},frame_counts:frameCounts,source_counts:sourceCounts,data_role:'DEVELOPMENT_AND_CALIBRATION_ONLY',r112_outcomes_used_as_confirmatory:false,post_result_gate_change:false,fresh_confirmatory_scoring:false,human_observations:0};audit.semantic_sha256=sha(audit);
fs.writeFileSync(`${ROOT}/ROUX_G3_GEOMETRY_AUDIT.json`,JSON.stringify(audit,null,2)+'\n');fs.writeFileSync(`${ROOT}/ROUX_G3_ROUTE_ROWS.json`,JSON.stringify({schema_version:'CR0105R113-ROUX-G3-ROUTE-ROWS-1',generation:'ROUX-MEASUREMENT-G3',rows,human_observations:0},null,2)+'\n');fs.writeFileSync(`${ROOT}/ROUX_G3_FEATURE_LEDGER.json`,JSON.stringify({schema_version:'CR0105R113-ROUX-G3-FEATURE-LEDGER-1',generation:'ROUX-MEASUREMENT-G3',rows:features,human_observations:0},null,2)+'\n');console.log(JSON.stringify({status:audit.status,counts,rates,feature_counts:audit.feature_counts,checks,semantic_sha256:audit.semantic_sha256},null,2));
