import fs from 'node:fs';
import { buildR19Core, parseAnnotated, sha } from '../0.10.5-r1.9/r19_quotient_core.mjs';
const ROOT=process.env.R113_ROOT||'/tmp/r113';fs.mkdirSync(ROOT,{recursive:true});
const F=JSON.parse(fs.readFileSync('research/0.10.5-r1.13/evidence-development/ROTATION_GAUGE_TRANSPORT_FIXTURE.json','utf8')),T=F.transport_table;
const D=JSON.parse(fs.readFileSync('research/0.10.5-r1.13/evidence-rotation-destroy/ROTATION_MECHANISM_DESTROY_AUDIT.json','utf8'));
const core=await buildR19Core();const {defaultPattern,EDGE,CORNER,ORIENT,faces,faceSupport,opposite}=core;
const intersect=(a,b)=>{const s=new Set(b);return a.filter(x=>s.has(x));};function blockMask(bottom,side){const top=opposite[bottom];return {edges:faceSupport[side].edges.filter(i=>!faceSupport[top].edges.includes(i)),corners:intersect(faceSupport[bottom].corners,faceSupport[side].corners)};}const frames=[];for(const bottom of faces)for(const side of faces){if(side===bottom||side===opposite[bottom])continue;frames.push({key:`${bottom}|${side}`,first:blockMask(bottom,side),second:blockMask(bottom,opposite[side])});}
function cs(p,o,i){const a=p.patternData[o],b=defaultPattern.patternData[o];return a.pieces[i]===b.pieces[i]&&a.orientation[i]===b.orientation[i];}function bs(p,m){return m.edges.every(i=>cs(p,EDGE,i))&&m.corners.every(i=>cs(p,CORNER,i));}
function ordinary(c){return /\bfb\b/i.test(c||'')&&!/\bpseudo\s+fb\b/i.test(c||'')&&!/\bfbdr\b/i.test(c||'');}function span(lines,phase,after=-1){let first=-1;for(let i=0;i<lines.length;i++)if(lines[i].phase===phase&&lines[i].end>lines[i].start&&lines[i].start>=after){first=i;break;}if(first<0)return null;let last=first;for(let i=first+1;i<lines.length;i++){if(lines[i].phase!==phase||lines[i].end<=lines[i].start)break;last=i;}return {start:lines[first].start,end:lines[last].end};}function nr(m){const s=String(m),a=s[0];if(!'xyz'.includes(a))return null;if(s.includes('2'))return `${a}2`;return s.includes("'")?`${a}'`:a;}
function load(){const c=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-census/SEALED_ROUTE_CENSUS.json','utf8')),a=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-acquisition/ROUX_EXPANSION_ROUTE_MANIFEST.json','utf8'));const z=[];for(const r of c.all_clean_attempts)z.push({...r,source:'SEALED_R111'});for(const r of a.records)if(r.route_source_status==='RAW_ALG_CUBING_LINK')z.push({...r,source:'R112_EXPANSION'});const m=new Map();for(const r of z)m.set(`${r.result_id}:${r.attempt_number}`,r);return [...m.values()];}
const rows=[];let rotationRoutes=0,rotationEvents=0,eventInvariant=0,forwardFailure=0,forwardFailureBreakAtRotation=0,forwardFailureBreakLater=0;
for(const r of load())try{const p=parseAnnotated(r.raw_alg,'Roux'),fbL=p.lines.filter(x=>x.phase==='ROUX_FB'&&x.end>x.start);if(fbL.length!==1||!ordinary(fbL[0].comment))continue;const fb=fbL[0],sb=span(p.lines,'ROUX_SB',fb.end);if(!sb)continue;const moves=p.tokens.map(x=>x.move);let s=defaultPattern.applyAlg(r.raw_setup),states=[s];for(const m of moves){s=s.applyMove(m);states.push(s);}if(!s.experimentalIsSolved({ignorePuzzleOrientation:true,ignoreCenterOrientation:true}))continue;const pref=[];for(let g=0;g<24;g++){const q=states[fb.end].applyTransformation(ORIENT[g]);for(const f of frames)if(bs(q,f.first)&&!bs(q,f.second))pref.push({g,f});}if(pref.length!==1)continue;const z=pref[0];let g=z.g;const gauges=Array(states.length).fill(null);gauges[fb.end]=g;for(let j=fb.end;j<moves.length;j++){const rot=nr(moves[j]);if(rot)g=T[g][rot];gauges[j+1]=g;}const ev=[];for(let j=fb.end;j<sb.end;j++){const rot=nr(moves[j]);if(!rot)continue;rotationEvents++;const beforeG=gauges[j],afterG=gauges[j+1],qb=states[j].applyTransformation(ORIENT[beforeG]),qa=states[j+1].applyTransformation(ORIENT[afterG]);const invariant=bs(qb,z.f.first)===bs(qa,z.f.first)&&bs(qb,z.f.second)===bs(qa,z.f.second);if(invariant)eventInvariant++;ev.push({token_index:j,move:moves[j],normalized:rot,phase:p.tokens[j].phase,comment:p.tokens[j].comment,before_gauge:beforeG,after_gauge:afterG,first_before:bs(qb,z.f.first),first_after:bs(qa,z.f.first),second_before:bs(qb,z.f.second),second_after:bs(qa,z.f.second),block_status_invariant:invariant});}
 if(!ev.length)continue;rotationRoutes++;let completion=null,firstBreak=null;for(let i=sb.start;i<=sb.end;i++){const q=states[i].applyTransformation(ORIENT[gauges[i]]);if(firstBreak===null&&!bs(q,z.f.first))firstBreak=i;if(bs(q,z.f.first)&&bs(q,z.f.second)){completion=i;break;}}if(completion===null){forwardFailure++;if(firstBreak!==null){const atRot=ev.some(e=>e.token_index+1===firstBreak);if(atRot)forwardFailureBreakAtRotation++;else forwardFailureBreakLater++;}}
 rows.push({attempt_key:`${r.result_id}:${r.attempt_number}`,reco_id:r.reco_id??null,source:r.source,frame_key:z.f.key,initial_gauge:z.g,sb_span:sb,rotation_events:ev,forward_completion_index:completion,first_forward_first_block_break_state:firstBreak,first_break_token:firstBreak!==null&&firstBreak>0?{token_index:firstBreak-1,move:moves[firstBreak-1],phase:p.tokens[firstBreak-1].phase,comment:p.tokens[firstBreak-1].comment}:null,raw_alg:r.raw_alg});}catch(e){rows.push({attempt_key:`${r.result_id}:${r.attempt_number}`,error:String(e?.message||e).slice(0,300)});}
const out={schema_version:'CR0105R113-ROTATION-ROUTE-LOCALIZATION-1',generation:'ROUX-MEASUREMENT-G3',status:'POSTHOC_LOCALIZATION_ONLY_NO_G3_GATE_CHANGE',destroy_semantic_sha256:D.semantic_sha256,counts:{rotation_routes:rotationRoutes,rotation_events:rotationEvents,rotation_events_block_status_invariant:eventInvariant,forward_failures:forwardFailure,forward_failure_first_break_at_rotation:forwardFailureBreakAtRotation,forward_failure_first_break_later:forwardFailureBreakLater},interpretation_guard:'Pure rotation invariance checks validate algebra locally; later first-block breaks diagnose route semantics but cannot be used to alter R1.13 admission or gates.',post_result_gate_change:false,human_observations:0};out.semantic_sha256=sha(out);fs.writeFileSync(`${ROOT}/ROTATION_ROUTE_LOCALIZATION_AUDIT.json`,JSON.stringify(out,null,2)+'\n');fs.writeFileSync(`${ROOT}/ROTATION_ROUTE_LOCALIZATION_ROWS.json`,JSON.stringify({schema_version:'CR0105R113-ROTATION-ROUTE-LOCALIZATION-ROWS-1',rows,human_observations:0},null,2)+'\n');console.log(JSON.stringify(out,null,2));
