import fs from 'node:fs';
import { sha, upperQuantile, mean } from '../0.10.5-r1.9/r19_quotient_core.mjs';

const ROOT=process.env.R113_ROOT||'/tmp/r113';fs.mkdirSync(ROOT,{recursive:true});
const G=JSON.parse(fs.readFileSync(`${ROOT}/ROUX_G3_GEOMETRY_AUDIT.json`,'utf8'));
const F=JSON.parse(fs.readFileSync(`${ROOT}/ROUX_G3_FEATURE_LEDGER.json`,'utf8')).rows;
const key=r=>`${r.result_id}:${r.attempt_number}`;
function tail(ref,x){const ge=ref.filter(r=>r.observed_amplitude>=x.observed_amplitude-1e-12).length;const p=(1+ge)/(ref.length+1);return {p,score:-Math.log10(p),n:ref.length};}
function localRef(train,z){const levels=[['PHASE_CHANNEL_BIN',train.filter(r=>r.phase===z.phase&&r.channel===z.channel&&r.move_bin===z.move_bin),25],['PHASE_CHANNEL',train.filter(r=>r.phase===z.phase&&r.channel===z.channel),40],['CHANNEL',train.filter(r=>r.channel===z.channel),100]];for(const [level,rows,min] of levels)if(rows.length>=min)return {level,rows,n:rows.length,required:min};return null;}
function scoreFeatures(target,train){let fallback=0;const out=[];for(const z of target){const r=localRef(train,z);if(!r){fallback++;continue;}const t=tail(r.rows,z);out.push({...z,local_level:r.level,local_n:r.n,local_p:t.p,local_score:t.score});}return {rows:out,fallback};}
function attempts(rows){const by=new Map();for(const z of rows){const k=key(z);if(!by.has(k))by.set(k,[]);by.get(k).push(z);}return [...by.entries()].map(([k,z])=>({key:k,result_id:z[0].result_id,attempt_number:z[0].attempt_number,reco_id:z[0].reco_id,source:z[0].source,fold:z[0].fold,rotation_present:z.some(x=>x.rotation_present),scored_feature_n:z.length,attempt_statistic:Math.max(...z.map(x=>x.local_score))}));}
function familyRef(rows,a,excludeSelf=true,minN=60){let c=rows.filter(r=>Number.isFinite(r.attempt_statistic));if(excludeSelf)c=c.filter(r=>r.key!==a.key);return c.length>=minN?{level:'ROUX_GLOBAL',rows:c,n:c.length,required:minN}:null;}
function familyP(ref,a){const ge=ref.rows.filter(r=>r.attempt_statistic>=a.attempt_statistic-1e-12).length;return (1+ge)/(ref.n+1);}
let looFallback=0;const looFeatures=[];for(const z of F){const s=scoreFeatures([z],F.filter(r=>key(r)!==key(z)));looFallback+=s.fallback;looFeatures.push(...s.rows);}const loo=attempts(looFeatures);let looOk=0,looW=0,looP=0;const looRows=loo.map(a=>{const r=familyRef(loo,a,true,60);if(!r)return {...a,familywise_ok:false};const p=familyP(r,a);looOk++;if(p<=.05)looW++;if(p<=.01)looP++;return {...a,familywise_ok:true,familywise_level:r.level,familywise_n:r.n,familywise_p:p};});
let crossFallback=0;const crossFeatures=[];for(let f=0;f<5;f++){const s=scoreFeatures(F.filter(z=>z.fold===f),F.filter(z=>z.fold!==f));crossFallback+=s.fallback;crossFeatures.push(...s.rows);}const cross=attempts(crossFeatures);
const nestedRows=[],outer=[];let nestedFallback=0;for(let f=0;f<5;f++){const ts=scoreFeatures(F.filter(z=>z.fold===f),F.filter(z=>z.fold!==f));nestedFallback+=ts.fallback;const ta=attempts(ts.rows),refs=[];for(let g=0;g<5;g++)if(g!==f){const ins=scoreFeatures(F.filter(z=>z.fold===g),F.filter(z=>z.fold!==f&&z.fold!==g));nestedFallback+=ins.fallback;for(const a of attempts(ins.rows))refs.push({...a,reference_for_outer_fold:f,inner_fold:g});}let ok=0,w=0,p1=0;for(const a of ta){const r=familyRef(refs,a,false,60);if(!r){nestedRows.push({...a,outer_fold:f,familywise_ok:false});continue;}const p=familyP(r,a);ok++;if(p<=.05)w++;if(p<=.01)p1++;nestedRows.push({...a,outer_fold:f,familywise_ok:true,familywise_n:r.n,familywise_p:p});}outer.push({fold:f,test_attempts:ta.length,familywise_ok_n:ok,watch_rate:w/Math.max(1,ok),primary_rate:p1/Math.max(1,ok),reference_attempts:refs.length,outer_test_excluded_from_references:true});}
const nestedOk=nestedRows.filter(r=>r.familywise_ok),nestedW=nestedOk.filter(r=>r.familywise_p<=.05).length/Math.max(1,nestedOk.length),nestedP=nestedOk.filter(r=>r.familywise_p<=.01).length/Math.max(1,nestedOk.length);
const cm=new Map(cross.map(a=>[a.key,a])),pairs=[];for(const a of loo){const b=cm.get(a.key);if(b)pairs.push({key:a.key,fold:a.fold,rotation_present:a.rotation_present,crossfit_stat:b.attempt_statistic,loo_stat:a.attempt_statistic,abs_diff:Math.abs(b.attempt_statistic-a.attempt_statistic)});}function corr(rows){if(rows.length<2)return null;const x=rows.map(r=>r.crossfit_stat),y=rows.map(r=>r.loo_stat),mx=mean(x),my=mean(y);let n=0,dx=0,dy=0;for(let i=0;i<x.length;i++){n+=(x[i]-mx)*(y[i]-my);dx+=(x[i]-mx)**2;dy+=(y[i]-my)**2;}return dx&&dy?n/Math.sqrt(dx*dy):null;}
const diffs=pairs.map(r=>r.abs_diff),pearson=corr(pairs),p99=diffs.length?upperQuantile(diffs,.99):null;const bank=loo.filter(a=>Number.isFinite(a.attempt_statistic)),N=bank.length,looRef=Math.max(0,N-1),minP=N?1/N:null,resolution=N>=100&&looRows.filter(x=>x.familywise_ok).every(x=>x.familywise_n>=99);const fallbackRate=looFallback/Math.max(1,F.length);
const checks={geometry_pass:G.status==='PASS_ROUX_G3_DEVELOPMENT_GEOMETRY',familywise_attempts_ge_75:looOk>=75,nested_familywise_attempts_ge_75:nestedOk.length>=75,local_fallback_rate_le_0_10:fallbackRate<=.10,nested_watch_health:nestedW>=.015&&nestedW<=.12,transport_pairs_ge_75:pairs.length>=75,crossfit_loo_pearson_ge_0_90:pearson!==null&&pearson>=.90,crossfit_loo_abs_diff_p99_le_0_75:p99!==null&&p99<=.75,nested_outer_fold_excluded:outer.every(x=>x.outer_test_excluded_from_references),g3_only_features:F.every(z=>z.generation==='ROUX-MEASUREMENT-G3'),primary_1pct_resolution:resolution};
const engineeringPass=Object.values(checks).every(Boolean);const status=engineeringPass?'PASS_ROUX_G3_DEVELOPMENT_NULL_ENGINEERING':'HOLD_ROUX_G3_DEVELOPMENT_NULL_ENGINEERING';const audit={schema_version:'CR0105R113-ROUX-G3-NULL-FOUNDRY-1',generation:'ROUX-MEASUREMENT-G3',status,geometry_status:G.status,counts:{features:F.length,loo_attempts:loo.length,loo_familywise_ok:looOk,crossfit_attempts:cross.length,nested_familywise_ok:nestedOk.length,transport_pairs:pairs.length},local_reference:{loo_fallback_n:looFallback,loo_fallback_rate:fallbackRate,crossfit_fallback_n:crossFallback,nested_fallback_events:nestedFallback},loo_pseudofresh:{primary_alpha:.01,primary_rate:looP/Math.max(1,looOk),watch_alpha:.05,watch_rate:looW/Math.max(1,looOk)},nested_no_test_fold_leak:{primary_alpha:.01,primary_rate:nestedP,watch_alpha:.05,watch_rate:nestedW,outer_folds:outer},transport:{pearson_crossfit_vs_loo:pearson,abs_difference:{p50:diffs.length?upperQuantile(diffs,.5):null,p90:diffs.length?upperQuantile(diffs,.9):null,p99,max:diffs.length?Math.max(...diffs):null}},finite_sample_primary_resolution:{admitted_attempt_bank_n:N,loo_reference_n:looRef,loo_minimum_add_one_p:minP,required_loo_reference_n:99,required_total_admitted_n:100,primary_1pct_resolvable:resolution,alpha_relaxation:'PROHIBITED'},checks,engineering_pass:engineeringPass,data_role:'DEVELOPMENT_AND_CALIBRATION_ONLY',future_roux_scoring_authority:false,authority_reason:'R1.12-derived development bank cannot release G3 future authority even if engineering passes; a separately sealed genuinely fresh route court is required.',fresh_confirmatory_scoring:false,human_observations:0};audit.semantic_sha256=sha(audit);const seal={schema_version:'CR0105R113-G3-ENGINEERING-SEAL-1',generation:'ROUX-MEASUREMENT-G3',status:engineeringPass?'PASS_ENGINEERING_SEALED_FRESH_AUTHORITY_REQUIRED':'HOLD_ENGINEERING',geometry_semantic_sha256:G.semantic_sha256,null_semantic_sha256:audit.semantic_sha256,development_engineering_pass:engineeringPass,future_roux_scoring_authority:false,fresh_route_court_required:true,r112_outcomes_confirmatory:false,human_observations:0};seal.seal_sha256=sha(seal);
fs.writeFileSync(`${ROOT}/ROUX_G3_NULL_AUDIT.json`,JSON.stringify(audit,null,2)+'\n');fs.writeFileSync(`${ROOT}/ROUX_G3_LOO_ATTEMPT_BANK.json`,JSON.stringify({schema_version:'CR0105R113-G3-LOO-BANK-1',rows:looRows,human_observations:0},null,2)+'\n');fs.writeFileSync(`${ROOT}/ROUX_G3_CROSSFIT_ATTEMPT_BANK.json`,JSON.stringify({schema_version:'CR0105R113-G3-CROSSFIT-BANK-1',rows:cross,human_observations:0},null,2)+'\n');fs.writeFileSync(`${ROOT}/ROUX_G3_NESTED_ROWS.json`,JSON.stringify({schema_version:'CR0105R113-G3-NESTED-ROWS-1',rows:nestedRows,human_observations:0},null,2)+'\n');fs.writeFileSync(`${ROOT}/ROUX_G3_TRANSPORT_PAIRS.json`,JSON.stringify({schema_version:'CR0105R113-G3-TRANSPORT-PAIRS-1',rows:pairs,human_observations:0},null,2)+'\n');fs.writeFileSync(`${ROOT}/G3_ENGINEERING_SEAL.json`,JSON.stringify(seal,null,2)+'\n');console.log(JSON.stringify({status,engineering_pass:engineeringPass,loo_attempts:loo.length,loo_watch:audit.loo_pseudofresh.watch_rate,nested_watch:nestedW,transport_pearson:pearson,transport_p99:p99,resolution:audit.finite_sample_primary_resolution,seal:seal.seal_sha256},null,2));
