import fs from 'node:fs';
import { buildR19Core, parseAnnotated, sha } from '../0.10.5-r1.9/r19_quotient_core.mjs';
const ROOT=process.env.R113_ROOT||'/tmp/r113';fs.mkdirSync(ROOT,{recursive:true});
const F=JSON.parse(fs.readFileSync('research/0.10.5-r1.13/evidence-development/ROTATION_GAUGE_TRANSPORT_FIXTURE.json','utf8'));
const P=JSON.parse(fs.readFileSync('research/0.10.5-r1.13/evidence-development/ROUX_G3_GEOMETRY_AUDIT.json','utf8'));
const T=F.transport_table;
const core=await buildR19Core();const {defaultPattern,EDGE,CORNER,ORIENT,faces,faceSupport,opposite}=core;
const intersect=(a,b)=>{const s=new Set(b);return a.filter(x=>s.has(x));};
function blockMask(bottom,side){const top=opposite[bottom];return {edges:faceSupport[side].edges.filter(i=>!faceSupport[top].edges.includes(i)),corners:intersect(faceSupport[bottom].corners,faceSupport[side].corners)};}
const frames=[];for(const bottom of faces)for(const side of faces){if(side===bottom||side===opposite[bottom])continue;frames.push({key:`${bottom}|${side}`,bottom,side,first:blockMask(bottom,side),second:blockMask(bottom,opposite[side])});}
function coordSolved(p,o,i){const a=p.patternData[o],b=defaultPattern.patternData[o];return a.pieces[i]===b.pieces[i]&&a.orientation[i]===b.orientation[i];}function blockSolved(p,m){return m.edges.every(i=>coordSolved(p,EDGE,i))&&m.corners.every(i=>coordSolved(p,CORNER,i));}
function ordinary(c){return /\bfb\b/i.test(c||'')&&!/\bpseudo\s+fb\b/i.test(c||'')&&!/\bfbdr\b/i.test(c||'');}
function span(lines,phase,after=-1){let first=-1;for(let i=0;i<lines.length;i++)if(lines[i].phase===phase&&lines[i].end>lines[i].start&&lines[i].start>=after){first=i;break;}if(first<0)return null;let last=first;for(let i=first+1;i<lines.length;i++){if(lines[i].phase!==phase||lines[i].end<=lines[i].start)break;last=i;}return {start:lines[first].start,end:lines[last].end};}
function normRot(m){const s=String(m),a=s[0];if(!'xyz'.includes(a))return null;if(s.includes('2'))return `${a}2`;return s.includes("'")?`${a}'`:a;}
const inverse={};for(const rot of F.rotation_tokens){inverse[rot]={};for(let g=0;g<24;g++)inverse[rot][T[g][rot]]=g;}
function load(){const c=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-census/SEALED_ROUTE_CENSUS.json','utf8'));const a=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-acquisition/ROUX_EXPANSION_ROUTE_MANIFEST.json','utf8'));const z=[];for(const r of c.all_clean_attempts)z.push({...r,source:'SEALED_R111'});for(const r of a.records)if(r.route_source_status==='RAW_ALG_CUBING_LINK')z.push({...r,source:'R112_EXPANSION'});const m=new Map();for(const r of z)m.set(`${r.result_id}:${r.attempt_number}`,r);return [...m.values()];}
function path(tokens,fbEnd,g0,n,mode){const g=Array(n).fill(null);g[fbEnd]=g0;let x=g0;for(let j=fbEnd;j<tokens.length;j++){const r=normRot(tokens[j].move);if(r){if(mode==='forward')x=T[x][r];else if(mode==='inverse')x=inverse[r][x];}g[j+1]=x;}return g;}
function completion(states,gauges,frame,sb){let firstBreak=false;for(let i=sb.start;i<=sb.end;i++){const q=states[i].applyTransformation(ORIENT[gauges[i]]);if(!blockSolved(q,frame.first))firstBreak=true;if(blockSolved(q,frame.first)&&blockSolved(q,frame.second))return {ok:true,index:i,first_break:firstBreak};}return {ok:false,index:null,first_break:firstBreak};}
const C={eligible:0,rotation_present:0,fixed_success:0,forward_success:0,inverse_success:0,fixed_forward_same_outcome:0,fixed_forward_both_success:0,fixed_only:0,forward_only:0,neither:0,rotation_fixed_success:0,rotation_forward_success:0,rotation_inverse_success:0,rotation_fixed_forward_same:0,forward_failure_first_block_break:0};const rows=[];
for(const r of load())try{const p=parseAnnotated(r.raw_alg,'Roux'),fbLines=p.lines.filter(x=>x.phase==='ROUX_FB'&&x.end>x.start);if(fbLines.length!==1||!ordinary(fbLines[0].comment))continue;const fb=fbLines[0],sb=span(p.lines,'ROUX_SB',fb.end);if(!sb)continue;const moves=p.tokens.map(x=>x.move);let s=defaultPattern.applyAlg(r.raw_setup),states=[s];for(const m of moves){s=s.applyMove(m);states.push(s);}if(!s.experimentalIsSolved({ignorePuzzleOrientation:true,ignoreCenterOrientation:true}))continue;const prefix=[];for(let g=0;g<24;g++){const q=states[fb.end].applyTransformation(ORIENT[g]);for(const f of frames)if(blockSolved(q,f.first)&&!blockSolved(q,f.second))prefix.push({g,frame:f});}if(prefix.length!==1)continue;C.eligible++;const z=prefix[0];const fixed=path(p.tokens,fb.end,z.g,states.length,'fixed'),forward=path(p.tokens,fb.end,z.g,states.length,'forward'),inv=path(p.tokens,fb.end,z.g,states.length,'inverse');const a=completion(states,fixed,z.frame,sb),b=completion(states,forward,z.frame,sb),c=completion(states,inv,z.frame,sb);const rots=[];for(let j=fb.end;j<sb.end;j++){const rr=normRot(p.tokens[j].move);if(rr)rots.push({index:j,move:p.tokens[j].move,norm:rr});}const rp=rots.length>0;if(rp)C.rotation_present++;if(a.ok)C.fixed_success++;if(b.ok)C.forward_success++;if(c.ok)C.inverse_success++;if(a.ok===b.ok)C.fixed_forward_same_outcome++;if(a.ok&&b.ok)C.fixed_forward_both_success++;else if(a.ok&&!b.ok)C.fixed_only++;else if(!a.ok&&b.ok)C.forward_only++;else C.neither++;if(rp){if(a.ok)C.rotation_fixed_success++;if(b.ok)C.rotation_forward_success++;if(c.ok)C.rotation_inverse_success++;if(a.ok===b.ok)C.rotation_fixed_forward_same++;}if(!b.ok&&b.first_break)C.forward_failure_first_block_break++;rows.push({attempt_key:`${r.result_id}:${r.attempt_number}`,source:r.source,rotation_present:rp,rotation_tokens:rots,initial_gauge:z.g,frame_key:z.frame.key,fixed:a,forward:b,inverse:c,fixed_forward_changed:a.ok!==b.ok});}catch(e){rows.push({attempt_key:`${r.result_id}:${r.attempt_number}`,source:r.source,error:String(e?.message||e).slice(0,300)});}
const rate=(n,d)=>d?n/d:0;const out={schema_version:'CR0105R113-ROTATION-MECHANISM-DESTROY-1',generation:'ROUX-MEASUREMENT-G3',status:'POSTHOC_DIAGNOSTIC_ONLY_NO_G3_GATE_CHANGE',primary_geometry_semantic_sha256:P.semantic_sha256,fixture_semantic_sha256:F.semantic_sha256,counts:C,rates:{fixed_success:rate(C.fixed_success,C.eligible),forward_success:rate(C.forward_success,C.eligible),inverse_success:rate(C.inverse_success,C.eligible),fixed_forward_same_outcome:rate(C.fixed_forward_same_outcome,C.eligible),rotation_fixed_success:rate(C.rotation_fixed_success,C.rotation_present),rotation_forward_success:rate(C.rotation_forward_success,C.rotation_present),rotation_inverse_success:rate(C.rotation_inverse_success,C.rotation_present),rotation_fixed_forward_same:rate(C.rotation_fixed_forward_same,C.rotation_present)},interpretation_guard:'This court is posthoc. Forward/inverse/fixed comparisons cannot repair R1.13 frozen geometry or select a new transport rule in-place. They only identify the next theory branch.',post_result_gate_change:false,human_observations:0};out.semantic_sha256=sha(out);fs.writeFileSync(`${ROOT}/ROTATION_MECHANISM_DESTROY_AUDIT.json`,JSON.stringify(out,null,2)+'\n');fs.writeFileSync(`${ROOT}/ROTATION_MECHANISM_DESTROY_ROWS.json`,JSON.stringify({schema_version:'CR0105R113-ROTATION-MECHANISM-DESTROY-ROWS-1',rows,human_observations:0},null,2)+'\n');console.log(JSON.stringify(out,null,2));
