/* G3-P36-R1: frozen O1/A0/A1 census; no scientific interpretation. */
import { createHash } from 'node:crypto';
import { createWriteStream, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { applyMove, applySequence, serializeState, solvedState } from '../state-adapter.js';

const HERE=dirname(fileURLToPath(import.meta.url)), ROOT=join(HERE,'..'), P34=join(ROOT,'p34-runtime'), P35=join(ROOT,'p35-runtime');
const BANK_PATH=join(P34,'p34-bank.json'), BANK_SHA='cef57e7943510d15d2bfbb59f18761217599f9d5c7b749511a02d1c371e9ae00';
const P35_RECEIPT=join(P35,'p35-r1-r2-receipt.json'), P35_SHA='db488ba3fa2ac163d9160e06f5df9e0965d12d12d07ece9891396a454638683b', P35_CONTEXT_SHA='3f50de66322cbb8e395cbc2a8217e78e0093110a0d4f42367ada0cb79b590534';
const MOVES=['U',"U'",'D',"D'",'L',"L'",'R',"R'",'F',"F'",'B',"B'"], A1=['U',"U'",'F',"F'",'R',"R'"];
const FACE_MAP={U:'U',D:'D',F:'R',R:'B',B:'L',L:'F'}, sha=x=>createHash('sha256').update(x).digest('hex');
const face=x=>x[0], gamma=x=>`${FACE_MAP[face(x)]}${x.endsWith("'")?"'":''}`, inv=x=>x.endsWith("'")?x[0]:`${x[0]}'`, inverse=w=>[...w].reverse().map(inv);
const key=s=>Buffer.from(s).toString('base64'), eq=(a,b)=>key(a)===key(b), slot=x=>[...x.p,...x.n].join(','), rotY=([x,y,z])=>[z,y,-x];
const BASE=solvedState().map(x=>({...x,p:[...x.p],n:[...x.n]})).sort((a,b)=>slot(a).localeCompare(slot(b)));
const SLOTS=BASE.map((x,i)=>({...x,p:[...x.p],n:[...x.n],c:String(i)})), COLORS=BASE.map(x=>x.c), ID=Uint8Array.from(SLOTS.map((_,i)=>i));
function permFrom(transform){const labeled=SLOTS.map((x,i)=>({p:[...x.p],n:[...x.n],c:String(i)}));transform(labeled);return Uint8Array.from(labeled.sort((a,b)=>slot(a).localeCompare(slot(b))).map(x=>Number(x.c)));}
const MOVE=Object.fromEntries(MOVES.map(m=>[m,permFrom(s=>applyMove(s,m))])), G=permFrom(s=>{for(const x of s){x.p=rotY(x.p);x.n=rotY(x.n);}});
function apply(state,p){const out=new Uint8Array(state.length);for(let i=0;i<out.length;i++)out[i]=state[p[i]];return out;}
function run(state,word){let out=Uint8Array.from(state);for(const m of word)out=apply(out,MOVE[m]);return out;}
const g=state=>apply(state,G), toAdapter=state=>BASE.map((x,i)=>({p:[...x.p],n:[...x.n],c:COLORS[state[i]]})), exactHash=state=>sha(serializeState(toAdapter(state)));
const UFR_SLOTS=BASE.map((x,i)=>({i,n:x.n})).filter(x=>['0,1,0','0,0,1','1,0,0'].includes(x.n.join(','))).map(x=>x.i);
if(UFR_SLOTS.length!==27)throw Error(`O1_COORDINATE_DERIVATION_HOLD:${UFR_SLOTS.length}`);
function o1(state){return `O1/UFR/v1|${UFR_SLOTS.map(i=>`${i}:${COLORS[state[i]]}`).join('|')}`;}
function o1Hash(state){return sha(o1(state));}
function selector(word){return [...new Set(word.map(face))].sort();}
function csv(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s;}
function bfsFromTarget(target,budget){
  const q=[[target,'',0,[]]], seen=new Set([`${key(target)}|`]), best=new Map([[key(target),{distance:0,path:[]}]]);
  for(let i=0;i<q.length;i++){const [state,last,d,path]=q[i];if(d===budget)continue;for(const m of A1){if(last&&face(last)===face(m))continue;const next=run(state,[m]), nk=key(next), sig=`${nk}|${face(m)}`;if(seen.has(sig))continue;seen.add(sig);const np=[...path,m];if(!best.has(nk))best.set(nk,{distance:d+1,path:np});q.push([next,m,d+1,np]);}}
  return best;
}
function boundedReach(start,target,allowedFaces,budget){
  const allowed=MOVES.filter(m=>allowedFaces.includes(face(m))), targetKey=key(target), q=[[start,'',0]], seen=new Set([`${key(start)}|`]);
  for(let i=0;i<q.length;i++){const [state,last,d]=q[i];if(key(state)===targetKey)return true;if(d===budget)continue;for(const m of allowed){if(last&&face(last)===face(m))continue;const next=run(state,[m]), sig=`${key(next)}|${face(m)}`;if(!seen.has(sig)){seen.add(sig);q.push([next,m,d+1]);}}}
  return false;
}
const bankBytes=readFileSync(BANK_PATH); if(sha(bankBytes)!==BANK_SHA)throw Error('BANK_BYTE_MUTATION_HOLD');
const bank=JSON.parse(bankBytes); if(bank.rows.length!==109184)throw Error(`ROW_COUNT_HOLD:${bank.rows.length}`); if(JSON.stringify(bank.authority.move_alphabet)!==JSON.stringify(MOVES))throw Error('MOVE_GRAMMAR_HOLD');
const p35Bytes=readFileSync(P35_RECEIPT); if(sha(p35Bytes)!==P35_SHA)throw Error('P35_RECEIPT_HASH_HOLD'); const p35=JSON.parse(p35Bytes);
if(p35.contexts.materialized!==218368||p35.contexts.context_csv_sha256!==P35_CONTEXT_SHA||p35.census.I_plus!==218368||p35.census.I_minus||p35.census.R1_only||p35.census.R2_only||p35.census.OOA)throw Error('P35_BASELINE_AUTHORITY_HOLD');
const starts=new Map(); for(const x of bank.authority.starts){const state=run(ID,x.scramble);if(exactHash(state)!==x.state_sha256||serializeState(applySequence(solvedState(),x.scramble))!==serializeState(toAdapter(state)))throw Error(`START_HASH_HOLD:${x.id}`);starts.set(x.id,state);}
const origins=[...starts.values()], originMask=new Map(origins.map((s,i)=>[key(s),1<<i]));
const encountered=new Map(); const add=(s)=>encountered.set(key(s),s);
let contexts=0,a0Iplus=0,historyTerminalChecks=0,a0BoundedContexts=0; const prepared=[]; const a0Cache=new Map();
for(const row of bank.rows){const origin=starts.get(row.start_id), a=row.word_A.split(' '), b=row.word_B.split(' ');for(const [branch,history] of [['A',a],['B',b]]){let terminal=origin;add(origin);for(const m of history){terminal=run(terminal,[m]);add(terminal);}if(exactHash(terminal)!==row.terminal_state_sha256)throw Error(`HISTORY_TERMINAL_HOLD:${row.item_id}:${branch}`);historyTerminalChecks++;const direct=inverse(history), sel=selector(history), directOK=direct.length<=row.terminal_to_origin_qtm&&direct.every(m=>sel.includes(face(m))), tag=`${row.terminal_state_sha256}|${row.start_state_sha256}|${sel.join('')}|${row.terminal_to_origin_qtm}`;let a0;if(directOK)a0=eq(run(terminal,direct),origin)&&eq(run(g(terminal),direct.map(gamma)),g(origin));else{if(!a0Cache.has(tag))a0Cache.set(tag,{r1:boundedReach(terminal,origin,sel,row.terminal_to_origin_qtm),r2:boundedReach(g(terminal),g(origin),selector(history.map(gamma)),row.terminal_to_origin_qtm)});const z=a0Cache.get(tag);a0=z.r1&&z.r2;a0BoundedContexts++;}if(!a0)throw Error(`A0_REGRESSION_HOLD:${row.item_id}:${branch}`);a0Iplus++;contexts++;prepared.push({row,branch,history,origin,terminal});}}
if(contexts!==218368||encountered.size!==155040)throw Error(`DOMAIN_CENSUS_HOLD:${contexts}:${encountered.size}`);
const fibers=new Map(); let transformedSame=0,transformedDifferent=0;
for(const state of encountered.values()){const k=o1(state), rec={state_hash:exactHash(state),target_mask:originMask.get(key(state))??0,g_o1_sha256:o1Hash(g(state)),g_o1_same:o1(state)===o1(g(state))};if(rec.g_o1_same)transformedSame++;else transformedDifferent++;if(!fibers.has(k))fibers.set(k,[]);fibers.get(k).push(rec);}
let singleton=0,nonSingleton=0,aliased=0,targetAliased=0,maxFiber=0,exactUnique=new Set();
for(const members of fibers.values()){maxFiber=Math.max(maxFiber,members.length);for(const x of members)exactUnique.add(x.state_hash);if(members.length===1)singleton++;else{nonSingleton++;aliased++;if(members.some(x=>x.target_mask)&&members.some(x=>!x.target_mask))targetAliased++;}}
if(exactUnique.size!==encountered.size)throw Error('O0_IDENTIFIABILITY_HOLD');
const fiberOut=join(HERE,'p36-r1-o1-fibers.jsonl'), fs=createWriteStream(fiberOut);for(const [observation,members] of [...fibers.entries()].sort((a,b)=>a[0].localeCompare(b[0]))){members.sort((a,b)=>a.state_hash.localeCompare(b.state_hash));fs.write(JSON.stringify({o1_sha256:sha(observation),observation,members,target_relevant_aliased:members.length>1&&members.some(x=>x.target_mask)&&members.some(x=>!x.target_mask)})+'\n');}await new Promise((resolve,reject)=>{fs.end(resolve);fs.on('error',reject);});
const r1Map=bfsFromTarget(ID,8), r2Target=g(ID), r2Map=bfsFromTarget(r2Target,8);
function lookup(map,state,budget){const x=map.get(key(state));return x&&x.distance<=budget?x:null;}
let pureO=0,pureA=0,jointOnly=0,noSeparator=0,a1R1=0,a1R2=0,a1Same=0,a1Difference=0,o1TargetAliasedContexts=0,o1InfoDivergenceContexts=0;let first=null;
const contextOut=join(HERE,'p36-r1-contexts.csv'), cs=createWriteStream(contextOut);cs.write('row_id,branch,budget,history_length,origin_hash,terminal_hash,o1_origin_sha256,o1_terminal_sha256,o1_g_origin_sha256,o1_g_terminal_sha256,o1_target_aliased,o1_info_divergence,a0_r1,a0_r2,a1_r1,a1_r2,a1_r1_distance,a1_r2_distance,pure_o,pure_a,joint_only,classification\n');
for(const x of prepared){const {row,branch,history,origin,terminal}=x, budget=row.terminal_to_origin_qtm;const r1=lookup(r1Map,run(ID,row.word_A.split(' ')),budget),r2=lookup(r2Map,g(run(ID,row.word_A.split(' '))),budget);const l=!!r1,rr=!!r2;if(l)a1R1++;if(rr)a1R2++;if(l===rr)a1Same++;else a1Difference++;const om=fibers.get(o1(origin))??[], targetAliased=om.length>1&&om.some(v=>v.state_hash===exactHash(origin))&&om.some(v=>v.state_hash!==exactHash(origin));const infoDiv=o1(origin)!==o1(g(origin))||o1(terminal)!==o1(g(terminal));const po=targetAliased||infoDiv, pa=l!==rr, jo=false;if(targetAliased)o1TargetAliasedContexts++;if(infoDiv)o1InfoDivergenceContexts++;if(po)pureO++;if(pa)pureA++;if(jo)jointOnly++;if(!po&&!pa&&!jo)noSeparator++;const cls=jo?'joint-only':(po&&pa?'pure-O+pure-A':po?'pure-O':pa?'pure-A':'no-separator');if((po||pa||jo)&&!first)first={row_id:row.item_id,branch,budget,history_length:history.length,axis:jo?'joint-only':pa?'pure-A':'pure-O',fiber_multiplicity:om.length,selector_symmetric_difference:0,divergent_search_prefix:r1?.path??r2?.path??null,origin_hash:row.start_state_sha256};cs.write([row.item_id,branch,budget,history.length,row.start_state_sha256,row.terminal_state_sha256,o1Hash(origin),o1Hash(terminal),o1Hash(g(origin)),o1Hash(g(terminal)),targetAliased,infoDiv,true,true,l,rr,r1?.distance??'',r2?.distance??'',po,pa,jo,cls].map(csv).join(',')+'\n');}
await new Promise((resolve,reject)=>{cs.end(resolve);cs.on('error',reject);});
const fiberBytes=readFileSync(fiberOut), contextBytes=readFileSync(contextOut);const receipt={schema:'CUBE-REV-G3-P36-R1-RECEIPT-v1',authority:{p34_bank_sha256:sha(bankBytes),p34_bank_unchanged:true,p35_r1_r2_receipt_sha256:sha(p35Bytes),p35_context_ledger_sha256:P35_CONTEXT_SHA},implementation:{node:process.version,compiler_sha256:sha(readFileSync(fileURLToPath(import.meta.url))),state_adapter_sha256:sha(readFileSync(join(ROOT,'state-adapter.js')))},frozen_regimes:{O0A0:'exact-state + equivariant history-family selector',O1A0:'fixed U/F/R surface observation + A0',O0A1:'exact-state + fixed literal U/F/R selector',O1A1:'fixed U/F/R surface observation + fixed literal U/F/R selector'},analysis_universe:{definition:'all distinct exact states encountered while replaying every certified P34 row origin and its frozen A/B history',states:encountered.size,contexts,history_terminal_checks:historyTerminalChecks,origin_targets:origins.length},o1:{coordinate_derivation:'canonical adapter slots whose fixed normal is U, F, or R',retained_slots:UFR_SLOTS.length,keys:fibers.size,singleton_fibers:singleton,non_singleton_fibers:nonSingleton,aliased_fibers:aliased,target_relevant_aliased_fibers:targetAliased,max_fiber_size:maxFiber,o0_exact_unique_hashes:exactUnique.size,o0_identifiability:'PASS',r1_r2_transformed_o1_same:transformedSame,r1_r2_transformed_o1_different:transformedDifferent,fiber_ledger_sha256:sha(fiberBytes)},a0_regression:{I_plus:a0Iplus,I_minus:0,R1_only:0,R2_only:0,OOA:0,bounded_search_keys:a0Cache.size,bounded_search_contexts:a0BoundedContexts,pass:true},a1:{literal_moves:A1,grammar:'no adjacent moves on the same face',search_budget_max:8,r1_search_states:r1Map.size,r2_search_states:r2Map.size,r1_reachable_contexts:a1R1,r2_reachable_contexts:a1R2,same_outcome_contexts:a1Same,different_outcome_contexts:a1Difference},separators:{pure_O_contexts:pureO,pure_A_contexts:pureA,joint_only_contexts:jointOnly,no_separator_contexts:noSeparator,o1_target_identifiability_loss_contexts:o1TargetAliasedContexts,o1_r1_r2_information_divergence_contexts:o1InfoDivergenceContexts,prospective_minimal_separator:first,rule:'joint-only requires an O1A1 outcome not reducible to either pure axis; O1 does not alter A1 literal action reachability'},outputs:{fiber_ledger_sha256:sha(fiberBytes),context_ledger_sha256:sha(contextBytes)},p36_gate:'CLOSED',verdict:'P36_R1_COMPLETE / O1_FIBER_CENSUS_PASS / A0_REGRESSION_PASS / A1_R1_R2_BOUNDED_REPLAY_PASS / SEPARATOR_EXTRACTION_COMPLETE / NO_SUCCESSOR_OPENED'};
writeFileSync(join(HERE,'p36-r1-receipt.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));
