import fs from 'node:fs';
import { buildR19Core, parseAnnotated, sha } from '../0.10.5-r1.9/r19_quotient_core.mjs';
const OUT=process.env.R111_FB_ROOT||'/tmp/r111fb';fs.mkdirSync(OUT,{recursive:true});
const c=await buildR19Core();const {defaultPattern,EDGE,CORNER,CENTER,ORIENT,faces,faceSupport,opposite,canonicalizeByCenters}=c;
const intersect=(a,b)=>{const s=new Set(b);return a.filter(x=>s.has(x));};
function mask(bottom,side){const top=opposite[bottom];return {bottom,side,edges:faceSupport[side].edges.filter(i=>!faceSupport[top].edges.includes(i)),corners:intersect(faceSupport[bottom].corners,faceSupport[side].corners)};}
const frames=[];for(const b of faces)for(const s of faces)if(s!==b&&s!==opposite[b])frames.push({key:`${b}|${s}`,first:mask(b,s)});
function solved(p,o,i){const a=p.patternData[o],b=defaultPattern.patternData[o];return a.pieces[i]===b.pieces[i]&&a.orientation[i]===b.orientation[i];}
function block(p,m){return m.edges.every(i=>solved(p,EDGE,i))&&m.corners.every(i=>solved(p,CORNER,i));}
function centerDefault(p){const a=p.patternData[CENTER].pieces,b=defaultPattern.patternData[CENTER].pieces;return a.length===b.length&&a.every((x,i)=>x===b[i]);}
function centerExactFrames(raw){const x=canonicalizeByCenters(raw);if(!x.ok)return [];return frames.filter(f=>block(x.pattern,f.first));}
function orientationFreeGroups(raw){const groups=new Map();for(let oi=0;oi<ORIENT.length;oi++){const q=raw.applyTransformation(ORIENT[oi]);for(const f of frames)if(block(q,f.first)){if(!groups.has(f.key))groups.set(f.key,[]);groups.get(f.key).push({oi,center_default:centerDefault(q)});}}return groups;}
function fam(comment){const x=String(comment||'').toLowerCase();if(/pseudo\s+fb/.test(x))return 'PSEUDO_FB';if(/\bfbdr\b/.test(x))return 'FBDR';if(/\bfb\b/.test(x))return 'FB';return 'OTHER';}
function load(){const a=JSON.parse(fs.readFileSync('research/0.10.5-r1.7/evidence-full-route/FULL_ROUTE_SAMPLE_MANIFEST.json','utf8')).records.map(r=>({...r,source:'R17'}));const b=JSON.parse(fs.readFileSync('research/0.10.5-r1.8/evidence-holdout-a/HOLDOUT_A_ROUTE_MANIFEST.json','utf8')).records.map(r=>({...r,source:'R18'}));return [...a,...b].filter(r=>r.method==='Roux'&&r.route_source_status==='RAW_ALG_CUBING_LINK');}
const rows=[];for(const r of load()){const z={result_id:r.result_id,attempt_number:r.attempt_number,reco_id:r.reco_id,source:r.source};try{const p=parseAnnotated(r.raw_alg,'Roux'),moves=p.tokens.map(x=>x.move);let s=defaultPattern.applyAlg(r.raw_setup),states=[s];for(const m of moves){s=s.applyMove(m);states.push(s);}if(!s.experimentalIsSolved({ignorePuzzleOrientation:true,ignoreCenterOrientation:true})){z.status='FINAL_NOT_SOLVED';rows.push(z);continue;}const fb=p.lines.find(x=>x.phase==='ROUX_FB'&&x.end>x.start);if(!fb){z.status='NO_FB';rows.push(z);continue;}const raw=states[fb.end],cg=centerExactFrames(raw),og=orientationFreeGroups(raw);z.status='EVALUATED';z.fb_comment=fb.comment;z.fb_family=fam(fb.comment);z.center_exact_frame_n=cg.length;z.center_exact_frames=cg.map(x=>x.key);z.orientation_free_group_n=og.size;z.orientation_free_groups=[...og.entries()].map(([key,reps])=>({key,representative_n:reps.length,center_default_representative_n:reps.filter(x=>x.center_default).length,representative_indices:reps.map(x=>x.oi)}));z.orientation_free_unique=og.size===1;if(og.size===1){const [key,reps]=[...og.entries()][0];z.unique_group_key=key;z.unique_group_rep_n=reps.length;z.unique_group_center_default_rep_n=reps.filter(x=>x.center_default).length;z.unique_group_requires_center_relabel=reps.every(x=>!x.center_default);}rows.push(z);}catch(e){z.status='ERROR';z.error=String(e?.message||e).slice(0,220);rows.push(z);}}
const clean=rows.filter(r=>r.status==='EVALUATED'),n=clean.length;const families={};for(const f of ['FB','FBDR','PSEUDO_FB','OTHER']){const a=clean.filter(r=>r.fb_family===f);families[f]={n:a.length,orientation_free_unique:a.filter(r=>r.orientation_free_unique).length,center_exact_unique:a.filter(r=>r.center_exact_frame_n===1).length,requires_center_relabel:a.filter(r=>r.unique_group_requires_center_relabel).length};}
const audit={schema_version:'CR0105R111-FB-SEMANTIC-LOCALIZATION-1',status:'POSTHOC_DIAGNOSTIC_ONLY_NO_R111_GATE_CHANGE',authority_changed:false,r111_holds_preserved:true,counts:{evaluated:n,errors:rows.filter(r=>r.status==='ERROR').length,orientation_free_unique:clean.filter(r=>r.orientation_free_unique).length,center_exact_unique:clean.filter(r=>r.center_exact_frame_n===1).length,unique_group_requires_center_relabel:clean.filter(r=>r.unique_group_requires_center_relabel).length,unique_group_has_center_default_rep:clean.filter(r=>r.orientation_free_unique&&r.unique_group_center_default_rep_n>0).length},rates:{orientation_free_unique:n?clean.filter(r=>r.orientation_free_unique).length/n:null,center_exact_unique:n?clean.filter(r=>r.center_exact_frame_n===1).length/n:null,requires_center_relabel_given_orientation_free_unique:clean.filter(r=>r.orientation_free_unique).length?clean.filter(r=>r.unique_group_requires_center_relabel).length/clean.filter(r=>r.orientation_free_unique).length:null},fb_comment_family:families,interpretation_guard:'Diagnostic only. Orientation-free frame uniqueness cannot be treated as center-consistent physical block identification unless center/color relabel semantics are prospectively justified.',fresh_network_read:false,human_observations:0};audit.semantic_sha256=sha(audit);fs.writeFileSync(`${OUT}/FB_SEMANTIC_LOCALIZATION_AUDIT.json`,JSON.stringify(audit,null,2)+'\n');fs.writeFileSync(`${OUT}/FB_SEMANTIC_LOCALIZATION_ROWS.json`,JSON.stringify({rows,human_observations:0},null,2)+'\n');console.log(JSON.stringify(audit,null,2));