import fs from 'node:fs';
import { buildR19Core, parseAnnotated, sha } from '../0.10.5-r1.9/r19_quotient_core.mjs';
const OUT=process.env.R111_PHASE_ROOT||'/tmp/r111phase';fs.mkdirSync(OUT,{recursive:true});
const c=await buildR19Core();const {defaultPattern,EDGE,CORNER,faces,faceSupport,opposite,canonicalizeByCenters}=c;
const intersect=(a,b)=>{const s=new Set(b);return a.filter(x=>s.has(x));};
function mask(bottom,side){const top=opposite[bottom];return {bottom,side,edges:faceSupport[side].edges.filter(i=>!faceSupport[top].edges.includes(i)),corners:intersect(faceSupport[bottom].corners,faceSupport[side].corners)};}
const frames=[];for(const b of faces)for(const s of faces)if(s!==b&&s!==opposite[b])frames.push({key:`${b}|${s}`,bottom:b,side:s,first:mask(b,s),second:mask(b,opposite[s])});
function solved(p,o,i){const a=p.patternData[o],b=defaultPattern.patternData[o];return a.pieces[i]===b.pieces[i]&&a.orientation[i]===b.orientation[i];}
function block(p,m){return m.edges.every(i=>solved(p,EDGE,i))&&m.corners.every(i=>solved(p,CORNER,i));}
function canonical(raw){const x=canonicalizeByCenters(raw);return x.ok?x.pattern:null;}
function exactFrames(raw){const p=canonical(raw);if(!p)return [];return frames.filter(f=>block(p,f.first));}
function bothAt(raw,f){const p=canonical(raw);return !!p&&block(p,f.first)&&block(p,f.second);}
function load(){const a=JSON.parse(fs.readFileSync('research/0.10.5-r1.7/evidence-full-route/FULL_ROUTE_SAMPLE_MANIFEST.json','utf8')).records.map(r=>({...r,source:'R17'}));const b=JSON.parse(fs.readFileSync('research/0.10.5-r1.8/evidence-holdout-a/HOLDOUT_A_ROUTE_MANIFEST.json','utf8')).records.map(r=>({...r,source:'R18'}));return [...a,...b].filter(r=>r.method==='Roux'&&r.route_source_status==='RAW_ALG_CUBING_LINK');}
const rows=[];for(const r of load()){const z={result_id:r.result_id,attempt_number:r.attempt_number,reco_id:r.reco_id,source:r.source};try{const p=parseAnnotated(r.raw_alg,'Roux'),moves=p.tokens.map(x=>x.move);let s=defaultPattern.applyAlg(r.raw_setup),states=[s];for(const m of moves){s=s.applyMove(m);states.push(s);}if(!s.experimentalIsSolved({ignorePuzzleOrientation:true,ignoreCenterOrientation:true})){z.status='FINAL_NOT_SOLVED';rows.push(z);continue;}const fb=p.lines.filter(x=>x.phase==='ROUX_FB'&&x.end>x.start),sb=p.lines.filter(x=>x.phase==='ROUX_SB'&&x.end>x.start),cmll=p.lines.find(x=>x.phase==='ROUX_CMLL'&&x.end>x.start);if(!fb.length||!sb.length){z.status='MISSING_PHASE';rows.push(z);continue;}const ff=exactFrames(states[fb[0].end]),lf=exactFrames(states[fb[fb.length-1].end]);z.fb_line_n=fb.length;z.sb_line_n=sb.length;z.fb_comments=fb.map(x=>x.comment);z.first_fb_exact_frame_n=ff.length;z.last_fb_exact_frame_n=lf.length;z.first_fb_exact_frames=ff.map(x=>x.key);z.last_fb_exact_frames=lf.map(x=>x.key);if(lf.length===1){const f=lf[0];z.last_fb_frame_key=f.key;z.first_sb_both=bothAt(states[sb[0].end],f);z.last_sb_both=bothAt(states[sb[sb.length-1].end],f);z.pre_cmll_both=cmll?bothAt(states[cmll.start],f):null;let earliest=null;for(let i=fb[fb.length-1].end;i<states.length;i++)if(bothAt(states[i],f)){earliest=i;break;}z.earliest_both=earliest;z.earliest_by_last_sb=earliest!=null&&earliest<=sb[sb.length-1].end;z.earliest_by_pre_cmll=earliest!=null&&cmll&&earliest<=cmll.start;}z.status='EVALUATED';rows.push(z);}catch(e){z.status='ERROR';z.error=String(e?.message||e).slice(0,220);rows.push(z);}}
const clean=rows.filter(r=>r.status==='EVALUATED'),n=clean.length,oneLast=clean.filter(r=>r.last_fb_exact_frame_n===1),m=oneLast.length;const dist=k=>Object.fromEntries([...new Set(clean.map(r=>r[k]))].sort((a,b)=>a-b).map(v=>[String(v),clean.filter(r=>r[k]===v).length]));const audit={schema_version:'CR0105R111-PHASE-BOUNDARY-LOCALIZATION-1',status:'POSTHOC_DIAGNOSTIC_ONLY_NO_R111_GATE_CHANGE',authority_changed:false,r111_holds_preserved:true,counts:{evaluated:n,errors:rows.filter(r=>r.status==='ERROR').length,first_fb_unique_center_anchored:clean.filter(r=>r.first_fb_exact_frame_n===1).length,last_fb_unique_center_anchored:m,last_fb_frame_first_sb_both:oneLast.filter(r=>r.first_sb_both).length,last_fb_frame_last_sb_both:oneLast.filter(r=>r.last_sb_both).length,last_fb_frame_pre_cmll_both:oneLast.filter(r=>r.pre_cmll_both===true).length,last_fb_frame_pre_cmll_observed:oneLast.filter(r=>r.pre_cmll_both!==null).length,last_fb_frame_earliest_both_found:oneLast.filter(r=>r.earliest_both!=null).length},rates:{first_fb_unique_center_anchored:n?clean.filter(r=>r.first_fb_exact_frame_n===1).length/n:null,last_fb_unique_center_anchored:n?m/n:null,last_sb_both_given_last_fb_unique:m?oneLast.filter(r=>r.last_sb_both).length/m:null,pre_cmll_both_given_last_fb_unique_and_observed:oneLast.filter(r=>r.pre_cmll_both!==null).length?oneLast.filter(r=>r.pre_cmll_both===true).length/oneLast.filter(r=>r.pre_cmll_both!==null).length:null},distributions:{fb_line_n:dist('fb_line_n'),sb_line_n:dist('sb_line_n'),first_fb_exact_frame_n:dist('first_fb_exact_frame_n'),last_fb_exact_frame_n:dist('last_fb_exact_frame_n')},interpretation_guard:'This diagnostic may motivate R1.12 only. It cannot repair or release R1.11.',fresh_network_read:false,human_observations:0};audit.semantic_sha256=sha(audit);fs.writeFileSync(`${OUT}/PHASE_BOUNDARY_LOCALIZATION_AUDIT.json`,JSON.stringify(audit,null,2)+'\n');fs.writeFileSync(`${OUT}/PHASE_BOUNDARY_LOCALIZATION_ROWS.json`,JSON.stringify({rows,human_observations:0},null,2)+'\n');console.log(JSON.stringify(audit,null,2));