import fs from 'node:fs';
import crypto from 'node:crypto';
import { buildR19Core, parseAnnotated, sha } from '../0.10.5-r1.9/r19_quotient_core.mjs';

const OUT=process.env.R111_SB_ROOT||'/tmp/r111sb';fs.mkdirSync(OUT,{recursive:true});
const core=await buildR19Core();
const {defaultPattern,EDGE,CORNER,ORIENT,faces,faceSupport,opposite}=core;
const intersect=(a,b)=>{const s=new Set(b);return a.filter(x=>s.has(x));};
function blockMask(bottom,side){const top=opposite[bottom];if(side===bottom||side===top)return null;return {bottom,side,top,edges:faceSupport[side].edges.filter(i=>!faceSupport[top].edges.includes(i)),corners:intersect(faceSupport[bottom].corners,faceSupport[side].corners)};}
const FRAMES=[];for(const bottom of faces)for(const side of faces){if(side===bottom||side===opposite[bottom])continue;FRAMES.push({key:`${bottom}|${side}`,bottom,side,first:blockMask(bottom,side),second:blockMask(bottom,opposite[side])});}
function solvedCoord(p,o,i){const a=p.patternData[o],b=defaultPattern.patternData[o];return a.pieces[i]===b.pieces[i]&&a.orientation[i]===b.orientation[i];}
function blockSolved(p,m){return m.edges.every(i=>solvedCoord(p,EDGE,i))&&m.corners.every(i=>solvedCoord(p,CORNER,i));}
function bothBlocks(p,f){return blockSolved(p,f.first)&&blockSolved(p,f.second);}
function candidateGroups(raw){const groups=new Map();for(let oi=0;oi<ORIENT.length;oi++){const q=raw.applyTransformation(ORIENT[oi]);for(const f of FRAMES)if(blockSolved(q,f.first)){if(!groups.has(f.key))groups.set(f.key,[]);groups.get(f.key).push(oi);}}return groups;}
function family(comment){const c=String(comment||'').toLowerCase();if(/flipped\s+sp/.test(c))return 'FLIPPED_SP';if(/\bsp\b/.test(c))return 'SP';if(/\bss\b/.test(c))return 'SS';if(/\bsb\b/.test(c))return 'SB';return 'OTHER';}
function load(){const a=JSON.parse(fs.readFileSync('research/0.10.5-r1.7/evidence-full-route/FULL_ROUTE_SAMPLE_MANIFEST.json','utf8')).records.map(r=>({...r,source:'R17'}));const b=JSON.parse(fs.readFileSync('research/0.10.5-r1.8/evidence-holdout-a/HOLDOUT_A_ROUTE_MANIFEST.json','utf8')).records.map(r=>({...r,source:'R18'}));return [...a,...b].filter(r=>r.method==='Roux'&&r.route_source_status==='RAW_ALG_CUBING_LINK');}
function contiguousSpan(lines){if(!lines.length)return null;const sorted=[...lines].sort((a,b)=>a.line_id-b.line_id),first=sorted[0];let last=first;for(let i=1;i<sorted.length;i++){if(sorted[i].line_id===last.line_id+1){last=sorted[i];}else break;}return {start:first.start,end:last.end,first_line_id:first.line_id,last_line_id:last.line_id};}
const rows=[];for(const r of load()){
 const rec={result_id:r.result_id,attempt_number:r.attempt_number,reco_id:r.reco_id,source:r.source};
 try{
  const p=parseAnnotated(r.raw_alg,'Roux'),moves=p.tokens.map(x=>x.move);let s=defaultPattern.applyAlg(r.raw_setup),states=[s];for(const m of moves){s=s.applyMove(m);states.push(s);}if(!s.experimentalIsSolved({ignorePuzzleOrientation:true,ignoreCenterOrientation:true})){rec.status='FINAL_NOT_SOLVED';rows.push(rec);continue;}
  const fb=p.lines.find(x=>x.phase==='ROUX_FB'&&x.end>x.start);const sbLines=p.lines.filter(x=>x.phase==='ROUX_SB'&&x.end>x.start);const cmll=p.lines.find(x=>x.phase==='ROUX_CMLL'&&x.end>x.start);const lse=p.lines.find(x=>x.phase==='ROUX_LSE'&&x.end>x.start);if(!fb||!sbLines.length){rec.status='MISSING_FB_OR_SB';rows.push(rec);continue;}
  const groups=candidateGroups(states[fb.end]);if(groups.size!==1){rec.status='FRAME_GROUP_NOT_UNIQUE';rec.frame_group_n=groups.size;rows.push(rec);continue;}const [frameKey,reps]=[...groups.entries()][0],frame=FRAMES.find(f=>f.key===frameKey),oi=reps[0],qs=states.map(x=>x.applyTransformation(ORIENT[oi]));
  const first=sbLines[0],last=sbLines[sbLines.length-1],span=contiguousSpan(sbLines);const passAt=i=>i!=null&&i>=0&&i<qs.length&&bothBlocks(qs[i],frame);const firstPass=passAt(first.end),lastPass=passAt(last.end),spanPass=span?passAt(span.end):false,preCmll=cmll?passAt(cmll.start):null,preLse=lse?passAt(lse.start):null;
  let earliest=null;for(let i=fb.end;i<qs.length;i++)if(passAt(i)){earliest=i;break;}
  rec.status='EVALUATED';rec.frame_key=frameKey;rec.frame_rep_n=reps.length;rec.sb_line_n=sbLines.length;rec.sb_comments=sbLines.map(x=>x.comment);rec.sb_families=sbLines.map(x=>family(x.comment));rec.first_sb={line_id:first.line_id,start:first.start,end:first.end,comment:first.comment,family:family(first.comment),pass:firstPass};rec.last_sb={line_id:last.line_id,start:last.start,end:last.end,comment:last.comment,family:family(last.comment),pass:lastPass};rec.contiguous_span={...span,pass:spanPass};rec.pre_cmll={index:cmll?.start??null,pass:preCmll};rec.pre_lse={index:lse?.start??null,pass:preLse};rec.earliest_both_blocks_index=earliest;rec.earliest_relative=earliest==null?'NEVER':earliest<=first.end?'BY_FIRST_SB_END':earliest<=last.end?'AFTER_FIRST_BY_LAST_SB_END':cmll&&earliest<=cmll.start?'AFTER_LAST_BY_PRE_CMLL':lse&&earliest<=lse.start?'AFTER_CMLL_BY_PRE_LSE':'LATER';rec.first_block_preserved_at_first=blockSolved(qs[first.end],frame.first);rec.second_block_solved_at_first=blockSolved(qs[first.end],frame.second);rec.first_block_preserved_at_last=blockSolved(qs[last.end],frame.first);rec.second_block_solved_at_last=blockSolved(qs[last.end],frame.second);rows.push(rec);
 }catch(e){rec.status='ERROR';rec.error=String(e?.message||e).slice(0,240);rows.push(rec);}
}
const clean=rows.filter(r=>r.status==='EVALUATED');const n=clean.length;const count=fn=>clean.filter(fn).length;const fam={};for(const f of ['SB','SS','SP','FLIPPED_SP','OTHER']){const x=clean.filter(r=>r.first_sb.family===f);fam[f]={n:x.length,first_pass:x.filter(r=>r.first_sb.pass).length,last_pass:x.filter(r=>r.last_sb.pass).length,pre_cmll_pass:x.filter(r=>r.pre_cmll.pass===true).length};}
const rel={};for(const r of clean)rel[r.earliest_relative]=(rel[r.earliest_relative]||0)+1;
const audit={schema_version:'CR0105R111-SB-FAILURE-LOCALIZATION-1',status:'POSTHOC_DIAGNOSTIC_ONLY_NO_R111_GATE_CHANGE',authority_changed:false,r111_geometry_hold_preserved:true,r111_null_authority_hold_preserved:true,counts:{manifest_rows:rows.length,evaluated:n,errors:rows.filter(r=>r.status==='ERROR').length,first_sb_endpoint_pass:count(r=>r.first_sb.pass),last_sb_endpoint_pass:count(r=>r.last_sb.pass),contiguous_span_endpoint_pass:count(r=>r.contiguous_span.pass),pre_cmll_pass:count(r=>r.pre_cmll.pass===true),pre_cmll_observed:count(r=>r.pre_cmll.index!=null),pre_lse_pass:count(r=>r.pre_lse.pass===true),earliest_both_blocks_found:count(r=>r.earliest_both_blocks_index!=null),first_block_preserved_at_first:count(r=>r.first_block_preserved_at_first),second_block_solved_at_first:count(r=>r.second_block_solved_at_first),first_block_preserved_at_last:count(r=>r.first_block_preserved_at_last),second_block_solved_at_last:count(r=>r.second_block_solved_at_last)},rates:{first_sb_endpoint_pass:n?count(r=>r.first_sb.pass)/n:null,last_sb_endpoint_pass:n?count(r=>r.last_sb.pass)/n:null,contiguous_span_endpoint_pass:n?count(r=>r.contiguous_span.pass)/n:null,pre_cmll_pass_given_observed:count(r=>r.pre_cmll.index!=null)?count(r=>r.pre_cmll.pass===true)/count(r=>r.pre_cmll.index!=null):null,earliest_both_blocks_found:n?count(r=>r.earliest_both_blocks_index!=null)/n:null},earliest_relative_distribution:rel,first_sb_comment_family:fam,interpretation_guard:'Diagnostic localization only. No endpoint rule is promoted into R1.11 geometry or future authority.',fresh_network_read:false,human_observations:0};audit.semantic_sha256=sha(audit);fs.writeFileSync(`${OUT}/SB_FAILURE_LOCALIZATION_AUDIT.json`,JSON.stringify(audit,null,2)+'\n');fs.writeFileSync(`${OUT}/SB_FAILURE_LOCALIZATION_ROWS.json`,JSON.stringify({rows,human_observations:0},null,2)+'\n');console.log(JSON.stringify(audit,null,2));
