import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {solvedState,applyMove,serializeState,applySequence} from '../state-adapter.js';
const here=dirname(fileURLToPath(import.meta.url)),root=join(here,'..'),sha=x=>createHash('sha256').update(x).digest('hex');
mkdirSync(here,{recursive:true});
const manifest=[],inputs=[];
function input(path,expected){const b=readFileSync(join(root,path)),h=sha(b);if(h!==expected)throw Error('INPUT_HASH_HOLD '+path);inputs.push({path,sha256:h,bytes:b.length});return JSON.parse(b);}
function output(name,data){const b=JSON.stringify(data,null,2)+'\n';writeFileSync(join(here,name),b);manifest.push({name,bytes:Buffer.byteLength(b),sha256:sha(b)});}
const bank=input('p34-runtime/p34-bank.json','cef57e7943510d15d2bfbb59f18761217599f9d5c7b749511a02d1c371e9ae00');
const O=input('p37-runtime/p37-r1-r1-lane-o-frontier.json','107eb90daa714a280bebe39e9453faf380606575c50bde1aa93c7b7b3e9c6cf9');
const A=input('p37-runtime/p37-r1-r1-lane-a.json','2caeeb0c96d518c74747b3fc64fbead4668771bf55607315da21ca985e775603');
const ledger=input('p37-runtime/p37-r1-r1-lane-a-antichains.json','6a58186be1e7cea70036114a1b26c3e63232633b8f8e586fe017525c12d59dd4');
input('p37-runtime/p37-r1-r1-terminal-receipt.json','e401e7565e17d474860e7faae46d7f21e70ed1252057ed90cae2ad36f6b0fc57');
const faceNames=['U','D','L','R','F','B'],moves=faceNames.flatMap(f=>[f,f+"'"]),gamma={U:'U',D:'D',F:'R',R:'B',B:'L',L:'F'},gt=m=>gamma[m[0]]+m.slice(1),inv=m=>m.endsWith("'")?m[0]:m+"'";
const slot=x=>[...x.p,...x.n].join(','),base=solvedState().sort((a,b)=>slot(a).localeCompare(slot(b))),colors=base.map(x=>x.c),ID=Uint8Array.from(base.map((_,i)=>i));
function perm(transform){const s=base.map((x,i)=>({p:[...x.p],n:[...x.n],c:String(i)}));transform(s);s.sort((a,b)=>slot(a).localeCompare(slot(b)));if(s.some((x,i)=>slot(x)!==slot(base[i])))throw Error('COORDINATE_PERM_HOLD');return Uint8Array.from(s.map(x=>+x.c));}
const mp=Object.fromEntries(moves.map(m=>[m,perm(s=>applyMove(s,m))]));
const apply=(s,p)=>Uint8Array.from(p,i=>s[i]),key=s=>Buffer.from(s).toString('base64'),run=(s,w)=>w.reduce((t,m)=>apply(t,mp[m]),s);
const adapter=s=>base.map((x,i)=>({p:x.p,n:x.n,c:colors[s[i]]})),hash=s=>sha(serializeState(adapter(s))),colorKey=s=>Array.from(s,i=>colors[i]).join('');
const G=perm(s=>{for(const x of s){x.p=[x.p[2],x.p[1],-x.p[0]];x.n=[x.n[2],x.n[1],-x.n[0]];}}),g=s=>apply(s,G);
const targets=new Map(bank.authority.starts.map(x=>[x.id,run(ID,x.scramble)]));for(const x of bank.authority.starts)if(hash(targets.get(x.id))!==x.state_sha256)throw Error('START_HASH_HOLD');
const universe=new Map();for(const row of bank.rows){for(const w of [row.word_A,row.word_B]){let s=targets.get(row.start_id);universe.set(key(s),s);for(const m of w.split(' ')){s=apply(s,mp[m]);universe.set(key(s),s);}if(hash(s)!==row.terminal_state_sha256)throw Error('TERMINAL_HASH_HOLD');}}
const states=[...universe.values()],hashes=states.map(hash),byHash=new Map(hashes.map((h,i)=>[h,states[i]])),targs=[...targets.values()],D=O.D_star.coordinates;
if(states.length!==155040||new Set(hashes).size!==155040)throw Error('UNIVERSE_HOLD');
console.log('Universe verified',states.length);
function delta(a,b,color=false){const out=[];for(let i=0;i<54;i++)if(color?colors[a[i]]!==colors[b[i]]:a[i]!==b[i])out.push(i);return out;}
const arrEq=(a,b)=>JSON.stringify(a)===JSON.stringify(b),sorted=a=>[...a].sort((a,b)=>a-b);
function proj(s,ds,color=false){const d=new Set(ds);return Array.from(s,(v,i)=>d.has(i)?'':color?colors[v]:String.fromCharCode(65+v)).join('');}
const weights=new Map();for(const row of bank.rows)weights.set(row.start_state_sha256,(weights.get(row.start_state_sha256)||0)+2);
function stats(ds,color=false){const f=new Map();for(let i=0;i<states.length;i++){const k=proj(states[i],ds,color);if(!f.has(k))f.set(k,[]);f.get(k).push(i);}let pairs=0,max=0;const hist={};for(const v of f.values()){pairs+=v.length*(v.length-1)/2;max=Math.max(max,v.length);hist[v.length]=(hist[v.length]||0)+1;}let coverage=0,targetsAffected=0;for(const q of targs)if(f.get(proj(q,ds,color)).length>1){coverage+=weights.get(hash(q));targetsAffected++;}return {coverage,targetsAffected,pairs,max,hist};}
let comparisons=0,canonicalMinimum=55,canonicalCounterexample=null;const supportMap=new Map(),canonicalSupportMap=new Map();for(const q of targs)for(const x of states){if(key(q)===key(x))continue;comparisons++;const d=delta(q,x),dc=delta(q,x,true);supportMap.set(d.join(','),d);canonicalSupportMap.set(dc.join(','),dc);if(dc.length<canonicalMinimum){canonicalMinimum=dc.length;canonicalCounterexample={target_hash:hash(q),rival_hash:hash(x),canonical_delta:dc,inherited_delta:d,target:adapter(q),rival:adapter(x)};}}
const histogram=m=>{const h={};for(const x of m.values())h[x.length]=(h[x.length]||0)+1;return h;};
const size10=[...supportMap.values()].filter(x=>x.length===10),q=byHash.get(O.D_star.witness.target_hash),x=byHash.get(O.D_star.witness.rival_hash);
const necessity=[];for(const k of D){const d=D.filter(v=>v!==k),st=stats(d),canonical=stats(d,true);necessity.push({coordinate:k,inherited:st,canonical_adapter:canonical,pair_essential:proj(q,d)!==proj(x,d),canonical_pair_essential:proj(q,d,true)!==proj(x,d,true),all_coverage_essential:st.coverage<218368});}
const canonicalHistogram=histogram(canonicalSupportMap),colorMismatch=canonicalSupportMap.size!==supportMap.size||!arrEq(canonicalHistogram,histogram(supportMap));
output('canonical-observation-counterexample.json',{scope:'Audit counterexample only; frozen D is not replaced.',minimum:canonicalMinimum,...canonicalCounterexample});
output('observation-necessity.json',{inputs,comparisons,coordinate_index:base.map((s,i)=>({i,p:s.p,n:s.n})),inherited:{supports:supportMap.size,histogram:histogram(supportMap),minimum:Math.min(...[...supportMap.values()].map(d=>d.length)),size10:size10.length,D,witness:{q:hash(q),x:hash(x),delta:delta(q,x)}},canonical_adapter:{supports:canonicalSupportMap.size,histogram:canonicalHistogram,minimum:Math.min(...Object.keys(canonicalHistogram).map(Number)),witness_delta:delta(q,x,true),D_stats:stats(D,true)},leave_one_out:necessity,semantic_parity:colorMismatch?'HOLD_INTERNAL_STICKER_IDS_DIFFER_FROM_SERIALIZED_COLOR_VALUES':'PASS'});
console.log('Necessity complete; canonical support minimum',Math.min(...Object.keys(canonicalHistogram).map(Number)));
// Signed determinant-one coordinate permutations, checked against every move as permutations.
function permutations(a){if(!a.length)return [[]];return a.flatMap(v=>permutations(a.filter(x=>x!==v)).map(p=>[v,...p]));}
const norms={U:'0,1,0',D:'0,-1,0',L:'-1,0,0',R:'1,0,0',F:'0,0,1',B:'0,0,-1'},normalFaces=Object.fromEntries(Object.entries(norms).map(([f,n])=>[n,f]));
const group=[];for(const axes of permutations([0,1,2])){let inversion=0;for(let i=0;i<3;i++)for(let j=i+1;j<3;j++)if(axes[i]>axes[j])inversion++;for(const sx of [-1,1])for(const sy of [-1,1])for(const sz of [-1,1]){const signs=[sx,sy,sz];if((inversion%2?-1:1)*sx*sy*sz!==1)continue;const rot=v=>axes.map((a,i)=>signs[i]*v[a]);const P=perm(s=>{for(const t of s){t.p=rot(t.p);t.n=rot(t.n);}}),faceMap=Object.fromEntries(faceNames.map(f=>[f,normalFaces[rot(norms[f].split(',').map(Number)).join(',')]]));for(const m of moves){const gm=faceMap[m[0]]+m.slice(1);if(key(apply(apply(ID,mp[m]),P))!==key(apply(apply(ID,P),mp[gm])))throw Error('ROTATION_TRANSITION_HOLD');}const image=ds=>sorted(Array.from(P,(src,dest)=>ds.includes(src)?dest:-1).filter(i=>i>=0));group.push({axes,signs,permutation:[...P],faceMap,D_image:image(D)});}}
if(group.length!==24||new Set(group.map(h=>h.permutation.join(','))).size!==24)throw Error('GROUP_ORDER_HOLD');let closure=0;const groupKeys=new Set(group.map(h=>h.permutation.join(',')));for(const h of group)for(const j of group){if(!groupKeys.has(j.permutation.map(i=>h.permutation[i]).join(',')))throw Error('GROUP_CLOSURE_HOLD');closure++;}
output('coordinate-automorphisms.json',{group_order:24,transition_permutation_checks:24*12,closure_checks:closure,claim_scope:'Transition automorphisms; certified finite bank need not be invariant.',group});
const orbitSets=new Map(group.map(h=>[h.D_image.join(','),h.D_image])),geometry=[];for(const ds of new Map([...size10,...orbitSets.values()].map(d=>[d.join(','),d])).values())geometry.push({coordinates:ds,on_size10_frontier:size10.some(d=>arrEq(d,ds)),on_D_orbit:orbitSets.has(ds.join(',')),is_D:arrEq(ds,D),symmetric_difference:ds.filter(k=>!D.includes(k)).length+D.filter(k=>!ds.includes(k)).length,inherited:stats(ds),canonical_adapter:stats(ds,true)});
output('size10-orbit.json',{all_size10:size10,orbit_size:orbitSets.size,stabilizer:group.filter(h=>arrEq(h.D_image,D)).length,orbit_members_on_frontier:geometry.filter(x=>x.on_D_orbit&&x.on_size10_frontier).length,geometry,uniqueness:{cardinality_unique:size10.length===1,full_coverage_minima:geometry.filter(x=>x.on_size10_frontier&&x.inherited.coverage===218368).length,minimum_collateral_minima:geometry.filter(x=>x.on_size10_frontier&&x.inherited.coverage===218368&&x.inherited.pairs===16).length},authority:'INHERITED_ID_ENCODING_RESULTS_WITH_CANONICAL_COLOR_AUDIT; NOT_A_REDEFINITION_OF_D'});
const bm=new Map(bank.rows.map(r=>[r.item_id,r])),lm=new Map();for(const l of ledger)for(const id of l.rows){if(lm.has(id))throw Error('DUPLICATE_ROW');lm.set(id,l);}if(lm.size!==109184)throw Error('MISSING_ROW');
const reach=(masks,M)=>masks.some(m=>(m&~M)===0),bits=M=>faceNames.filter((_,i)=>M&(1<<i)),gm=M=>bits(M).reduce((a,f)=>a|(1<<faceNames.indexOf(gamma[f])),0),classify=s=>s.neither===218368?'floor':s.both===218368?'ceiling':s.r1only+s.r2only?'informative':'nondegenerate-equal';
const table=new Map(A.selectors.map(s=>[s.M,s]));const edges=[];for(let M=1;M<63;M++)for(let i=0;i<6;i++){const N=M|(1<<i);if(N===M||N===63)continue;const delta=Object.fromEntries(['r1','r2','both','neither','r1only','r2only'].map(f=>[f,table.get(N)[f]-table.get(M)[f]]));edges.push({M,N,added:faceNames[i],delta,classes:[classify(table.get(M)),classify(table.get(N))]});}
let monotonicFailures=0,tableFailures=0,gammaFailures=0;const recalc=new Map(Array.from({length:62},(_,i)=>[i+1,{r1:0,r2:0,both:0,neither:0,r1only:0,r2only:0}]));
for(const l of ledger){for(const e of edges)for(const masks of [l.r1_masks,l.r2_masks])if(reach(masks,e.M)&&!reach(masks,e.N))monotonicFailures++;for(let M=1;M<63;M++){const a=reach(l.r1_masks,M),b=reach(l.r2_masks,M),r=recalc.get(M),w=l.rows.length*2;if(a)r.r1+=w;if(b)r.r2+=w;r[a&&b?'both':!a&&!b?'neither':a?'r1only':'r2only']+=w;if(a!==reach(l.r2_masks,gm(M)))gammaFailures++;}}
for(const [M,r] of recalc)for(const f of Object.keys(r))if(r[f]!==table.get(M)[f])tableFailures++;
output('hasse-edges.json',{nodes:A.selectors,edges,edge_count:edges.length,contextwise_monotonicity_failures:monotonicFailures,table_recovery_failures:tableFailures,context_gamma_transport_failures:gammaFailures,A_neighbors:[12,10,6,15,30,46].map(m=>table.get(m))});
const informative=A.selectors.filter(s=>s.r1only+s.r2only),minimal=informative.filter(s=>!informative.some(t=>t.M!==s.M&&(t.M&s.M)===t.M));
function contextOrder(a,b){return a.budget-b.budget||a.history_length-b.history_length||a.origin_hash.localeCompare(b.origin_hash)||a.row_id.localeCompare(b.row_id)||a.branch.localeCompare(b.branch);}
function divergent(M){const out=[];for(const row of bank.rows){const l=lm.get(row.item_id),a=reach(l.r1_masks,M),b=reach(l.r2_masks,M);if(a===b)continue;for(const branch of ['A','B'])out.push({row_id:row.item_id,branch,budget:row.terminal_to_origin_qtm,history_length:row['word_'+branch].split(' ').length,origin_hash:row.start_state_sha256,side:a?'r1':'r2'});}return out.sort(contextOrder);}
const mini=minimal.map(s=>({...s,gamma:gm(s.M),gamma_informative:informative.some(t=>t.M===gm(s.M)),gamma_minimal:minimal.some(t=>t.M===gm(s.M)),ordered_divergences:divergent(s.M)}));output('informative-antichain.json',{members:mini,A_inclusion_minimal:minimal.some(s=>s.M===14),informative_minimum_cardinality:Math.min(...informative.map(s=>bits(s.M).length)),witness_order_note:'Budget/history then origin hash/row/branch; certified budget equals shortest return, fixing route length. Prior P37 selected witness omitted origin-hash priority.'});
const seen=new Set(),orbits=[];for(let M=1;M<63;M++){if(seen.has(M))continue;const o=[];let m=M;do{o.push({...table.get(m),population_class:classify(table.get(m)),is_minimal:minimal.some(t=>t.M===m)});seen.add(m);m=gm(m);}while(m!==M);orbits.push(o);}output('gamma-orbits.json',{orbits,A_orbit:orbits.find(o=>o.some(s=>s.M===14)),informative_family_closed:informative.every(s=>informative.some(t=>t.M===gm(s.M))),minimal_family_closed:minimal.every(s=>minimal.some(t=>t.M===gm(s.M))),gamma_equivariance_failures:gammaFailures});
// Literal g(c): exact coordinate rotation of target and start and gamma(history), with no color relabeling or substitute origin.
const originHashes=new Set(bank.authority.starts.map(x=>x.state_sha256)),divs=divergent(14),pairing=[];
for(const c of divs){const row=bm.get(c.row_id),q=targets.get(row.start_id),s=run(q,row['word_'+c.branch].split(' ')),qh=hash(g(q));pairing.push({...c,transformed_target:qh,transformed_start:hash(g(s)),transformed_history:row['word_'+c.branch].split(' ').map(gt),status:originHashes.has(qh)?'TARGET_PRESENT_REQUIRES_FULL_MATCH':'UNMATCHED_TRANSFORMED_TARGET_OUTSIDE_CERTIFIED_ORIGIN_SET'});}
output('context-pairing.json',{mapping:'g(start), g(target), gamma(history), same budget and branch; exact bank membership',R1_only:pairing.filter(c=>c.side==='r1').length,R2_only:pairing.filter(c=>c.side==='r2').length,matched:0,unmatched:pairing.length,ambiguous:0,bijection:false,records:pairing,scope:'Equal 512/512 counts do not certify an in-bank g-bijection. Selector covariance is a distinct proven test.'});
const wr=bm.get('P34-001164'),wq=targets.get(wr.start_id),ws=run(wq,wr.word_A.split(' ')),route=['L',"D'",'L',"R'","D'","L'"],gr=route.map(gt),wledger=lm.get(wr.item_id);
output('witness-mechanism.json',{row:wr,route,mask:14,gamma_route:gr,gamma_mask:gm(14),start_r2:hash(g(ws)),target_r2:hash(g(wq)),actual_route_return:hash(run(g(ws),route))===hash(g(wq)),gamma_route_return:hash(run(g(g(ws)),gr))===hash(g(g(wq))),antichains:{r1:wledger.r1_masks,r2:wledger.r2_masks},r1_no_subset_mask:!reach(wledger.r1_masks,14),r2_subset_mask:reach(wledger.r2_masks,14),partner:pairing.find(c=>c.row_id===wr.item_id&&c.branch==='A'),frozen_witness_first_under_origin_hash_order:divs[0],inherited_witness_minimality_matches:divs[0].row_id===wr.item_id});
// Code audit records premises and deficiencies, rather than treating receipt assertions as execution evidence.
const codeO=readFileSync(join(root,'p37-runtime/run-r1.mjs'),'utf8'),codeA=readFileSync(join(root,'p37-runtime/run-r1-r1-lane-a.mjs'),'utf8');
output('factorization-proof.json',{theorem:'Define Y_O(D) as target-fiber ambiguity and Y_A(M) as bounded reachability on fixed exact states. If neither function consumes the other instrument, Y(D,M)=(Y_O(D),Y_A(M)) by definition. Any differing coordinate is already a pure-axis difference; no joint-only difference exists.',runtime:{lane_A_reads_observation_artifacts:/readFileSync[^\n]*(lane-o|frontier)/.test(codeA),lane_A_uses_projection:/projection\(|proj\(/.test(codeA),selectors_depend_only_on_masks:true,common_transition_adapter:true,observation_reads_bank_without_mutation:true,origin_target_normalization_in_A:codeA.includes('s=run(ID,w)'),target_indexed_reverse_cache_present:false,mask_dominance_unpruned_regression_present:false,observation_serialization_parity:!colorMismatch,prior_joint_evaluation:'literal status assignment; no joint runtime ledger'},code_hashes:{O:sha(codeO),A:sha(codeA)},formal_result:'FACTORISATION_THEOREM_VALID_UNDER_STATED_PREMISES',runtime_promotion:'HOLD_CANONICAL_OBSERVATION_SEMANTICS_AND_EXACT_TARGET_REUSE_REQUIRE_RECONCILIATION',structural_joint_null_promoted:false});
const holds=['P37_OBSERVATION_USES_INTERNAL_STICKER_ID_VALUES_NOT_ADAPTER_COLOR_VALUES','P37_FULL_SUPPORT_FRONTIER_NOT_MATERIALIZED_PER_CANDIDATE: only 447? filtered entries; exact count recorded below','P37_FIRST_ACTION_WITNESS_ORDER_OMITS_ORIGIN_HASH_PRIORITY','P37_TARGET_INDEXED_CACHE_AND_UNPRUNED_DOMINANCE_REGRESSION_ABSENT'];
holds[1]='P37_FRONTIER_ONLY_'+O.frontier.length+'_OF_'+supportMap.size+'_SUPPORTS_RECORDED_AND_DOMINANCE_TEST_OMITS_SUBSET_CONDITION';
output('transport-gates.json',{observation:{status:'HOLD',reason:'Inherited ID-encoded necessity differs from canonical adapter coordinate values; no scientific repair authorized.'},action:{status:'HOLD',reason:'Hasse and gamma audits are exact on inherited masks; exact-target normalization proof, missing pruning controls, and prospectively minimal witness must be reconciled before certification.'},combined:{status:'HOLD',reason:'Both mechanism gates and runtime-premise gate must pass.'},abstract_schema:'Finite state set, transitions, exact target predicate, representation automorphism, coordinate-deletion observations, action subsets ordered by inclusion, cost bound, and constructive or exhaustive certificates.',holds,world_contact:'HOLD',successor:'NOT_OPENED'});
output('terminal-receipt.json',{stage:'G3-P38-R1',verdict:'P38_R1_AUDIT_HOLD / INHERITED_SEMANTIC_AND_PROVENANCE_DISCREPANCIES_LOCALIZED / NO_TRANSPORT_PROMOTION / NO_SUCCESSOR_OPENED',input_hashes:inputs,counts:{states:states.length,comparisons,inherited_supports:supportMap.size,canonical_supports:canonicalSupportMap.size,size10:size10.length,rotations:24,Hasse_edges:edges.length,minimal_informative:mini.length,pairing_unmatched:pairing.length},holds,artifacts:manifest,compiler_sha256:sha(readFileSync(fileURLToPath(import.meta.url)))});
writeFileSync(join(here,'sha256-manifest.json'),JSON.stringify(manifest,null,2)+'\n');console.log(JSON.stringify({manifest,holds},null,2));
for(const i of inputs)if(sha(readFileSync(join(root,i.path)))!==i.sha256)throw Error('POSTRUN_INPUT_MUTATION_HOLD '+i.path);
