import fs from 'node:fs';
import crypto from 'node:crypto';
const ROOT=process.env.R114_EXTERNAL_ROOT; if(!ROOT) throw new Error('R114_EXTERNAL_ROOT_REQUIRED');
const ROLE=process.env.R114_EXTERNAL_ROLE||'EXTERNAL';
const freeze=JSON.parse(fs.readFileSync('research/0.10.5-r1.14/G4_EXTERNAL_SCORING_IMPLEMENTATION_FREEZE.json','utf8'));
const refSeal=JSON.parse(fs.readFileSync('research/0.10.5-r1.14/evidence-reference/G4_REFERENCE_BANK_SEAL.json','utf8'));
const refFeatures=JSON.parse(fs.readFileSync('research/0.10.5-r1.14/evidence-ontology/G4_CANONICAL_FEATURE_LEDGER.json','utf8')).rows;
const refLoo=JSON.parse(fs.readFileSync('research/0.10.5-r1.14/evidence-reference/G4_REFERENCE_LOO_BANK.json','utf8')).rows.filter(x=>Number.isFinite(x.attempt_statistic));
const audit=JSON.parse(fs.readFileSync(`${ROOT}/G4_ONTOLOGY_AUDIT.json`,'utf8'));
const rows=JSON.parse(fs.readFileSync(`${ROOT}/G4_ONTOLOGY_ROUTE_ROWS.json`,'utf8')).rows;
const features=JSON.parse(fs.readFileSync(`${ROOT}/G4_CANONICAL_FEATURE_LEDGER.json`,'utf8')).rows;
if(refSeal.seal_sha256!==freeze.reference_seal_sha256) throw new Error('REFERENCE_SEAL_MISMATCH');
const key=r=>`${r.result_id}:${r.attempt_number}`;
function localRef(z){const levels=[['PHASE_CHANNEL_BIN',refFeatures.filter(r=>r.phase===z.phase&&r.channel===z.channel&&r.move_bin===z.move_bin),25],['PHASE_CHANNEL',refFeatures.filter(r=>r.phase===z.phase&&r.channel===z.channel),40],['CHANNEL',refFeatures.filter(r=>r.channel===z.channel),100]];for(const [level,rr,min] of levels)if(rr.length>=min)return {level,rows:rr,n:rr.length};return null;}
function tail(rr,v){const ge=rr.filter(x=>x.observed_amplitude>=v-1e-12).length;return (1+ge)/(rr.length+1);}
let fallback=0;const sf=[];
for(const z of features){const r=localRef(z);if(!r){fallback++;continue;}const p=tail(r.rows,z.observed_amplitude);sf.push({...z,local_level:r.level,local_n:r.n,local_p:p,local_score:-Math.log10(p)});}
const by=new Map();for(const z of sf){const k=key(z);if(!by.has(k))by.set(k,[]);by.get(k).push(z);}const attempts=[];
for(const [k,z] of by){const stat=Math.max(...z.map(x=>x.local_score));const ge=refLoo.filter(x=>x.attempt_statistic>=stat-1e-12).length;const p=(1+ge)/(refLoo.length+1);attempts.push({key:k,reco_id:z[0].reco_id,scored_feature_n:z.length,attempt_statistic:stat,familywise_reference_n:refLoo.length,familywise_p:p});}
const rawN=audit.counts.raw_unique_attempts||0, eligible=audit.counts.ordinary_fb_sb_eligible||0, prefix=audit.counts.prefix_unique||0, canonical=audit.counts.canonical||0;
const stateRate=rawN?audit.counts.state_certified/rawN:null, prefixRate=eligible?prefix/eligible:null, canonEligible=eligible?canonical/eligible:null, canonPrefix=prefix?canonical/prefix:null;
const cmllRate=audit.counts.cmll_opportunities?audit.counts.cmll_consistent/audit.counts.cmll_opportunities:null, lseRate=audit.counts.lse_opportunities?audit.counts.lse_consistent/audit.counts.lse_opportunities:null;
const fallbackRate=features.length?fallback/features.length:0, watchRate=attempts.length?attempts.filter(x=>x.familywise_p<=.05).length/attempts.length:null, primaryRate=attempts.length?attempts.filter(x=>x.familywise_p<=.01).length/attempts.length:null;
const recoOverlap=rows.filter(x=>x.reco_id!=null && refSeal.reference_attempt_keys.includes(String(x.attempt_key))).length;
let checks={};let authority=false;let status='';
if(ROLE==='PREEXISTING_UNSEEN_HOLDOUT'){
 const g=freeze.preexisting_transport_gates;checks={minimum_raw_routes:rawN>=g.minimum_raw_routes,state_certification_rate:stateRate!==null&&stateRate>=g.state_certification_rate_min,prefix_unique_rate_given_eligible:prefixRate!==null&&prefixRate>=g.prefix_unique_rate_given_eligible_min,canonical_rate_given_prefix_unique:canonPrefix!==null&&canonPrefix>=g.canonical_rate_given_prefix_unique_min,null_fallback_rate:fallbackRate<=g.null_fallback_rate_max};
 status=Object.values(checks).every(Boolean)?'PASS_PREEXISTING_UNSEEN_ONTOLOGY_TRANSPORT':'HOLD_PREEXISTING_UNSEEN_ONTOLOGY_TRANSPORT';
}else if(ROLE==='POST_FREEZE_FRESH_VINTAGE'){
 const g=freeze.fresh_authority_gates;checks={minimum_raw_routes:rawN>=g.minimum_raw_routes,state_certification_rate:stateRate!==null&&stateRate>=g.state_certification_rate_min,prefix_unique_rate_given_eligible:prefixRate!==null&&prefixRate>=g.prefix_unique_rate_given_eligible_min,canonical_fb_preserving_rate_given_eligible:canonEligible!==null&&canonEligible>=g.canonical_fb_preserving_rate_given_eligible_min,cmll_consistency_rate:cmllRate!==null&&cmllRate>=g.cmll_consistency_rate_min,lse_consistency_rate:lseRate!==null&&lseRate>=g.lse_consistency_rate_min,local_reference_fallback_rate:fallbackRate<=g.local_reference_fallback_rate_max,familywise_watch_rate:watchRate!==null&&watchRate<=g.familywise_watch_rate_0_05_max,familywise_primary_rate:primaryRate!==null&&primaryRate<=g.familywise_primary_rate_0_01_max,reference_bank_contamination:recoOverlap===g.reference_bank_contamination};authority=Object.values(checks).every(Boolean);status=authority?'PASS_FRESH_G4_AUTHORITY_RELEASE_ELIGIBLE':'HOLD_FRESH_G4_AUTHORITY';
}else throw new Error(`UNKNOWN_ROLE:${ROLE}`);
const out={schema_version:'CR0105R114-G4-EXTERNAL-SCORE-1',generation:'ROUX-MEASUREMENT-G4',role:ROLE,status,counts:{raw_routes:rawN,state_certified:audit.counts.state_certified,eligible_routes:eligible,prefix_unique:prefix,canonical,block_disruptive:audit.counts.block_disruptive,fb_preserved_no_completion:audit.counts.fb_preserved_no_completion,canonical_features:features.length,scored_features:sf.length,scored_attempts:attempts.length,reference_attempts:refLoo.length},rates:{state_certification:stateRate,prefix_unique_given_eligible:prefixRate,canonical_given_eligible:canonEligible,canonical_given_prefix_unique:canonPrefix,cmll_consistency:cmllRate,lse_consistency:lseRate,local_reference_fallback:fallbackRate,familywise_watch_0_05:watchRate,familywise_primary_0_01:primaryRate},checks,reference:{seal_sha256:refSeal.seal_sha256,membership_sha256:refSeal.reference_membership_sha256,contamination_n:recoOverlap,external_routes_entered_reference:false},future_roux_scoring_authority:authority,semantic_guard:'Ontology classes are observable reconstruction-state categories, not solver intent/error labels.',human_observations:0};out.semantic_sha256=crypto.createHash('sha256').update(JSON.stringify(out)).digest('hex');
fs.writeFileSync(`${ROOT}/G4_EXTERNAL_SCORE_AUDIT.json`,JSON.stringify(out,null,2)+'\n');fs.writeFileSync(`${ROOT}/G4_EXTERNAL_SCORED_FEATURES.json`,JSON.stringify({schema_version:'CR0105R114-G4-EXTERNAL-SCORED-FEATURES-1',role:ROLE,rows:sf,human_observations:0},null,2)+'\n');fs.writeFileSync(`${ROOT}/G4_EXTERNAL_ATTEMPT_SCORES.json`,JSON.stringify({schema_version:'CR0105R114-G4-EXTERNAL-ATTEMPT-SCORES-1',role:ROLE,rows:attempts,human_observations:0},null,2)+'\n');console.log(JSON.stringify(out,null,2));
