import fs from 'node:fs';
import crypto from 'node:crypto';
import { buildR19Core, parseAnnotated, sha } from '../0.10.5-r1.9/r19_quotient_core.mjs';

const ROOT=process.env.R114_ROOT||'/tmp/r114';fs.mkdirSync(ROOT,{recursive:true});
const fixture=JSON.parse(fs.readFileSync('research/0.10.5-r1.13/evidence-development/ROTATION_GAUGE_TRANSPORT_FIXTURE.json','utf8'));
const impl=JSON.parse(fs.readFileSync('research/0.10.5-r1.14/G4_IMPLEMENTATION_FREEZE.json','utf8'));
if(fixture.status!=='PASS_ROTATION_GAUGE_ALGEBRA') throw new Error('R114_PARENT_ROTATION_FIXTURE_NOT_PASS');
if(impl.status!=='FROZEN_AFTER_BASELINE_BEFORE_G4_ROUTE_RECLASSIFICATION') throw new Error('R114_IMPLEMENTATION_NOT_FROZEN');
const T=fixture.transport_table;
const core=await buildR19Core();
const {defaultPattern,EDGE,CORNER,ORIENT,faces,faceSupport,opposite}=core;
const attemptKey=r=>`${r.result_id}:${r.attempt_number}`;
const foldOf=k=>parseInt(crypto.createHash('sha256').update(`R114FOLD:${k}`).digest('hex').slice(0,8),16)%5;
const intersect=(a,b)=>{const s=new Set(b);return a.filter(x=>s.has(x));};
const moveBin=n=>n<=4?'1-4':n<=8?'5-8':n<=12?'9-12':'13+';
function blockMask(bottom,side){const top=opposite[bottom];return {bottom,side,top,edges:faceSupport[side].edges.filter(i=>!faceSupport[top].edges.includes(i)),corners:intersect(faceSupport[bottom].corners,faceSupport[side].corners)};}
const frames=[];for(const bottom of faces)for(const side of faces){if(side===bottom||side===opposite[bottom])continue;frames.push({key:`${bottom}|${side}`,bottom,top:opposite[bottom],first_side:side,second_side:opposite[side],first:blockMask(bottom,side),second:blockMask(bottom,opposite[side])});}
const allCorners=defaultPattern.patternData[CORNER].pieces.map((_,i)=>i),allEdges=defaultPattern.patternData[EDGE].pieces.map((_,i)=>i);
function coordSolved(p,o,i){const a=p.patternData[o],b=defaultPattern.patternData[o];return a.pieces[i]===b.pieces[i]&&a.orientation[i]===b.orientation[i];}
function blockSolved(p,m){return m.edges.every(i=>coordSolved(p,EDGE,i))&&m.corners.every(i=>coordSolved(p,CORNER,i));}
function masksForBlock(b){return [{orbit:EDGE,positions:b.edges},{orbit:CORNER,positions:b.corners}];}
function twoBlockMasks(f){return [{orbit:EDGE,positions:[...f.first.edges,...f.second.edges]},{orbit:CORNER,positions:[...f.first.corners,...f.second.corners]}];}
function lseEdges(f){const s=new Set([...f.first.edges,...f.second.edges]);return allEdges.filter(i=>!s.has(i));}
function dist(p,target,masks){let bad=0,total=0;for(const m of masks)for(const i of m.positions){total+=2;const a=p.patternData[m.orbit],b=target.patternData[m.orbit];if(a.pieces[i]!==b.pieces[i])bad++;if(a.orientation[i]!==b.orientation[i])bad++;}return total?bad/total:null;}
function minDist(p,targets,masks){return Math.min(...targets.map(t=>dist(p,t,masks)));}
function objectiveBacktrack(ds){let frontier=Infinity,amp=0;for(const d of ds){frontier=Math.min(frontier,d);amp=Math.max(amp,d-frontier);}return amp;}
function anchorBreak(states,masks){if(!states.length)return null;const vals=states.map(p=>dist(p,defaultPattern,masks)),a0=vals[0];return Math.max(...vals.map(x=>Math.max(0,x-a0)));}
function aufVariants(p,face){const out=[p];let q=p;for(let i=1;i<4;i++){q=q.applyMove(face);out.push(q);}return out;}
function cornersSolvedAUF(p,face){let q=p;for(let i=0;i<4;i++){if(allCorners.every(j=>coordSolved(q,CORNER,j)))return true;q=q.applyMove(face);}return false;}
function ordinaryFb(c){const s=String(c||'');return /\bfb\b/i.test(s)&&!/\bpseudo\s+fb\b/i.test(s)&&!/\bfbdr\b/i.test(s);}
function span(lines,phase,after=-1){let first=-1;for(let i=0;i<lines.length;i++)if(lines[i].phase===phase&&lines[i].end>x.start&&lines[i].start>=after){first=i;break;}if(first<0)return null;let last=first;for(let i=first+1;i<lines.length;i++){if(lines[i].phase!==phase||lines[i].end<=lines[i].start)break;last=i;}return {start:lines[first].start,end:lines[last].end,lines:lines.slice(first,last+1)};}
function firstLineAfter(lines,phase,after){return lines.find(x=>x.phase===phase&&x.end>x.start&&x.start>=after)||null;}
function normRot(m){const s=String(m),a=s[0];if(!'xyz'.includes(a))return null;if(s.includes('2'))return `${a}2`;return s.includes("'")?`${a}'`:a;}
const inverse={};for(const rot of fixture.rotation_tokens){inverse[rot]={};for(let g=0;g<24;g++){const h=T[g][rot];if(h===null||h===undefined)throw new Error('TRANSPORT_TABLE_NULL');if(inverse[rot][h]!==undefined)throw new Error('TRANSPORT_NOT_PERMUTATION');inverse[rot][h]=g;}}
function buildGaugePath(tokens,fbEnd,g0,nStates){const g=Array(nStates).fill(null);g[fbEnd]=g0;let x=g0;for(let j=fbEnd-1;j>=0;j--){const r=normRot(tokens[j].move);if(r)x=inverse[r][x];g[j]=x;}x=g0;for(let j=fbEnd;j<tokens.length;j++){const r=normRot(tokens[j].move);if(r)x=T[x][r];g[j+1]=x;}return g;}
function transformed(states,gauges,i){return states[i].applyTransformation(ORIENT[gauges[i]]);}
function loadRecords(){const c=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-census/SEALED_ROUTE_CENSUS.json','utf8'));const a=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-acquisition/ROUX_EXPANSION_ROUTE_MANIFEST.json','utf8'));const z=[];for(const r of c.all_clean_attempts)z.push({...r,source:'SEALED_R111'});for(const r of a.records)if(r.route_source_status==='RAW_ALG_CUBING_LINK')z.push({...r,source:'R112_EXPANSION'});const m=new Map();for(const r of z)m.set(attemptKey(r),r);return [...m.values()].sort((a,b)=>attemptKey(a).localeCompare(attemptKey(b)));}

const records=loadRecords(),rows=[],features=[];
const C={raw_unique_attempts:records.length,parse_ok:0,state_certified:0,ordinary_fb_sb_eligible:0,prefix_unique:0,canonical:0,block_disruptive:0,fb_preserved_no_completion:0,pseudo_fb_or_fbdr:0,syntax_or_state_invalid:0,ontology_unscorable:0,cmll_opportunities:0,cmll_consistent:0,lse_opportunities:0,lse_consistent:0};
const source={},frameCounts={},errors=[];
for(const r of records){const rec={attempt_key:attemptKey(r),result_id:r.result_id,attempt_number:r.attempt_number,reco_id:r.reco_id??null,source:r.source,g4_class:null};source[r.source]??={n:0,eligible:0,canonical:0,block_disruptive:0,preserved_no_completion:0};source[r.source].n++;
 try{
  const parsed=parseAnnotated(r.raw_alg,'Roux');C.parse_ok++;const moves=parsed.tokens.map(x=>x.move);let s=defaultPattern.applyAlg(r.raw_setup),states=[s];for(const m of moves){s=s.applyMove(m);states.push(s);}if(!s.experimentalIsSolved({ignorePuzzleOrientation:true,ignoreCenterOrientation:true})){C.syntax_or_state_invalid++;rec.g4_class='SYNTAX_OR_STATE_INVALID';rec.reason='FINAL_NOT_SOLVED';rows.push(rec);continue;}C.state_certified++;
  const fbLines=parsed.lines.filter(x=>x.phase==='ROUX_FB'&&x.end>x.start);if(fbLines.length!==1){C.ontology_unscorable++;rec.g4_class='ONTOLOGY_UNSCORABLE';rec.reason='FB_LINE_COUNT_NOT_ONE';rows.push(rec);continue;}const fb=fbLines[0];rec.fb_comment=fb.comment;if(/\bpseudo\s+fb\b/i.test(fb.comment)||/\bfbdr\b/i.test(fb.comment)){C.pseudo_fb_or_fbdr++;rec.g4_class='PSEUDO_FB_OR_FBDR_FORK';rows.push(rec);continue;}if(!ordinaryFb(fb.comment)){C.ontology_unscorable++;rec.g4_class='ONTOLOGY_UNSCORABLE';rec.reason='FB_NONORDINARY';rows.push(rec);continue;}const sb=span(parsed.lines,'ROUX_SB',fb.end);if(!sb){C.ontology_unscorable++;rec.g4_class='ONTOLOGY_UNSCORABLE';rec.reason='NO_SB_SPAN';rows.push(rec);continue;}C.ordinary_fb_sb_eligible++;source[r.source].eligible++;
  const prefix=[];for(let gi=0;gi<24;gi++){const q=states[fb.end].applyTransformation(ORIENT[gi]);for(const f of frames)if(blockSolved(q,f.first)&&!blockSolved(q,f.second))prefix.push({gauge:gi,frame:f});}rec.prefix_candidate_n=prefix.length;if(prefix.length!==1){C.ontology_unscorable++;rec.g4_class='ONTOLOGY_UNSCORABLE';rec.reason=prefix.length?'PREFIX_MULTI':'PREFIX_NONE';rows.push(rec);continue;}C.prefix_unique++;const init=prefix[0],frame=init.frame;rec.initial_gauge=init.gauge;rec.frame_key=frame.key;frameCounts[frame.key]=(frameCounts[frame.key]||0)+1;const gauges=buildGaugePath(parsed.tokens,fb.end,init.gauge,states.length);const qAt=i=>transformed(states,gauges,i);
  let completion=null,breakIndex=null;for(let i=sb.start;i<=sb.end;i++){const q=qAt(i);if(!blockSolved(q,frame.first)&&breakIndex===null)breakIndex=i;if(blockSolved(q,frame.first)&&blockSolved(q,frame.second)){completion=i;break;}}
  rec.first_block_break_index=breakIndex;rec.sb_completion_index=completion;rec.sb_span={start:sb.start,end:sb.end,line_count:sb.lines.length};
  if(breakIndex!==null && (completion===null||breakIndex<completion)){C.block_disruptive++;source[r.source].block_disruptive++;rec.g4_class='BLOCK_DISRUPTIVE_RESIDUAL';rows.push(rec);continue;}
  if(completion===null){C.fb_preserved_no_completion++;source[r.source].preserved_no_completion++;rec.g4_class='FB_PRESERVED_NO_COMPLETION_RESIDUAL';rows.push(rec);continue;}
  C.canonical++;source[r.source].canonical++;rec.g4_class='CANONICAL_FB_PRESERVING';
  const rots=[];for(let j=fb.end;j<completion;j++){const rr=normRot(parsed.tokens[j].move);if(rr)rots.push({token_index:j,move:parsed.tokens[j].move,normalized:rr});}rec.rotation_present=rots.length>0;rec.rotation_tokens=rots;
  function addFeature(phase,channel,start,end,amp){features.push({generation:'ROUX-MEASUREMENT-G4',ontology_class:'CANONICAL_FB_PRESERVING',result_id:r.result_id,attempt_number:r.attempt_number,reco_id:r.reco_id??null,source:r.source,method:'Roux',phase,channel,move_count:end-start,move_bin:moveBin(end-start),observed_amplitude:amp,frame_key:frame.key,initial_gauge:init.gauge,rotation_present:rots.length>0,fold:foldOf(attemptKey(r))});}
  const fbStates=[];for(let i=fb.start;i<=fb.end;i++)fbStates.push(qAt(i));addFeature('FB','objective',fb.start,fb.end,objectiveBacktrack(fbStates.map(p=>dist(p,defaultPattern,masksForBlock(frame.first)))));
  const sbStates=[];for(let i=sb.start;i<=completion;i++)sbStates.push(qAt(i));addFeature('SB','objective',sb.start,completion,objectiveBacktrack(sbStates.map(p=>dist(p,defaultPattern,masksForBlock(frame.second)))));addFeature('SB','anchor',sb.start,completion,anchorBreak(sbStates,masksForBlock(frame.first)));
  const cmll=firstLineAfter(parsed.lines,'ROUX_CMLL',completion);if(cmll){C.cmll_opportunities++;const ep=qAt(cmll.end),consistent=blockSolved(ep,frame.first)&&blockSolved(ep,frame.second)&&cornersSolvedAUF(ep,frame.top);rec.cmll_consistent=consistent;if(consistent)C.cmll_consistent++;const targets=aufVariants(ep,frame.top),ms=[{orbit:CORNER,positions:allCorners}],ps=[];for(let i=cmll.start;i<=cmll.end;i++)ps.push(qAt(i));addFeature('CMLL','objective',cmll.start,cmll.end,objectiveBacktrack(ps.map(p=>minDist(p,targets,ms))));addFeature('CMLL','anchor',cmll.start,cmll.end,anchorBreak(ps,twoBlockMasks(frame)));}
  const lse=span(parsed.lines,'ROUX_LSE',completion);if(lse){C.lse_opportunities++;const ep=qAt(lse.end),consistent=blockSolved(ep,frame.first)&&blockSolved(ep,frame.second);rec.lse_consistent=consistent;if(consistent)C.lse_consistent++;const ms=[{orbit:EDGE,positions:lseEdges(frame)}],ps=[];for(let i=lse.start;i<=lse.end;i++)ps.push(qAt(i));addFeature('LSE','objective',lse.start,lse.end,objectiveBacktrack(ps.map(p=>dist(p,ep,ms))));addFeature('LSE','anchor',lse.start,lse.end,anchorBreak(ps,twoBlockMasks(frame)));}
  rows.push(rec);
 }catch(e){C.syntax_or_state_invalid++;rec.g4_class='SYNTAX_OR_STATE_INVALID';rec.reason='PARSE_OR_REPLAY_ERROR';rec.error=String(e?.message||e).slice(0,400);errors.push({attempt_key:rec.attempt_key,error:rec.error});rows.push(rec);}}

// Compare only after independent G4 classification is complete.
let confusion={};try{const old=JSON.parse(fs.readFileSync('research/0.10.5-r1.13/evidence-development/ROUX_G3_ROUTE_ROWS.json','utf8')).rows;const om=new Map(old.map(x=>[x.attempt_key,x.status]));for(const r of rows){const o=om.get(r.attempt_key)||'MISSING';const k=`${o} -> ${r.g4_class}`;confusion[k]=(confusion[k]||0)+1;}}catch{}
const rate=(n,d)=>d?n/d:0,objectiveN=features.filter(x=>x.channel==='objective').length;
const assigned=C.canonical+C.block_disruptive+C.fb_preserved_no_completion;
const rates={state_certification_rate:rate(C.state_certified,C.raw_unique_attempts),prefix_unique_rate_given_eligible:rate(C.prefix_unique,C.ordinary_fb_sb_eligible),ontology_assignment_rate_given_prefix_unique:rate(assigned,C.prefix_unique),canonical_rate_given_prefix_unique:rate(C.canonical,C.prefix_unique),cmll_consistency_rate_canonical:rate(C.cmll_consistent,C.cmll_opportunities),lse_consistency_rate_canonical:rate(C.lse_consistent,C.lse_opportunities)};
const g=impl.development_ontology_gates;
const checks={state_certified_n_min:C.state_certified>=g.state_certified_n_min,ordinary_fb_sb_eligible_n_min:C.ordinary_fb_sb_eligible>=g.ordinary_fb_sb_eligible_n_min,prefix_unique_rate_given_eligible_min:rates.prefix_unique_rate_given_eligible>=g.prefix_unique_rate_given_eligible_min,ontology_assignment_rate_given_prefix_unique_min:rates.ontology_assignment_rate_given_prefix_unique>=g.ontology_assignment_rate_given_prefix_unique_min,canonical_reference_attempts_min:C.canonical>=g.canonical_reference_attempts_min,cmll_consistency_rate_canonical_min:rates.cmll_consistency_rate_canonical>=g.cmll_consistency_rate_canonical_min,lse_consistency_rate_canonical_min:rates.lse_consistency_rate_canonical>=g.lse_consistency_rate_canonical_min,total_canonical_features_min:features.length>=g.total_canonical_features_min,objective_canonical_features_min:objectiveN>=g.objective_canonical_features_min,all_features_g4_canonical:features.every(x=>x.generation==='ROUX-MEASUREMENT-G4'&&x.ontology_class==='CANONICAL_FB_PRESERVING')};
const pass=Object.values(checks).every(Boolean);
const audit={schema_version:'CR0105R114-G4-CANONICAL-ROUX-ONTOLOGY-1',generation:'ROUX-MEASUREMENT-G4',status:pass?'PASS_G4_DEVELOPMENT_ONTOLOGY':'HOLD_G4_DEVELOPMENT_ONTOLOGY',baseline_id_set_sha256:impl.baseline_id_set_sha256,counts:C,rates,checks,source_counts:source,frame_counts:frameCounts,feature_counts:{total:features.length,objective:objectiveN,anchor:features.length-objectiveN,canonical_attempts:new Set(features.map(attemptKey)).size,phase:Object.fromEntries(['FB','SB','CMLL','LSE'].map(p=>[p,features.filter(x=>x.phase===p).length]))},confusion_vs_g3_diagnostic_only:confusion,errors,development_role:'CALIBRATION_AND_ONTOLOGY_STRESS_TEST_ONLY',r113_labels_used_for_classification:false,r113_features_or_scores_reused:false,post_result_gate_change:false,human_observations:0};audit.semantic_sha256=sha(audit);
fs.writeFileSync(`${ROOT}/G4_ONTOLOGY_AUDIT.json`,JSON.stringify(audit,null,2)+'\n');fs.writeFileSync(`${ROOT}/G4_ONTOLOGY_ROUTE_ROWS.json`,JSON.stringify({schema_version:'CR0105R114-G4-ONTOLOGY-ROWS-1',rows,human_observations:0},null,2)+'\n');fs.writeFileSync(`${ROOT}/G4_CANONICAL_FEATURE_LEDGER.json`,JSON.stringify({schema_version:'CR0105R114-G4-CANONICAL-FEATURES-1',generation:'ROUX-MEASUREMENT-G4',rows:features,human_observations:0},null,2)+'\n');console.log(JSON.stringify({status:audit.status,counts:C,rates,feature_counts:audit.feature_counts,checks,semantic_sha256:audit.semantic_sha256},null,2));
