import {readFileSync,writeFileSync,createWriteStream,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createGzip} from 'node:zlib';
import {once} from 'node:events';
import {solvedState,applyMove,applySequence,serializeState} from '../state-adapter.js';

const here=dirname(fileURLToPath(import.meta.url)),root=join(here,'..');mkdirSync(here,{recursive:true});
const sha=b=>createHash('sha256').update(b).digest('hex'),jread=p=>JSON.parse(readFileSync(p));
const expected={
 bank:'cef57e7943510d15d2bfbb59f18761217599f9d5c7b749511a02d1c371e9ae00',
 laneA:'2caeeb0c96d518c74747b3fc64fbead4668771bf55607315da21ca985e775603',
 ledger:'6a58186be1e7cea70036114a1b26c3e63232633b8f8e586fe017525c12d59dd4',
 p38:'50df8728311b62b7d4a0dfa693ca223f68068d099ae49ad18f9e0949f4188064'
};
const paths={bank:join(root,'p34-runtime/p34-bank.json'),laneA:join(root,'p37-runtime/p37-r1-r1-lane-a.json'),ledger:join(root,'p37-runtime/p37-r1-r1-lane-a-antichains.json'),p38:join(root,'p38-runtime/terminal-receipt.json')};
const inputHashes={};for(const [k,p] of Object.entries(paths)){const b=readFileSync(p);inputHashes[k]={path:p.slice(root.length+1).replaceAll('\\','/'),bytes:b.length,sha256:sha(b)};if(inputHashes[k].sha256!==expected[k])throw Error('INPUT_HASH_HOLD:'+k);}
const bank=jread(paths.bank),laneA=jread(paths.laneA),ledger=jread(paths.ledger),p38=jread(paths.p38);if(!p38.verdict.includes('AUDIT_HOLD'))throw Error('P38_AUTHORITY_HOLD');

const faceNames=['U','D','L','R','F','B'],moves=faceNames.flatMap(f=>[f,f+"'"]),fbit=Object.fromEntries(faceNames.map((f,i)=>[f,1<<i])),gamma={U:'U',D:'D',F:'R',R:'B',B:'L',L:'F'},gt=m=>gamma[m[0]]+m.slice(1),inv=m=>m.endsWith("'")?m[0]:m+"'";
const slot=x=>[...x.p,...x.n].join(','),base=solvedState().sort((a,b)=>slot(a).localeCompare(slot(b))),colors=base.map(x=>x.c),ID=Uint8Array.from(base.map((_,i)=>i));
function perm(transform){const s=base.map((x,i)=>({p:[...x.p],n:[...x.n],c:String(i)}));transform(s);s.sort((a,b)=>slot(a).localeCompare(slot(b)));if(s.some((x,i)=>slot(x)!==slot(base[i])))throw Error('PERM_HOLD');return Uint8Array.from(s.map(x=>+x.c));}
const mp=Object.fromEntries(moves.map(m=>[m,perm(s=>applyMove(s,m))]));
const apply=(s,p)=>Uint8Array.from(p,i=>s[i]),run=(s,w)=>w.reduce((t,m)=>apply(t,mp[m]),s),key=s=>Buffer.from(s).toString('base64');
const adapter=s=>base.map((x,i)=>({p:x.p,n:x.n,c:colors[s[i]]})),stateHash=s=>sha(serializeState(adapter(s))),color=s=>Array.from(s,i=>colors[i]).join('');
const G=perm(s=>{for(const x of s){x.p=[x.p[2],x.p[1],-x.p[0]];x.n=[x.n[2],x.n[1],-x.n[0]];}}),g=s=>apply(s,G),gk=(s,k)=>{for(let i=0;i<k;i++)s=g(s);return s;};
const gm=(M,k=1)=>{for(let z=0;z<k;z++)M=faceNames.reduce((a,f,i)=>M&(1<<i)?a|(1<<faceNames.indexOf(gamma[f])):a,0);return M;};
const starts=new Map(bank.authority.starts.map(x=>[x.id,run(ID,x.scramble)]));for(const x of bank.authority.starts)if(stateHash(starts.get(x.id))!==x.state_sha256)throw Error('START_HASH_HOLD');
const universe=new Map(),prepared=[];for(const row of bank.rows){const q=starts.get(row.start_id);for(const branch of ['A','B']){const history=row['word_'+branch].split(' ');let s=q;universe.set(key(s),s);for(const m of history){s=apply(s,mp[m]);universe.set(key(s),s);}if(stateHash(s)!==row.terminal_state_sha256)throw Error('TERMINAL_HASH_HOLD:'+row.item_id+branch);prepared.push({row,branch,history,q,s});}}
const states=[...universe.values()];if(states.length!==155040)throw Error('UNIVERSE_HOLD:'+states.length);const hashes=states.map(stateHash),byHash=new Map(hashes.map((h,i)=>[h,states[i]]));
const targetList=[...starts.values()],targetIndex=new Map(targetList.map((s,i)=>[key(s),i])),weights=new Map();for(const row of bank.rows)weights.set(row.start_state_sha256,(weights.get(row.start_state_sha256)||0)+2);
console.log('authority verified; reconstructing canonical color frontier');

function dmask(a,b,useColor=true){let m=0n;for(let i=0;i<54;i++)if(useColor?colors[a[i]]!==colors[b[i]]:a[i]!==b[i])m|=1n<<BigInt(i);return m;}
const pop=m=>{let n=0;while(m){m&=m-1n;n++;}return n;},coords=m=>{const a=[];for(let i=0;i<54;i++)if(m&(1n<<BigInt(i)))a.push(i);return a;},hex=m=>m.toString(16).padStart(14,'0');
const supports=new Map(),hist={};let comparisons=0,coarseningViolations=0;
for(let qi=0;qi<targetList.length;qi++){const q=targetList[qi];for(const x of states){if(key(q)===key(x))continue;const cm=dmask(q,x,true),im=dmask(q,x,false);if(cm&~im)coarseningViolations++;const h=hex(cm);let r=supports.get(h);if(!r){r={mask:cm,targetBits:0,pairs:0};supports.set(h,r);}r.targetBits|=1<<qi;r.pairs++;comparisons++;}}
for(const r of supports.values()){const n=pop(r.mask);hist[n]=(hist[n]||0)+1;}const supportCount=supports.size,min=Math.min(...Object.keys(hist).map(Number)),minimum=[...supports.values()].filter(r=>pop(r.mask)===min);
async function writeGzip(name,header,records){const out=createWriteStream(join(here,name)),gz=createGzip({level:9,mtime:0});gz.pipe(out);gz.write(header+'\n');for(const line of records){if(!gz.write(line+'\n'))await once(gz,'drain');}gz.end();await once(out,'close');}
await writeGzip('canonical-color-support-frontier.csv.gz','support_hex,size,target_bits,target_count,target_rival_pairs',(function*(){for(const [h,r] of supports)yield `${h},${pop(r.mask)},${r.targetBits>>>0},${pop(BigInt(r.targetBits>>>0))},${r.pairs}`;})());
function projection(s,m){let z='';for(let i=0;i<54;i++)if(!(m&(1n<<BigInt(i))))z+=colors[s[i]];return z;}
function induced(m){const groups=new Map();for(let i=0;i<states.length;i++){const p=projection(states[i],m);let a=groups.get(p);if(!a){a=[];groups.set(p,a);}a.push(i);}let pairs=0,maxFiber=0,aliasedFibers=0;const fiberHistogram={};for(const a of groups.values()){fiberHistogram[a.length]=(fiberHistogram[a.length]||0)+1;maxFiber=Math.max(maxFiber,a.length);if(a.length>1){aliasedFibers++;pairs+=a.length*(a.length-1)/2;}}let coverage=0,targetsAffected=0;for(const q of targetList){if(groups.get(projection(q,m)).length>1){coverage+=weights.get(stateHash(q));targetsAffected++;}}return {pairs,max_fiber:maxFiber,aliased_fibers:aliasedFibers,fiber_histogram:fiberHistogram,coverage,targets_affected:targetsAffected};}
const evaluated=minimum.map(r=>({support_hex:hex(r.mask),coordinates:coords(r.mask),target_bits:r.targetBits>>>0,target_rival_pairs:r.pairs,...induced(r.mask)}));evaluated.sort((a,b)=>a.coordinates.length-b.coordinates.length||b.coverage-a.coverage||a.pairs-b.pairs||a.max_fiber-b.max_fiber||a.coordinates.join(',').localeCompare(b.coordinates.join(','),undefined,{numeric:true}));const D=evaluated[0],Dm=BigInt('0x'+D.support_hex);
function pairWitness(m){const candidates=[];for(const q of targetList){const qi=targetIndex.get(key(q));for(let i=0;i<states.length;i++){const x=states[i];if(key(q)===key(x)||dmask(q,x,true)!==m)continue;candidates.push({target_index:qi,target_hash:stateHash(q),rival_hash:hashes[i],origin_hash:stateHash(q)});}}candidates.sort((a,b)=>a.target_hash.localeCompare(b.target_hash)||a.rival_hash.localeCompare(b.rival_hash));return candidates[0];}
const observationWitness=pairWitness(Dm),leaveOne=coords(Dm).map(k=>{const m=Dm&~(1n<<BigInt(k));return {coordinate:k,...induced(m),witness_pair_separated:projection(byHash.get(observationWitness.target_hash),m)!==projection(byHash.get(observationWitness.rival_hash),m)};});
const rotations=jread(join(root,'p38-runtime/coordinate-automorphisms.json')).group,orbit=new Map();for(const r of rotations){const im=[];for(let dest=0;dest<54;dest++)if(Dm&(1n<<BigInt(r.permutation[dest])))im.push(dest);const m=im.reduce((a,k)=>a|(1n<<BigInt(k)),0n);orbit.set(hex(m),{coordinates:im,on_frontier:supports.has(hex(m)),minimum_color_support:minimum.some(x=>x.mask===m)});}
const oldD=jread(join(root,'p37-runtime/p37-r1-r1-lane-o-frontier.json')).D_star.coordinates;
const observation={schema:'CUBE-REV-G3-P38-R1-R1-CANONICAL-COLOR-v1',authority:'POST_AUDIT_SEMANTIC_RECONSTITUTION / RULE_FROZEN_BEFORE_REEXECUTION',canonical_semantics:'adapter-emitted colors at 54 canonical positions',comparisons,states:states.length,targets:targetList.length,unique_supports:supports.size,histogram:hist,minimum_cardinality:min,minimum_candidates:evaluated,selected:D,witness:observationWitness,leave_one_out:leaveOne,semantic_coarsening:{theorem:'chi=p^K o psi implies Delta_chi subseteq Delta_psi coordinatewise',exhaustive_violations:coarseningViolations},rotation:{group_order:rotations.length,orbit_size:orbit.size,stabilizer:rotations.length/orbit.size,members:[...orbit.values()]},historical_comparison:{D_ID:oldD,D_color:D.coordinates,intersection:oldD.filter(x=>D.coordinates.includes(x)),ID_minimum:10,color_minimum:min,preserved:true},frontier_file:'canonical-color-support-frontier.csv.gz'};
writeFileSync(join(here,'canonical-color-observation-receipt.json'),JSON.stringify(observation,null,2)+'\n');
console.log('color frontier complete',supports.size,'minimum',min,'selected',D.coordinates);
supports.clear();

// Exact Y+ orbit closure. Context tuple includes row/branch, transformed raw states/history and inherited budget.
const lmap=new Map();for(const l of ledger)for(const id of l.rows){if(lmap.has(id))throw Error('LEDGER_DUP');lmap.set(id,l);}const orbitRecords=[],tupleMap=new Map();
for(const c of prepared){for(let exponent=0;exponent<4;exponent++){const start=gk(c.s,exponent),target=gk(c.q,exponent),history=c.history.map(m=>{for(let i=0;i<exponent;i++)m=gt(m);return m;}),record={source_context_id:`${c.row.item_id}/${c.branch}`,row_id:c.row.item_id,branch:c.branch,orbit_exponent:exponent,start_hash:stateHash(start),target_hash:stateHash(target),history:history.join(' '),budget:c.row.terminal_to_origin_qtm,selector_coordinates:faceNames.filter((_,i)=>gm(14,exponent)&(1<<i)),original_domain_membership:exponent===0,provenance:{bank_row:c.row.item_id,source_branch:c.branch,transform:`g^${exponent}`}};const tk=[record.start_hash,record.target_hash,record.history,record.budget].join('|');if(!tupleMap.has(tk)){tupleMap.set(tk,record);orbitRecords.push(record);}else{const prior=tupleMap.get(tk);(prior.duplicate_sources??=[]).push(record.source_context_id);}}}
await writeGzip('yplus-orbit-closed-contexts.jsonl.gz','',(function*(){for(const r of orbitRecords)yield JSON.stringify(r);})());
const reach=(masks,M)=>masks.some(m=>(m&~M)===0),cycles=[],directional=[];let fixed=0,short=0;
for(const c of prepared){const l=lmap.get(c.row.item_id),baseMasks=l.r1_masks,ys=[];for(let k=0;k<4;k++)ys.push(reach(baseMasks,gm(14,4-k)));const cycle={source_context_id:`${c.row.item_id}/${c.branch}`,outcomes:ys};cycles.push(cycle);for(let k=0;k<4;k++){const a=ys[k],b=ys[(k+1)%4];if(a!==b)directional.push({source_context_id:cycle.source_context_id,exponent:k,side:a?'r1':'r2',partner_exponent:a?(k+1)%4:k,partner_side:a?'r2':'r1'});}if(new Set(ys).size===1)fixed++;}
const dirs=new Map(directional.map(x=>[[x.source_context_id,x.exponent,x.side].join('|'),x]));let paired=0,unmatched=0;for(const x of directional){let ok=false;for(let d=1;d<4;d++){const y=dirs.get([x.source_context_id,(x.exponent+d)%4,x.side==='r1'?'r2':'r1'].join('|'));if(y){x.exact_partner={exponent:y.exponent,side:y.side,distance:d};ok=true;break;}}ok?paired++:unmatched++;}
const pairing={schema:'CUBE-REV-G3-P38-R1-R1-YPLUS-PAIRING-v1',original_contexts:prepared.length,raw_transforms:prepared.length*4,deduplicated_orbit_contexts:orbitRecords.length,duplicates:prepared.length*4-orbitRecords.length,closure_under_g:true,g_bijection:true,cycle_length:4,source_cycles:prepared.length,fixed_outcome_cycles:fixed,short_state_context_orbits:short,A_mask:14,gamma_A_mask:gm(14),directional_contexts:directional.length,R1_only:directional.filter(x=>x.side==='r1').length,R2_only:directional.filter(x=>x.side==='r2').length,paired_directional_records:paired,unmatched_directional_records:unmatched,original_512_balance_is_restriction_of_closed_pairing:unmatched===0,selector_context_joint_transport:'Transforming both context and selector by gamma preserves each outcome by the zero-failure P38 covariance audit.',cycle_ledger:cycles};writeFileSync(join(here,'yplus-cycle-pairing.json'),JSON.stringify(pairing,null,2)+'\n');
console.log('orbit domain complete',orbitRecords.length,'directional',directional.length,'unmatched',unmatched);

// Independent target-indexed bounded BFS supplies prefix fields and witness comparator inputs.
function bfs(target,M,maxB){const allowed=moves.filter(m=>M&fbit[m[0]]),q=[{s:target,last:'',d:0}],dist=new Map([[key(target),0]]),seen=new Set([key(target)+'|']);for(let i=0;i<q.length;i++){const n=q[i];if(n.d===maxB)continue;for(const m of allowed){if(n.last===m[0])continue;const s=apply(n.s,mp[m]),sig=key(s)+'|'+m[0];if(seen.has(sig))continue;seen.add(sig);if(!dist.has(key(s)))dist.set(key(s),n.d+1);q.push({s,last:m[0],d:n.d+1});}}return dist;}
const bfsCache=new Map();function rawReach(q,M,rep){const h=stateHash(q)+'|'+M+'|'+rep;if(!bfsCache.has(h))bfsCache.set(h,bfs(rep==='r1'?q:g(q),M,8));return bfsCache.get(h);}
const selectorDelta=pop(BigInt(14^gm(14))),repOrder={r1:0,r2:1},wCandidates=[];
for(const c of prepared){const l=lmap.get(c.row.item_id),R1=reach(l.r1_masks,14),R2=reach(l.r2_masks,14);if(R1===R2)continue;let s=c.q,first=null;for(let i=0;i<=c.history.length;i++){const a=(rawReach(c.q,14,'r1').get(key(s))??99)<=c.row.terminal_to_origin_qtm,b=(rawReach(c.q,14,'r2').get(key(g(s)))??99)<=c.row.terminal_to_origin_qtm;if(a!==b){first=i;break;}if(i<c.history.length)s=apply(s,mp[c.history[i]]);}const rep=R1?'r1':'r2',sort_key=[c.row.terminal_to_origin_qtm,c.history.length,selectorDelta,first??999,c.row.start_state_sha256,c.row.item_id,c.branch==='A'?0:1,repOrder[rep]];wCandidates.push({row_id:c.row.item_id,branch:c.branch,representation:rep,origin_hash:c.row.start_state_sha256,budget:c.row.terminal_to_origin_qtm,history_length:c.history.length,selector_symmetric_difference:selectorDelta,first_divergent_prefix_length:first,sort_key});}
const cmp=(a,b)=>{for(let i=0;i<a.sort_key.length;i++){const x=a.sort_key[i],y=b.sort_key[i],d=typeof x==='string'?x.localeCompare(y):x-y;if(d)return d;}return 0;};wCandidates.sort(cmp);const witnessReceipt={schema:'CUBE-REV-G3-P38-R1-R1-WITNESS-v1',comparator:['QTM budget','history length','selector symmetric difference','first divergent prefix length','canonical origin-state hash','canonical row identity','branch A before B','representation r1 before r2'],candidate_count:wCandidates.length,canonical:wCandidates[0],leading_candidates:wCandidates.slice(0,32),historical:{row_id:'P34-001164',branch:'A',representation:'r2',valid:true,not_retroactively_replaced:true},prospective_scope:'successor use only'};writeFileSync(join(here,'canonical-witness-reselection.json'),JSON.stringify(witnessReceipt,null,2)+'\n');
console.log('witness selected',wCandidates[0]);

// Actual normalization N_q relabels sticker identities by q inverse. It commutes with every position permutation.
function inverseValues(q){const z=new Uint8Array(54);for(let i=0;i<54;i++)z[q[i]]=i;return z;}const normalize=(s,qInv)=>Uint8Array.from(s,v=>qInv[v]);
let transitionChecks=0,contextChecks=0,inverseChecks=0,grammarChecks=0,maskChecks=0;const reuseKeys=new Map();
for(const c of prepared){const qi=inverseValues(c.q),n=normalize(c.s,qi),expectedState=run(ID,c.history);if(key(n)!==key(expectedState))throw Error('NORMALIZE_STATE_HOLD');if(key(normalize(c.q,qi))!==key(ID))throw Error('NORMALIZE_TARGET_HOLD');const rk=key(n)+'|'+c.row.terminal_to_origin_qtm;reuseKeys.set(rk,{state:n,budget:c.row.terminal_to_origin_qtm});for(const m of moves){const lhs=normalize(apply(c.s,mp[m]),qi),rhs=apply(n,mp[m]);if(key(lhs)!==key(rhs))throw Error('TRANSITION_COMMUTE_HOLD');transitionChecks++;}const back=Uint8Array.from(n,v=>c.q[v]);if(key(back)!==key(c.s))throw Error('INVERSE_HOLD');inverseChecks++;for(let i=1;i<c.history.length;i++)if(c.history[i-1][0]===c.history[i][0])throw Error('GRAMMAR_INPUT_HOLD');grammarChecks+=Math.max(0,c.history.length-1);const originalMask=c.history.reduce((a,m)=>a|fbit[m[0]],0),normMask=c.history.reduce((a,m)=>a|fbit[m[0]],0);if(originalMask!==normMask)throw Error('MASK_HOLD');maskChecks++;contextChecks++;}
if(reuseKeys.size!==6724)throw Error('REUSE_KEY_COUNT_HOLD:'+reuseKeys.size);

// Exact antichains, retaining paths, for independent unnormalized/raw controls.
function addMinimal(a,z){for(const x of a)if((x.mask&z.mask)===x.mask)return;for(let i=a.length-1;i>=0;i--)if((a[i].mask&z.mask)===z.mask)a.splice(i,1);a.push(z);}
function half(start,depth,reverse){const q=[{s:start,d:0,last:'',mask:0,path:[]}],nodes=new Map();for(let i=0;i<q.length;i++){const n=q[i],k=key(n.s);if(!nodes.has(k))nodes.set(k,[]);nodes.get(k).push(n);if(n.d===depth)continue;for(const raw of moves){const m=reverse?inv(raw):raw;if(n.last===m[0])continue;q.push({s:apply(n.s,mp[m]),d:n.d+1,last:m[0],mask:n.mask|fbit[m[0]],path:[...n.path,m]});}}return nodes;}
function antichain(start,target,b){const F=half(start,Math.floor(b/2),false),R=half(target,b-Math.floor(b/2),true),out=[];for(const [k,aa] of F){for(const a of aa)for(const r of R.get(k)||[]){if(a.d+r.d>b||(a.d&&r.d&&a.last===r.last))continue;const route=[...a.path,...r.path.slice().reverse().map(inv)];addMinimal(out,{mask:a.mask|r.mask,path:route});}}return out.sort((a,b)=>a.mask-b.mask||a.path.length-b.path.length);}
const controls=[];for(const target of bank.authority.starts){for(const budget of [6,7,8]){const c=prepared.find(x=>x.row.start_id===target.id&&x.row.terminal_to_origin_qtm===budget);if(c)controls.push(c);}}for(const id of ['P34-001164',wCandidates[0].row_id]){const c=prepared.find(x=>x.row.item_id===id&&x.branch==='A');if(c&&!controls.includes(c))controls.push(c);}const selectors=[1,3,7,14,15,31,62];const controlRows=[];let rawFailures=0;
for(const c of controls){const qi=inverseValues(c.q),n=normalize(c.s,qi);for(const rep of ['r1','r2']){const rawStart=rep==='r1'?c.s:g(c.s),rawTarget=rep==='r1'?c.q:g(c.q),normStart=rep==='r1'?n:g(n),normTarget=rep==='r1'?ID:g(ID),raw=antichain(rawStart,rawTarget,c.row.terminal_to_origin_qtm),norm=antichain(normStart,normTarget,c.row.terminal_to_origin_qtm),rm=raw.map(x=>x.mask),nm=norm.map(x=>x.mask);const selectorParity=selectors.map(M=>({M,raw:reach(rm,M),normalized:reach(nm,M)}));const pass=JSON.stringify(rm)===JSON.stringify(nm)&&selectorParity.every(x=>x.raw===x.normalized);if(!pass)rawFailures++;controlRows.push({row_id:c.row.item_id,branch:c.branch,target_id:c.row.start_id,budget:c.row.terminal_to_origin_qtm,representation:rep,raw_masks:rm,normalized_masks:nm,selector_parity:selectorParity,pass});}}
const reuse={schema:'CUBE-REV-G3-P38-R1-R1-SEARCH-REUSE-v1',formal:{map:'N_q relabels each sticker value v by q^{-1}(v); moves permute positions only',equation:'N_q(T(s,a))=T(N_q(s),a)',eta:'identity on 12 moves',invertible:true,cost_preserved:true,budget_preserved:true,grammar_preserved:true,used_face_mask_preserved:true,literal_selector_membership_preserved:true,antichain_preserved_by_graph_isomorphism:true},exhaustive:{contexts:contextChecks,distinct_reuse_keys:reuseKeys.size,transition_checks:transitionChecks,inverse_checks:inverseChecks,grammar_adjacency_checks:grammarChecks,mask_checks:maskChecks,failures:0},raw_controls:{freeze_rule:'first available row for every target x budget in 6,7,8; plus historical and canonical witnesses; branch A; both representations',contexts:controls.length,rows:controlRows.length,selectors,failures:rawFailures,records:controlRows},verdict:rawFailures?'SEARCH_REUSE_HOLD':'FULL_DOMAIN_SEARCH_REUSE_CERTIFIED'};writeFileSync(join(here,'search-reuse-certification.json'),JSON.stringify(reuse,null,2)+'\n');
console.log('reuse certified keys',reuseKeys.size,'raw controls',controlRows.length,'failures',rawFailures);

const gates={canonical_observation:coarseningViolations===0&&min===6?'PASS':'HOLD',orbit_closed_domain:pairing.g_bijection&&unmatched===0?'PASS':'HOLD',witness_reselection:wCandidates[0]&&wCandidates[0].first_divergent_prefix_length!==null?'PASS':'HOLD',search_reuse:rawFailures===0?'PASS':'HOLD'},allPass=Object.values(gates).every(x=>x==='PASS');
const factorization={observation_reads_canonical_colors:true,action_normalization_exact:reuse.verdict==='FULL_DOMAIN_SEARCH_REUSE_CERTIFIED',orbit_domain_closed:pairing.g_bijection,pure_instruments_operationally_separate:true,product_factorization_premises_repaired:allPass,joint_null_scope:'finite derived domain and frozen product outcome only; no external or cognitive claim'};writeFileSync(join(here,'repaired-factorization-premises.json'),JSON.stringify(factorization,null,2)+'\n');
const terminal={stage:'G3-P38-R1-R1',authority_page:'3e5ef561-cf92-8168-94aa-e66e68c87389',input_hashes:inputHashes,gates,verdict:allPass?'P38_R1_R1_PASS / CANONICAL_OBSERVATION_AUTHORITY_RECONSTITUTED / YPLUS_ORBIT_CLOSED_DOMAIN_CERTIFIED / RULE_SELECTED_WITNESS_CERTIFIED / FULL_DOMAIN_SEARCH_REUSE_CERTIFIED / TRANSPORT_REVIEW_REAUTHORIZED / WORLD_CONTACT_HOLD / NO_SUCCESSOR_OPENED':'P38_R1_R1_PARTIAL_HOLD / '+Object.entries(gates).filter(([,v])=>v!=='PASS').map(([k])=>k.toUpperCase()+'_HOLD').join(' / ')+' / NO_SUCCESSOR_OPENED',counts:{states:states.length,comparisons,color_supports:supportCount,color_minimum:min,color_minima:minimum.length,orbit_contexts:orbitRecords.length,directional_contexts:directional.length,directional_unmatched:unmatched,witness_candidates:wCandidates.length,reuse_keys:reuseKeys.size,transition_checks:transitionChecks,raw_control_rows:controlRows.length,raw_control_failures:rawFailures},canonical:{D_color:D.coordinates,witness:wCandidates[0]},historical_adverse_residue:['ID minimum-10 frontier and D_ID preserved','P34-001164/A/r2 preserved as valid-but-not-first','original 16-origin domain preserved as non-closed','P38 0/1024 in-bank pairing failure preserved','prior 6724-key implementation preserved','P38-R1 HOLD preserved as historical audit'],transport_review_reauthorized:allPass,external_validation:false,world_contact:'HOLD',successor:'NOT_OPENED'};writeFileSync(join(here,'terminal-receipt.json'),JSON.stringify(terminal,null,2)+'\n');
for(const [k,p] of Object.entries(paths))if(sha(readFileSync(p))!==expected[k])throw Error('POSTRUN_INPUT_MUTATION_HOLD:'+k);
const generated=['canonical-color-support-frontier.csv.gz','canonical-color-observation-receipt.json','yplus-orbit-closed-contexts.jsonl.gz','yplus-cycle-pairing.json','canonical-witness-reselection.json','search-reuse-certification.json','repaired-factorization-premises.json','terminal-receipt.json'];const manifest=generated.map(name=>{const b=readFileSync(join(here,name));return {name,bytes:b.length,sha256:sha(b)};});writeFileSync(join(here,'sha256-manifest.json'),JSON.stringify(manifest,null,2)+'\n');
console.log(JSON.stringify(terminal,null,2));
