import {writeFileSync,readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {dirname,join} from 'node:path';import {fileURLToPath} from 'node:url';
const here=dirname(fileURLToPath(import.meta.url)),sha=x=>createHash('sha256').update(x).digest('hex'),ok=(x,m)=>{if(!x)throw Error(m);};
const reach=(sys,start,M,B=sys.B)=>{const q=[[start,0]],seen=new Set([start+'|0']);for(let i=0;i<q.length;i++){const [s,d]=q[i];if(sys.Q.includes(s))return true;if(d===B)continue;for(const a of M){const t=sys.T[s][a],k=t+'|'+(d+1);if(!seen.has(k)){seen.add(k);q.push([t,d+1]);}}}return false;};
const cases=[];function add(id,object,predicate,minimality){ok(predicate(object),id);cases.push({id,object,minimality,verified:true});}
add('CE-T1-CONVERSE',{S:[0,1],A:[0],T:[[0],[0]],Q:[0],g:[1,0],contexts:[0]},x=>reach({...x,B:0},0,[],0)===true&&x.g[x.T[0][0]]!==x.T[x.g[0]][0],{status:'EXHAUSTIVE_LOWER_BOUND',reason:'One state admits only the identity state bijection; two states are the first size at which outcome agreement and transition non-equivariance coexist.'});
add('CE-T3-STRICT',{psi:[[0],[1]],p:[0,0],Q:[0]},x=>x.psi[0][0]!==x.psi[1][0]&&x.p[x.psi[0][0]]===x.p[x.psi[1][0]],{status:'EXHAUSTIVE_LOWER_BOUND',reason:'A strict support inclusion requires two states and one coordinate; this construction attains both bounds.'});
add('CE-T3-OPTIMIZER',{psi:[[0,0],[1,0],[0,2]],p:[0,0,1],Q:[0]},x=>{const d=(a,b,p)=>a.map((v,i)=>p[v]!==p[b[i]]?i:-1).filter(i=>i>=0);return JSON.stringify(d(x.psi[0],x.psi[1],[0,1,2]))!==JSON.stringify(d(x.psi[0],x.psi[1],x.p));},{status:'STRUCTURAL_MINIMAL',reason:'Two coordinates and a noninjective semantic map are required for optimizer identity to change rather than only cardinality.'});
add('CE-T4-CONVERSE',{S:[0,1],A:[0],T:[[0],[0]],Q:[0],B:1,M:[],N:[0],start:1},x=>!reach(x,x.start,x.M)&&reach(x,x.start,x.N),{status:'EXHAUSTIVE_LOWER_BOUND',reason:'Two states, one action and budget one are necessary and sufficient for added-action reachability.'});
add('CE-T4-DIVERGENCE',{S:[0,1,2],A:[0,1],T:[[0,0],[0,1],[2,0]],Q:[0],B:1,starts:[1,2],M:[0],N:[0,1]},x=>reach(x,1,x.M)!==reach(x,2,x.M)&&reach(x,1,x.N)===reach(x,2,x.N),{status:'EXHAUSTIVE_LOWER_BOUND',reason:'One target and two distinct non-target starts require three states; one added action requires two actions.'});
add('CE-T5-AGGREGATE',{X:[0,1],C:[0],g:[1,0],outcomes:{left:[1],right:[1]}},x=>!x.C.includes(x.g[x.C[0]])&&x.outcomes.left.reduce((a,b)=>a+b,0)===x.outcomes.right.reduce((a,b)=>a+b,0),{status:'EXHAUSTIVE_LOWER_BOUND',reason:'A nonclosed bijection needs at least two ambient objects; a singleton restricted domain already permits equal aggregates without internal pairing.'});
add('CE-T6-QUERY',{S:[0,1],A:[0],T:[[0],[0]],Q:[0],B:0,N:[0,0],query:0},x=>reach(x,x.query,[],0)===reach(x,x.N[x.query],[],0)&&new Set(x.N).size<x.S.length,{status:'EXHAUSTIVE_LOWER_BOUND',reason:'Two states are minimal for a noninvertible normalization; budget zero gives the smallest accidental query agreement.'});
add('CE-T7-SCALAR',{pureO:[0,1],pureA:[0,1],J:(o,a)=>o&&a},x=>x.J(1,1)!==x.J(1,0)&&x.J(1,1)!==x.J(0,1),{status:'EXHAUSTIVE_BOOLEAN',reason:'Two independent Boolean channels and conjunction are the smallest coupled scalar readout.'});
add('CE-T8-AND',{baseline:[0,0],O:[1,0],A:[0,1],OA:[1,1],J:([o,a])=>o&&a},x=>x.J(x.baseline)===x.J(x.O)&&x.J(x.baseline)===x.J(x.A)&&x.J(x.OA)!==x.J(x.baseline),{status:'EXHAUSTIVE_BOOLEAN',reason:'Conjunction on two Boolean axes is the unique canonical minimal joint-only pattern up to complementation and relabeling.'});
add('CE-T9-SIMULATION-NEGATIVE',{source:{S:[0],A:[0],T:[[0]],Q:[],B:1},target:{S:[0,1],A:[0],T:[[1],[1]],Q:[1],B:1},h:[0]},x=>!reach(x.source,0,[0])&&reach(x.target,x.h[0],[0]),{status:'EXHAUSTIVE_LOWER_BOUND',reason:'The source needs one non-target state; the codomain needs one additional target state and one transition to defeat negative transport.'});
add('CE-T9-QUOTIENT-LABEL',{S:[0,1],h:[0,0],Q:[0]},x=>x.h[0]===x.h[1]&&x.Q.includes(0)!==x.Q.includes(1),{status:'EXHAUSTIVE_LOWER_BOUND',reason:'Two differently labelled states merged into one quotient cell are minimal.'});
const banned=['cube','face','sticker','scramble','solve','rotation','rubik','U/D/L/R/F/B'];const core=['qast-axioms.md','theorem-ledger.json'];const erasure=[];for(const f of core){const text=readFileSync(join(here,f),'utf8'),hits=banned.filter(w=>text.toLowerCase().includes(w.toLowerCase()));erasure.push({file:f,hits,pass:hits.length===0,sha256:sha(text)});}ok(erasure.every(x=>x.pass),'CUBE_ERASURE_HOLD');
const out={schema:'CUBE-REV-G3-P38-R2-COUNTEREXAMPLE-ATLAS-v1',frozen_order:['states','actions','budget','maximum observation fiber','selector-family size','canonical encoding'],cases,cube_erasure:erasure,verdict:'COUNTEREXAMPLE_ATLAS_PASS'};writeFileSync(join(here,'minimal-counterexample-atlas.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify({cases:cases.length,erasure},null,2));
