import fs from 'node:fs';
import { parseAnnotated } from '../0.10.5-r1.9/r19_quotient_core.mjs';
import { buildRouxFrameCore } from './r110_roux_frame_core.mjs';
const OUT=process.env.R110_DIAG_ROOT||'/tmp/r110diag';fs.mkdirSync(OUT,{recursive:true});
const c=await buildRouxFrameCore();const {kp,defaultPattern,EDGE,CORNER,ORIENT,frames,canonicalizeByCenters}=c;
const coord=(p,o,i,ch='full')=>{const a=p.patternData[o],b=defaultPattern.patternData[o];return (ch==='piece'||ch==='full'?a.pieces[i]===b.pieces[i]:true)&&(ch==='orientation'||ch==='full'?a.orientation[i]===b.orientation[i]:true);};
function blockScore(p,m,ch='full'){let ok=0;for(const i of m.edges)if(coord(p,EDGE,i,ch))ok++;for(const i of m.corners)if(coord(p,CORNER,i,ch))ok++;return ok;}
function exactCanonical(raw,ch='full'){const x=canonicalizeByCenters(raw);if(!x.ok)return [];return frames.filter(f=>blockScore(x.pattern,f.first,ch)===5);}
function orientationFree(raw,ch='full'){const seen=new Map();for(const rot of ORIENT){const p=raw.applyTransformation(rot);for(const f of frames)if(blockScore(p,f.first,ch)===5){const k=`${f.bottom}|${f.first_side}`;if(!seen.has(k))seen.set(k,f);}}return [...seen.values()];}
function bestCanonical(raw,ch='full'){const x=canonicalizeByCenters(raw);if(!x.ok)return null;return Math.max(...frames.map(f=>blockScore(x.pattern,f.first,ch)));}
function load(){const a=JSON.parse(fs.readFileSync('research/0.10.5-r1.7/evidence-full-route/FULL_ROUTE_SAMPLE_MANIFEST.json','utf8')).records;const b=JSON.parse(fs.readFileSync('research/0.10.5-r1.8/evidence-holdout-a/HOLDOUT_A_ROUTE_MANIFEST.json','utf8')).records;return [...a,...b].filter(r=>r.method==='Roux'&&r.route_source_status==='RAW_ALG_CUBING_LINK');}
const rows=[];for(const r of load())try{const p=parseAnnotated(r.raw_alg,'Roux'),moves=p.tokens.map(x=>x.move);let s=defaultPattern.applyAlg(r.raw_setup),states=[s];for(const m of moves){s=s.applyMove(m);states.push(s);}if(!s.experimentalIsSolved({ignorePuzzleOrientation:true,ignoreCenterOrientation:true}))continue;const fb=p.lines.find(x=>x.phase==='ROUX_FB'&&x.end>x.start),sb=p.lines.find(x=>x.phase==='ROUX_SB'&&x.end>x.start);if(!fb||!sb)continue;const fe=states[fb.end],se=states[sb.end];const cf=exactCanonical(fe,'full'),cp=exactCanonical(fe,'piece'),of=orientationFree(fe,'full'),op=orientationFree(fe,'piece');rows.push({result_id:r.result_id,attempt_number:r.attempt_number,reco_id:r.reco_id,fb:[fb.start,fb.end],sb:[sb.start,sb.end],fb_exact_full:cf.length,fb_exact_piece:cp.length,fb_orientation_free_full:of.length,fb_orientation_free_piece:op.length,fb_best_full:bestCanonical(fe,'full'),fb_best_piece:bestCanonical(fe,'piece'),sb_exact_full_blocks:exactCanonical(se,'full').length,sb_orientation_free_full_blocks:orientationFree(se,'full').length});}catch(e){rows.push({result_id:r.result_id,attempt_number:r.attempt_number,reco_id:r.reco_id,error:String(e?.message||e).slice(0,200)});}
const clean=rows.filter(r=>!r.error),count=(k,v)=>clean.filter(r=>r[k]===v).length,dist=k=>Object.fromEntries([...new Set(clean.map(r=>r[k]))].sort((a,b)=>a-b).map(v=>[String(v),count(k,v)]));
const out={schema_version:'CR0105R110-ROUX-FRAME-FAILURE-DIAGNOSTIC-1',status:'POSTHOC_DIAGNOSTIC_ONLY',authority_changed:false,gates_changed:false,rows_n:rows.length,clean_n:clean.length,distributions:{fb_exact_full:dist('fb_exact_full'),fb_exact_piece:dist('fb_exact_piece'),fb_orientation_free_full:dist('fb_orientation_free_full'),fb_orientation_free_piece:dist('fb_orientation_free_piece'),fb_best_full:dist('fb_best_full'),fb_best_piece:dist('fb_best_piece'),sb_exact_full_blocks:dist('sb_exact_full_blocks'),sb_orientation_free_full_blocks:dist('sb_orientation_free_full_blocks')},human_observations:0};
fs.writeFileSync(`${OUT}/ROUX_FRAME_FAILURE_DIAGNOSTIC.json`,JSON.stringify(out,null,2)+'\n');fs.writeFileSync(`${OUT}/ROUX_FRAME_FAILURE_DIAGNOSTIC_ROWS.json`,JSON.stringify({rows},null,2)+'\n');console.log(JSON.stringify(out,null,2));
