import fs from 'node:fs';
import { upperQuantile, mean } from './r19_quotient_core.mjs';
const OUT=process.env.R19_SCALE_ROOT||'/tmp/r19scale';fs.mkdirSync(OUT,{recursive:true});
const F=JSON.parse(fs.readFileSync('research/0.10.5-r1.9/evidence-familywise-development/QUOTIENT_FEATURE_LEDGER.json','utf8')).rows;
const A=JSON.parse(fs.readFileSync('research/0.10.5-r1.9/evidence-familywise-development/CROSSFIT_ATTEMPT_REFERENCE.json','utf8')).rows.filter(x=>x.attempt_statistic!==null);
const R3=JSON.parse(fs.readFileSync('research/0.10.5-r1.9/evidence-nested-gate-repair/ATTEMPT_FAMILYWISE_NULL_PREREG_SEAL_R3.json','utf8'));
const fresh=JSON.parse(fs.readFileSync('research/0.10.5-r1.9/evidence-fresh-readiness/FRESH_VINTAGE_READINESS.json','utf8'));
if(R3.future_fresh_outcomes_seen!==false)throw new Error('R19_R3_FRESH_FLAG_NOT_FALSE');
if(fresh.fresh.new_reco_id_rows!==0)throw new Error('R19_SCALE_AUDIT_ONLY_IMPLEMENTED_FOR_ZERO_FRESH_CURRENT_VINTAGE');
function key(r){return `${r.result_id}:${r.attempt_number}`;}
function bin(n){return n<=8?'1-8':n<=12?'9-12':n<=16?'13-16':'17+';}
function lowerBound(a,x){let l=0,h=a.length;while(l<h){const m=(l+h)>>1;if(a[m]<x-1e-12)l=m+1;else h=m;}return l;}
class Group{
 constructor(rows){this.values=rows.map(r=>r.reference_envelope).sort((a,b)=>a-b);this.by=new Map();for(const r of rows){const k=key(r);if(!this.by.has(k))this.by.set(k,[]);this.by.get(k).push(r.reference_envelope);}for(const v of this.by.values())v.sort((a,b)=>a-b);}
 score(z){const own=this.by.get(key(z))||[],n=this.values.length-own.length;if(!n)return null;const ge=(this.values.length-lowerBound(this.values,z.observed_amplitude))-(own.length-lowerBound(own,z.observed_amplitude));const p=(1+ge)/(n+1);return {n,p,score:-Math.log10(p)};}
}
function makeIndex(){const maps={mpcb:new Map(),pcb:new Map(),mpc:new Map(),pc:new Map(),gc:new Map()};const add=(m,k,r)=>{if(!m.has(k))m.set(k,[]);m.get(k).push(r)};for(const r of F){add(maps.mpcb,`${r.method}|${r.phase}|${r.channel}|${r.move_bin}`,r);add(maps.pcb,`${r.phase}|${r.channel}|${r.move_bin}`,r);add(maps.mpc,`${r.method}|${r.phase}|${r.channel}`,r);add(maps.pc,`${r.phase}|${r.channel}`,r);add(maps.gc,r.channel,r);}for(const [name,m] of Object.entries(maps))for(const [k,v] of m)m.set(k,new Group(v));return maps;}
const I=makeIndex();
function local(z){const levels=[['METHOD_PHASE_CHANNEL_BIN',I.mpcb.get(`${z.method}|${z.phase}|${z.channel}|${z.move_bin}`),120],['PHASE_CHANNEL_BIN',I.pcb.get(`${z.phase}|${z.channel}|${z.move_bin}`),160],['METHOD_PHASE_CHANNEL',I.mpc.get(`${z.method}|${z.phase}|${z.channel}`),120],['PHASE_CHANNEL',I.pc.get(`${z.phase}|${z.channel}`),200],['GLOBAL_CHANNEL',I.gc.get(z.channel),500]];for(const [level,g,min] of levels){if(!g)continue;const s=g.score(z);if(s&&s.n>=min)return {...s,level};}return null;}
const by=new Map();let fallback=0;for(const z of F){const s=local(z);if(!s){fallback++;continue;}const k=key(z);if(!by.has(k))by.set(k,[]);by.get(k).push(s.score);}
const loo=[];for(const a of A){const v=by.get(key(a))||[];loo.push({...a,loo_feature_n:v.length,loo_feature_count_bin:bin(v.length),loo_attempt_statistic:v.length?Math.max(...v):null});}
function familyBank(a){const rows=A.filter(r=>key(r)!==key(a));const levels=[['METHOD_COUNT',rows.filter(r=>r.method===a.method&&r.feature_count_bin===a.loo_feature_count_bin),300],['COUNT',rows.filter(r=>r.feature_count_bin===a.loo_feature_count_bin),300],['METHOD',rows.filter(r=>r.method===a.method),300],['GLOBAL',rows,1000]];for(const [level,x,min] of levels)if(x.length>=min)return {level,rows:x,n:x.length,required:min};return null;}
let ok=0,p01=0,p05=0;const levels={},comparisons=[];for(const a of loo){if(a.loo_attempt_statistic===null)continue;const ref=familyBank(a);if(!ref)continue;const ge=ref.rows.filter(r=>r.attempt_statistic>=a.loo_attempt_statistic-1e-12).length,p=(1+ge)/(ref.n+1);ok++;if(p<=.01)p01++;if(p<=.05)p05++;levels[ref.level]=(levels[ref.level]||0)+1;comparisons.push({key:key(a),method:a.method,crossfit_stat:a.attempt_statistic,loo_full_scale_stat:a.loo_attempt_statistic,abs_diff:Math.abs(a.attempt_statistic-a.loo_attempt_statistic),familywise_p:p,level:ref.level,n:ref.n});}
const primary=p01/ok,watch=p05/ok,diffs=comparisons.map(x=>x.abs_diff),cross=comparisons.map(x=>x.crossfit_stat),loov=comparisons.map(x=>x.loo_full_scale_stat);const mx=mean(cross),my=mean(loov);let num=0,dx=0,dy=0;for(let i=0;i<cross.length;i++){num+=(cross[i]-mx)*(loov[i]-my);dx+=(cross[i]-mx)**2;dy+=(loov[i]-my)**2;}const corr=num/Math.sqrt(dx*dy);
const checks={loo_attempts_ge_1200:ok>=1200,local_fallback_rate_le_0_05:fallback/Math.max(1,F.length)<=.05,pseudo_fresh_primary_health:primary>=.003&&primary<=.02,pseudo_fresh_watch_health:watch>=.025&&watch<=.08,crossfit_loo_stat_correlation_ge_0_95:corr>=.95,r3_sealed:true,current_fresh_zero:true};
const status=Object.values(checks).every(Boolean)?'PASS_FUTURE_SCALE_COMPATIBILITY':'HOLD_FUTURE_SCALE_COMPATIBILITY';
const out={schema_version:'CR0105R19-FUTURE-SCORE-SCALE-COMPATIBILITY-1',status,role:'POST-SEAL ZERO-FRESH ENGINEERING AUDIT; DOES NOT CHANGE THE FROZEN METRIC OR NULL',r3_seal:R3.seal_sha256,current_fresh_status:fresh.status,loo_full_history_local_reference:{attempts:ok,feature_fallback_n:fallback,feature_fallback_rate:fallback/Math.max(1,F.length)},pseudo_fresh_against_sealed_crossfit_bank:{primary_alpha:.01,primary_empirical_exceedance:primary,watch_alpha:.05,watch_empirical_exceedance:watch,familywise_levels:levels},score_transport:{pearson_crossfit_vs_loo:corr,abs_difference:{p50:upperQuantile(diffs,.5),p90:upperQuantile(diffs,.9),p99:upperQuantile(diffs,.99),max:Math.max(...diffs)}},checks,adjudication:'This audit approximates the future scoring scale by scoring each historical attempt against all other historical features, then comparing that attempt statistic to the already sealed cross-fitted historical attempt bank. It is an engineering transport check only; the nested R3 audit remains the no-test-fold-leak calibration proof.',human_observations:0};
fs.writeFileSync(`${OUT}/FUTURE_SCORE_SCALE_COMPATIBILITY.json`,JSON.stringify(out,null,2)+'\n');
console.log(JSON.stringify(out,null,2));if(status!=='PASS_FUTURE_SCALE_COMPATIBILITY')process.exit(20);
