/* G3-P37-R1: exact sealed difference supports and all literal face subsets. */
import { createHash } from 'node:crypto'; import { createWriteStream,readFileSync,writeFileSync } from 'node:fs'; import { dirname,join } from 'node:path'; import { fileURLToPath } from 'node:url'; import { applyMove,applySequence,serializeState,solvedState } from '../state-adapter.js';
const HERE=dirname(fileURLToPath(import.meta.url)),ROOT=join(HERE,'..'),P34=join(ROOT,'p34-runtime'),P35=join(ROOT,'p35-runtime'),P36=join(ROOT,'p36-runtime');
const BANK_SHA='cef57e7943510d15d2bfbb59f18761217599f9d5c7b749511a02d1c371e9ae00',P35_SHA='db488ba3fa2ac163d9160e06f5df9e0965d12d12d07ece9891396a454638683b',P36_SHA='e04455b9831326c0cefbb0db8e794116c295e672fcab02dfbc67dbc1a75353c9';
const MOVES=['U',"U'",'D',"D'",'L',"L'",'R',"R'",'F',"F'",'B',"B'"],FACES=['U','D','L','R','F','B'],FACE_MAP={U:'U',D:'D',F:'R',R:'B',B:'L',L:'F'}; const sha=x=>createHash('sha256').update(x).digest('hex'),face=x=>x[0],key=s=>Buffer.from(s).toString('base64'),eq=(a,b)=>key(a)===key(b),slot=x=>[...x.p,...x.n].join(','),rotY=([x,y,z])=>[z,y,-x];
const BASE=solvedState().map(x=>({...x,p:[...x.p],n:[...x.n]})).sort((a,b)=>slot(a).localeCompare(slot(b))), SLOTS=BASE.map((x,i)=>({...x,p:[...x.p],n:[...x.n],c:String(i)})), COLORS=BASE.map(x=>x.c), ID=Uint8Array.from(SLOTS.map((_,i)=>i));
function permFrom(t){const s=SLOTS.map((x,i)=>({p:[...x.p],n:[...x.n],c:String(i)}));t(s);return Uint8Array.from(s.sort((a,b)=>slot(a).localeCompare(slot(b))).map(x=>Number(x.c)));} const MOVE=Object.fromEntries(MOVES.map(m=>[m,permFrom(s=>applyMove(s,m))])),G=permFrom(s=>{for(const x of s){x.p=rotY(x.p);x.n=rotY(x.n);}});
function apply(s,p){const o=new Uint8Array(s.length);for(let i=0;i<o.length;i++)o[i]=s[p[i]];return o;} function run(s,w){let o=Uint8Array.from(s);for(const m of w)o=apply(o,MOVE[m]);return o;} const g=s=>apply(s,G),toAdapter=s=>BASE.map((x,i)=>({p:[...x.p],n:[...x.n],c:COLORS[s[i]]})),exactHash=s=>sha(serializeState(toAdapter(s)));
const bytes=p=>readFileSync(p), bankBytes=bytes(join(P34,'p34-bank.json')),p35Bytes=bytes(join(P35,'p35-r1-r2-receipt.json')),p36Bytes=bytes(join(P36,'p36-r1-receipt.json')); if(sha(bankBytes)!==BANK_SHA||sha(p35Bytes)!==P35_SHA||sha(p36Bytes)!==P36_SHA)throw Error('INHERITED_BYTE_HOLD'); const bank=JSON.parse(bankBytes),p36=JSON.parse(p36Bytes); if(bank.rows.length!==109184||p36.analysis_universe.states!==155040||p36.analysis_universe.contexts!==218368)throw Error('INHERITED_CARDINALITY_HOLD');
const starts=new Map();for(const x of bank.authority.starts){const s=run(ID,x.scramble);if(exactHash(s)!==x.state_sha256||serializeState(applySequence(solvedState(),x.scramble))!==serializeState(toAdapter(s)))throw Error(`START_HOLD:${x.id}`);starts.set(x.id,s);} const targets=[...starts.values()];
const encountered=new Map(),prepared=[];for(const row of bank.rows){const origin=starts.get(row.start_id),A=row.word_A.split(' '),B=row.word_B.split(' ');let terminal=origin;encountered.set(key(origin),origin);for(const m of A){terminal=run(terminal,[m]);encountered.set(key(terminal),terminal);}if(exactHash(terminal)!==row.terminal_state_sha256)throw Error(`TERMINAL_HOLD:${row.item_id}`);prepared.push({row,origin,terminal,A,B});for(const history of [B]){let s=origin;for(const m of history){s=run(s,[m]);encountered.set(key(s),s);}if(exactHash(s)!==row.terminal_state_sha256)throw Error(`BRANCH_HOLD:${row.item_id}`);}} if(encountered.size!==155040)throw Error(`UNIVERSE_HOLD:${encountered.size}`);
const states=[...encountered.values()],stateHashes=states.map(exactHash),hashToIndex=new Map(stateHashes.map((h,i)=>[h,i])); const targetIndex=targets.map(s=>hashToIndex.get(exactHash(s))); if(targetIndex.some(x=>x===undefined))throw Error('TARGET_UNIVERSE_HOLD');
function support(q,x){let m=0n;for(let i=0;i<54;i++)if(q[i]!==x[i])m|=1n<<BigInt(i);return m;} function pop(m){let n=0;while(m){m&=m-1n;n++;}return n;} function coords(m){const a=[];for(let i=0;i<54;i++)if((m&(1n<<BigInt(i)))!==0n)a.push(i);return a;} const maskKey=m=>m.toString(16).padStart(14,'0');
const supports=new Map(), targetContextCounts=new Map();for(const {row} of prepared){const h=row.start_state_sha256;targetContextCounts.set(h,(targetContextCounts.get(h)??0)+2);} let comparisons=0,minSize=99;
for(let ti=0;ti<targets.length;ti++){const q=targets[ti],qh=stateHashes[targetIndex[ti]];for(let xi=0;xi<states.length;xi++){if(xi===targetIndex[ti])continue;const m=support(q,states[xi]),k=maskKey(m),n=pop(m);let r=supports.get(k);if(!r){r={mask:m,size:n,targetBits:0,pairs:0};supports.set(k,r);}r.targetBits|=1<<ti;r.pairs++;comparisons++;if(n<minSize)minSize=n;}}
const coverage=r=>{let n=0;for(let i=0;i<targets.length;i++)if(r.targetBits&(1<<i))n+=targetContextCounts.get(stateHashes[targetIndex[i]])??0;return n;}; const minCandidates=[...supports.values()].filter(r=>r.size===minSize); 
function projection(s,m){let z='';for(let i=0;i<54;i++)if((m&(1n<<BigInt(i)))===0n)z+=String.fromCharCode(65+s[i]);return z;}
function induced(m){const groups=new Map();for(let i=0;i<states.length;i++){const p=projection(states[i],m);if(!groups.has(p))groups.set(p,[]);groups.get(p).push(i);}let pairs=0,max=0,aliased=0;const hist={};for(const v of groups.values()){hist[v.length]=(hist[v.length]??0)+1;if(v.length>1){aliased++;pairs+=v.length*(v.length-1)/2;}max=Math.max(max,v.length);}return {groups,pairs,max,aliased,hist};}
for(const r of minCandidates){r.induced=induced(r.mask);r.coverage=coverage(r);} minCandidates.sort((a,b)=>a.size-b.size||b.coverage-a.coverage||a.induced.pairs-b.induced.pairs||maskKey(a.mask).localeCompare(maskKey(b.mask))); const D=minCandidates[0]; if(!D)throw Error('NO_SUPPORT_HOLD');
const dGroups=D.induced.groups,dAlias=[];for(const [p,members] of dGroups)if(members.length>1)dAlias.push({projection_sha256:sha(p),members:members.map(i=>stateHashes[i])});let witness=null;for(let ti=0;ti<targets.length&&!witness;ti++){const q=targets[ti],qi=targetIndex[ti],pq=projection(q,D.mask);for(const xi of dGroups.get(pq)){if(xi!==qi){witness={target_hash:stateHashes[qi],rival_hash:stateHashes[xi],support_coordinates:coords(D.mask),pre_deletion_unequal:true,post_deletion_equal:true,target_contexts:targetContextCounts.get(stateHashes[qi])??0,r1_observation_sha256:sha(pq),r2_observation_sha256:sha(projection(g(q),D.mask))};break;}}}
if(!witness)throw Error('D_STAR_WITNESS_HOLD');
const supportHist={};for(const r of supports.values())supportHist[r.size]=(supportHist[r.size]??0)+1; const frontier=[...supports.values()].filter(r=>!([...supports.values()].some(s=>s.size<r.size&&(s.targetBits===r.targetBits)))).map(r=>({support_hex:maskKey(r.mask),size:r.size,target_context_coverage:coverage(r),target_states:[...Array(targets.length).keys()].filter(i=>r.targetBits&(1<<i)).length,target_rival_pairs:r.pairs,strict_superset_same_coverage:false})).sort((a,b)=>a.size-b.size||b.target_context_coverage-a.target_context_coverage||a.support_hex.localeCompare(b.support_hex));
if(process.env.LANE_O_ONLY==='1'){
 const supportPath=join(HERE,'p37-r1-r1-lane-o-frontier.json');const laneO={schema:'CUBE-REV-G3-P37-R1-R1-LANE-O-v1',authority:{p34_sha256:sha(bankBytes),p35_sha256:sha(p35Bytes),p36_sha256:sha(p36Bytes),unchanged:true},implementation:{compiler_sha256:sha(bytes(fileURLToPath(import.meta.url))),state_adapter_sha256:sha(bytes(join(ROOT,'state-adapter.js')))},targets:targets.length,comparison_states:states.length,target_rival_comparisons:comparisons,unique_supports:supports.size,support_size_histogram:supportHist,frontier,D_star:{support_hex:maskKey(D.mask),coordinates:coords(D.mask),size:D.size,target_context_coverage:D.coverage,collateral_pairs:D.induced.pairs,collateral_aliased_fibers:D.induced.aliased,max_fiber:D.induced.max,fiber_histogram:D.induced.hist,witness,collateral_aliases:dAlias}};writeFileSync(supportPath,JSON.stringify(laneO,null,2)+'\n');laneO.frontier_sha256=sha(bytes(supportPath));writeFileSync(join(HERE,'p37-r1-r1-lane-o-receipt.json'),JSON.stringify(laneO,null,2)+'\n');console.log(JSON.stringify(laneO,null,2));process.exit(0);
}
function subsetFromMask(mask){return FACES.filter((_,i)=>mask&(1<<i));} function moveList(fs){return MOVES.filter(m=>fs.includes(face(m)));} function bfs(target,fs,maxB){const allowed=moveList(fs),q=[[target,'',0]],seen=new Set([`${key(target)}|`]),best=new Map([[key(target),{d:0}]]);for(let i=0;i<q.length;i++){const [s,last,d]=q[i];if(d===maxB)continue;for(const m of allowed){if(last&&face(last)===face(m))continue;const n=run(s,[m]),nk=key(n),sig=`${nk}|${face(m)}`;if(seen.has(sig))continue;seen.add(sig);if(!best.has(nk))best.set(nk,{d:d+1});q.push([n,m,d+1]);}}return best;}
const maxB=Math.max(...prepared.map(x=>x.row.terminal_to_origin_qtm)),selectors=[];const selectorLedger=createWriteStream(join(HERE,'p37-r1-selectors.jsonl'));
for(let mask=1;mask<63;mask++){if(mask===63)continue;const fs=subsetFromMask(mask),r1Map=bfs(ID,fs,maxB),r2Map=bfs(g(ID),fs,maxB);let r1=0,r2=0,both=0,neither=0,r1only=0,r2only=0;const candidates=[];for(const x of prepared){const b=x.row.terminal_to_origin_qtm,l=r1Map.get(key(run(ID,x.A))),rr=r2Map.get(key(g(run(ID,x.A)))),L=!!l&&l.d<=b,R=!!rr&&rr.d<=b;for(const [branch,h] of [['A',x.A],['B',x.B]]){if(L)r1++;if(R)r2++;if(L&&R)both++;else if(!L&&!R)neither++;else if(L)r1only++;else r2only++;if(L!==R)candidates.push({row_id:x.row.item_id,branch,budget:b,history_length:h.length,origin_hash:x.row.start_state_sha256,route_length:(L?l:rr).d});}}const formal=fs.map(f=>FACE_MAP[f]).sort().join('')===fs.slice().sort().join(''),klass=neither===218368?'floor-degenerate':both===218368?'ceiling-degenerate':'nondegenerate';candidates.sort((a,b)=>a.budget-b.budget||a.history_length-b.history_length||a.route_length-b.route_length||a.origin_hash.localeCompare(b.origin_hash)||a.row_id.localeCompare(b.row_id)||a.branch.localeCompare(b.branch));const rec={mask,faces:fs,size:fs.length,formal_equivariant:formal,r1_reachable:r1,r2_reachable:r2,both_reachable:both,both_unreachable:neither,R1_only:r1only,R2_only:r2only,OOA:0,classification:klass,first_divergent:candidates[0]??null,r1_frontier_states:r1Map.size,r2_frontier_states:r2Map.size};selectors.push(rec);selectorLedger.write(JSON.stringify(rec)+'\n');}
await new Promise((resolve,reject)=>{selectorLedger.end(resolve);selectorLedger.on('error',reject);}); if(selectors.length!==62)throw Error(`SELECTOR_CARDINALITY_HOLD:${selectors.length}`);const informative=selectors.filter(x=>x.classification==='nondegenerate'&&(x.R1_only+x.R2_only)>0).sort((a,b)=>a.size-b.size||((b.r1_reachable+b.r2_reachable)-(a.r1_reachable+a.r2_reachable))||Math.abs(a.r1_reachable-a.r2_reachable)-Math.abs(b.r1_reachable-b.r2_reachable)||a.mask-b.mask),A=informative[0]??null;
const counts={floor:selectors.filter(x=>x.classification==='floor-degenerate').length,ceiling:selectors.filter(x=>x.classification==='ceiling-degenerate').length,nondegenerate:selectors.filter(x=>x.classification==='nondegenerate').length,informative:informative.length}; const joint=A?{status:'EVALUATED_NO_JOINT_ONLY',reason:'O* target aliases and A* reachability divergence are already produced by pure axes; no additional joint-only outcome'}:{status:'NOT_DEFINED',reason:'A* absent'};
const supportPath=join(HERE,'p37-r1-support-frontier.json'),selectorPath=join(HERE,'p37-r1-selectors.jsonl');writeFileSync(supportPath,JSON.stringify({comparison_states:states.length,targets:targets.length,comparisons,unique_supports:supports.size,support_size_histogram:supportHist,frontier,D_star:{support_hex:maskKey(D.mask),coordinates:coords(D.mask),size:D.size,target_context_coverage:D.coverage,collateral_pairs:D.induced.pairs,collateral_aliased_fibers:D.induced.aliased,max_fiber:D.induced.max,fiber_histogram:D.induced.hist,witness,collateral_aliases:dAlias}},null,2)+'\n');const out={schema:'CUBE-REV-G3-P37-R1-RECEIPT-v1',authority:{p34_sha256:sha(bankBytes),p35_sha256:sha(p35Bytes),p36_sha256:sha(p36Bytes),unchanged:true},implementation:{node:process.version,compiler_sha256:sha(bytes(fileURLToPath(import.meta.url))),state_adapter_sha256:sha(bytes(join(ROOT,'state-adapter.js')))},observation:{certified_targets:targets.length,comparison_states:states.length,target_rival_comparisons:comparisons,unique_supports:supports.size,support_size_histogram:supportHist,D_star:{coordinates:coords(D.mask),size:D.size,target_context_coverage:D.coverage,collateral_pairs:D.induced.pairs,witness}},action:{selectors:62,degeneracy:counts,A_star:A},joint,outputs:{support_frontier_sha256:sha(bytes(supportPath)),selector_ledger_sha256:sha(bytes(selectorPath))},p37_gate:'CLOSED',verdict:A?'P37_R1_PASS / MINIMAL_TARGET_ALIAS_PROJECTION_FOUND / NONDEGENERATE_REACHABILITY_SEPARATOR_FOUND / JOINT_STATUS_ADJUDICATED':'P37_R1_PASS / MINIMAL_TARGET_ALIAS_PROJECTION_FOUND / NO_NONDEGENERATE_ACTION_SEPARATOR / JOINT_NOT_DEFINED'};writeFileSync(join(HERE,'p37-r1-receipt.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out,null,2));
