import fs from 'node:fs';
import { buildR19Core, parseAnnotated, sha } from '../0.10.5-r1.9/r19_quotient_core.mjs';
const ROOT=process.env.R112_ROOT||'/tmp/r112';fs.mkdirSync(ROOT,{recursive:true});
const core=await buildR19Core();const {defaultPattern,EDGE,CORNER,ORIENT,faces,faceSupport,opposite,canonicalizeByCenters}=core;
const ID=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-gauge-identifiability/ROUX_G2_GAUGE_IDENTIFIABILITY_AUDIT.json','utf8'));
const intersect=(a,b)=>{const s=new Set(b);return a.filter(x=>s.has(x));};
function blockMask(bottom,side){const top=opposite[bottom];return {bottom,side,top,edges:faceSupport[side].edges.filter(i=>!faceSupport[top].edges.includes(i)),corners:intersect(faceSupport[bottom].corners,faceSupport[side].corners)};}
const frames=[];for(const bottom of faces)for(const side of faces){if(side===bottom||side===opposite[bottom])continue;frames.push({key:`${bottom}|${side}`,bottom,top:opposite[bottom],first_side:side,second_side:opposite[side],first:blockMask(bottom,side),second:blockMask(bottom,opposite[side])});}
function coordSolved(p,o,i){const a=p.patternData[o],b=defaultPattern.patternData[o];return a.pieces[i]===b.pieces[i]&&a.orientation[i]===b.orientation[i];}
function blockSolved(p,m){return m.edges.every(i=>coordSolved(p,EDGE,i))&&m.corners.every(i=>coordSolved(p,CORNER,i));}
function both(p,f){return blockSolved(p,f.first)&&blockSolved(p,f.second);}
function ordinary(c){return /\bfb\b/i.test(c||'')&&!/\bpseudo\s+fb\b/i.test(c||'')&&!/\bfbdr\b/i.test(c||'');}
function span(lines,phase,after=-1){let first=-1;for(let i=0;i<lines.length;i++)if(lines[i].phase===phase&&lines[i].end>lines[i].start&&lines[i].start>=after){first=i;break;}if(first<0)return null;let last=first;for(let i=first+1;i<lines.length;i++){if(lines[i].phase!==phase||lines[i].end<=lines[i].start)break;last=i;}return {start:lines[first].start,end:lines[last].end,lines:lines.slice(first,last+1)};}
function firstLineAfter(lines,phase,after){return lines.find(x=>x.phase===phase&&x.end>x.start&&x.start>=after)||null;}
function load(){const c=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-census/SEALED_ROUTE_CENSUS.json','utf8'));const a=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-acquisition/ROUX_EXPANSION_ROUTE_MANIFEST.json','utf8'));const out=[];for(const r of c.all_clean_attempts)out.push({...r,source:'SEALED_R111'});for(const r of a.records)if(r.route_source_status==='RAW_ALG_CUBING_LINK')out.push({...r,source:'R112_EXPANSION'});const m=new Map();for(const r of out)m.set(`${r.result_id}:${r.attempt_number}`,r);return [...m.values()];}
const rows=[];const C={eligible:0,prefix_success:0,prefix_failure:0,failure_matches_final_gauge:0,failure_completion_after_sb_before_cmll:0,failure_completion_after_sb_before_lse:0,failure_completion_any_later:0,failure_has_rotation_in_sb:0,failure_has_wide_slice_in_sb:0,success_has_rotation_in_sb:0,success_has_wide_slice_in_sb:0,failure_final_prefix_frame_both_solved:0,failure_same_transform_other_frame_completes_in_sb:0,failure_first_block_breaks_in_sb:0};
const statusCounts={},sourceCounts={};
for(const r of load())try{
 const p=parseAnnotated(r.raw_alg,'Roux'),fbLines=p.lines.filter(x=>x.phase==='ROUX_FB'&&x.end>x.start);if(fbLines.length!==1||!ordinary(fbLines[0].comment))continue;const fb=fbLines[0],sb=span(p.lines,'ROUX_SB',fb.end);if(!sb)continue;const moves=p.tokens.map(x=>x.move);let s=defaultPattern.applyAlg(r.raw_setup),states=[s];for(const m of moves){s=s.applyMove(m);states.push(s);}if(!s.experimentalIsSolved({ignorePuzzleOrientation:true,ignoreCenterOrientation:true}))continue;C.eligible++;
 const prefix=[];for(let oi=0;oi<ORIENT.length;oi++){const q=states[fb.end].applyTransformation(ORIENT[oi]);for(const f of frames)if(blockSolved(q,f.first)&&!blockSolved(q,f.second))prefix.push({oi,frame:f});}
 if(prefix.length!==1)throw new Error(`PREFIX_PAIR_${prefix.length}`);const z=prefix[0];
 let completion=null,firstBreak=false,otherFrame=false;for(let i=sb.start;i<=sb.end;i++){const q=states[i].applyTransformation(ORIENT[z.oi]);if(!blockSolved(q,z.frame.first))firstBreak=true;if(both(q,z.frame))completion??=i;if(frames.some(f=>f.key!==z.frame.key&&both(q,f)))otherFrame=true;}
 const success=completion!==null;const sbMoves=moves.slice(sb.start,sb.end),rot=sbMoves.some(m=>/^[xyz]/.test(m)),wideSlice=sbMoves.some(m=>/^[rludfbMES]/.test(m));
 if(success){C.prefix_success++;if(rot)C.success_has_rotation_in_sb++;if(wideSlice)C.success_has_wide_slice_in_sb++;}
 else{
  C.prefix_failure++;if(rot)C.failure_has_rotation_in_sb++;if(wideSlice)C.failure_has_wide_slice_in_sb++;if(firstBreak)C.failure_first_block_breaks_in_sb++;if(otherFrame)C.failure_same_transform_other_frame_completes_in_sb++;
  const finalCanon=canonicalizeByCenters(states.at(-1));const matchesFinal=finalCanon.ok&&z.oi===finalCanon.index;if(matchesFinal)C.failure_matches_final_gauge++;
  const cmll=firstLineAfter(p.lines,'ROUX_CMLL',sb.end),lse=span(p.lines,'ROUX_LSE',sb.end);let afterCmll=false,afterLse=false,anyLater=false;
  const stopCmll=cmll?cmll.start:states.length-1,stopLse=lse?lse.start:states.length-1;
  for(let i=sb.end+1;i<states.length;i++){const q=states[i].applyTransformation(ORIENT[z.oi]);if(both(q,z.frame)){anyLater=true;if(i<=stopCmll)afterCmll=true;if(i<=stopLse)afterLse=true;break;}}
  if(afterCmll)C.failure_completion_after_sb_before_cmll++;if(afterLse)C.failure_completion_after_sb_before_lse++;if(anyLater)C.failure_completion_any_later++;const qf=states.at(-1).applyTransformation(ORIENT[z.oi]);if(both(qf,z.frame))C.failure_final_prefix_frame_both_solved++;
 }
 sourceCounts[r.source]??={eligible:0,success:0,failure:0};sourceCounts[r.source].eligible++;sourceCounts[r.source][success?'success':'failure']++;
 const fam=sb.lines.map(x=>String(x.comment||'')).join(' | ');const fkey=[/\bSS\b/i.test(fam)?'SS':'',/\bSP\b/i.test(fam)?'SP':'',/flipped\s+SP/i.test(fam)?'FLIPPED_SP':'',/\bSB\b/i.test(fam)?'SB':''].filter(Boolean).join('+')||'OTHER';statusCounts[fkey]??={eligible:0,success:0,failure:0};statusCounts[fkey].eligible++;statusCounts[fkey][success?'success':'failure']++;
 rows.push({attempt_key:`${r.result_id}:${r.attempt_number}`,source:r.source,prefix_success:success,prefix_orientation_index:z.oi,prefix_frame_key:z.frame.key,sb_start:sb.start,sb_end:sb.end,sb_comments:sb.lines.map(x=>x.comment),rotation_in_sb:rot,wide_or_slice_in_sb:wideSlice,first_block_ever_broken_in_sb:firstBreak,other_frame_completed_same_transform_in_sb:otherFrame,completion_index:completion});
}catch(e){rows.push({attempt_key:`${r.result_id}:${r.attempt_number}`,source:r.source,error:String(e?.message||e).slice(0,300)});}
const rate=(n,d)=>d?n/d:0;const out={schema_version:'CR0105R112-RESIDUAL-GAUGE-COURT-1',generation:'ROUX-MEASUREMENT-G2',status:'POSTHOC_RESIDUAL_DIAGNOSTIC_NO_PRIMARY_GATE_CHANGE',identifiability_semantic_sha256:ID.semantic_sha256,counts:C,rates:{prefix_success:rate(C.prefix_success,C.eligible),rotation_in_sb_failure:rate(C.failure_has_rotation_in_sb,C.prefix_failure),rotation_in_sb_success:rate(C.success_has_rotation_in_sb,C.prefix_success),wide_slice_in_sb_failure:rate(C.failure_has_wide_slice_in_sb,C.prefix_failure),wide_slice_in_sb_success:rate(C.success_has_wide_slice_in_sb,C.prefix_success),failure_any_later_completion:rate(C.failure_completion_any_later,C.prefix_failure),failure_final_prefix_frame_both_solved:rate(C.failure_final_prefix_frame_both_solved,C.prefix_failure),failure_first_block_breaks:rate(C.failure_first_block_breaks_in_sb,C.prefix_failure)},by_source:sourceCounts,by_sb_annotation_family:statusCounts,adjudication_rule:'Residual court only characterizes the 10 prefix-identified failures. It cannot promote, repair, or relax R1.12 G2 authority.',post_result_gate_change:false,human_observations:0};out.semantic_sha256=sha(out);fs.writeFileSync(`${ROOT}/ROUX_G2_RESIDUAL_GAUGE_AUDIT.json`,JSON.stringify(out,null,2)+'\n');fs.writeFileSync(`${ROOT}/ROUX_G2_RESIDUAL_GAUGE_ROWS.json`,JSON.stringify({schema_version:'CR0105R112-RESIDUAL-GAUGE-ROWS-1',rows,human_observations:0},null,2)+'\n');console.log(JSON.stringify(out,null,2));