import fs from 'node:fs';
import { buildR19Core, parseAnnotated, sha } from '../0.10.5-r1.9/r19_quotient_core.mjs';
const ROOT=process.env.R112_ROOT||'/tmp/r112';fs.mkdirSync(ROOT,{recursive:true});
const core=await buildR19Core();const {defaultPattern,EDGE,CORNER,ORIENT,faces,faceSupport,opposite,canonicalizeByCenters}=core;
const PRIMARY=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-g2/ROUX_G2_GEOMETRY_AUDIT.json','utf8'));
const D1=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-destroy/ROUX_G2_COORDINATE_GAUGE_DESTROY_AUDIT.json','utf8'));
const intersect=(a,b)=>{const s=new Set(b);return a.filter(x=>s.has(x));};
function blockMask(bottom,side){const top=opposite[bottom];return {bottom,side,top,edges:faceSupport[side].edges.filter(i=>!faceSupport[top].edges.includes(i)),corners:intersect(faceSupport[bottom].corners,faceSupport[side].corners)};}
const frames=[];for(const bottom of faces)for(const side of faces){if(side===bottom||side===opposite[bottom])continue;frames.push({key:`${bottom}|${side}`,bottom,first:blockMask(bottom,side),second:blockMask(bottom,opposite[side])});}
function coordSolved(p,o,i){const a=p.patternData[o],b=defaultPattern.patternData[o];return a.pieces[i]===b.pieces[i]&&a.orientation[i]===b.orientation[i];}
function blockSolved(p,m){return m.edges.every(i=>coordSolved(p,EDGE,i))&&m.corners.every(i=>coordSolved(p,CORNER,i));}
function both(p,f){return blockSolved(p,f.first)&&blockSolved(p,f.second);}
function ordinary(c){return /\bfb\b/i.test(c||'')&&!/\bpseudo\s+fb\b/i.test(c||'')&&!/\bfbdr\b/i.test(c||'');}
function span(lines,phase,after=-1){let first=-1;for(let i=0;i<lines.length;i++)if(lines[i].phase===phase&&lines[i].end>lines[i].start&&lines[i].start>=after){first=i;break;}if(first<0)return null;let last=first;for(let i=first+1;i<lines.length;i++){if(lines[i].phase!==phase||lines[i].end<=lines[i].start)break;last=i;}return {start:lines[first].start,end:lines[last].end};}
function load(){const c=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-census/SEALED_ROUTE_CENSUS.json','utf8'));const a=JSON.parse(fs.readFileSync('research/0.10.5-r1.12/evidence-acquisition/ROUX_EXPANSION_ROUTE_MANIFEST.json','utf8'));const out=[];for(const r of c.all_clean_attempts)out.push({...r,source:'SEALED_R111'});for(const r of a.records)if(r.route_source_status==='RAW_ALG_CUBING_LINK')out.push({...r,source:'R112_EXPANSION'});const m=new Map();for(const r of out)m.set(`${r.result_id}:${r.attempt_number}`,r);return [...m.values()];}
const C={eligible:0,final_gauge_available:0,final_gauge_fb_unique:0,final_gauge_sb_success:0,prefix_any_pair:0,prefix_unique_pair:0,prefix_unique_pair_sb_success:0,prefix_unique_pair_matches_final_gauge:0,dynamic_center_gauge_changed_fb_to_sb:0,fb_center_gauge_differs_final:0,strict_admitted:PRIMARY.counts.g2_admitted,route_global_joint_solution:D1.counts.route_global_any_solution};
const bySource={},rows=[];const bump=(src,k)=>{bySource[src]??={eligible:0,final_gauge_sb_success:0,prefix_unique_pair_sb_success:0};bySource[src][k]++;};
for(const r of load())try{
 const p=parseAnnotated(r.raw_alg,'Roux'),fbLines=p.lines.filter(x=>x.phase==='ROUX_FB'&&x.end>x.start);if(fbLines.length!==1||!ordinary(fbLines[0].comment))continue;const fb=fbLines[0],sb=span(p.lines,'ROUX_SB',fb.end);if(!sb)continue;const moves=p.tokens.map(x=>x.move);let s=defaultPattern.applyAlg(r.raw_setup),states=[s];for(const m of moves){s=s.applyMove(m);states.push(s);}if(!s.experimentalIsSolved({ignorePuzzleOrientation:true,ignoreCenterOrientation:true}))continue;C.eligible++;bump(r.source,'eligible');
 const finalCanon=canonicalizeByCenters(states.at(-1));const fbCanon=canonicalizeByCenters(states[fb.end]);if(!finalCanon.ok||!fbCanon.ok)continue;C.final_gauge_available++;const fg=finalCanon.index;
 const qfbFG=states[fb.end].applyTransformation(ORIENT[fg]);const fgFrames=frames.filter(f=>blockSolved(qfbFG,f.first)&&!blockSolved(qfbFG,f.second));if(fgFrames.length===1){C.final_gauge_fb_unique++;const f=fgFrames[0];let ok=false;for(let i=sb.start;i<=sb.end;i++)if(both(states[i].applyTransformation(ORIENT[fg]),f)){ok=true;break;}if(ok){C.final_gauge_sb_success++;bump(r.source,'final_gauge_sb_success');}}
 const prefix=[];for(let oi=0;oi<ORIENT.length;oi++){const q=states[fb.end].applyTransformation(ORIENT[oi]);for(const f of frames)if(blockSolved(q,f.first)&&!blockSolved(q,f.second))prefix.push({oi,frame:f});}
 if(prefix.length)C.prefix_any_pair++;let prefixOk=false,prefixMatch=false;if(prefix.length===1){C.prefix_unique_pair++;const z=prefix[0];prefixMatch=z.oi===fg;if(prefixMatch)C.prefix_unique_pair_matches_final_gauge++;for(let i=sb.start;i<=sb.end;i++)if(both(states[i].applyTransformation(ORIENT[z.oi]),z.frame)){prefixOk=true;break;}if(prefixOk){C.prefix_unique_pair_sb_success++;bump(r.source,'prefix_unique_pair_sb_success');}}
 const centerIndices=[];for(let i=fb.end;i<=sb.end;i++){const cc=canonicalizeByCenters(states[i]);if(cc.ok)centerIndices.push(cc.index);}if(new Set(centerIndices).size>1)C.dynamic_center_gauge_changed_fb_to_sb++;if(fbCanon.index!==fg)C.fb_center_gauge_differs_final++;
 rows.push({attempt_key:`${r.result_id}:${r.attempt_number}`,source:r.source,final_gauge_index:fg,fb_center_gauge_index:fbCanon.index,center_gauge_distinct_fb_to_sb:new Set(centerIndices).size,final_gauge_fb_candidate_n:fgFrames.length,prefix_candidate_n:prefix.length,prefix_unique_matches_final_gauge:prefix.length===1?prefixMatch:null,prefix_unique_sb_success:prefix.length===1?prefixOk:null});
}catch(e){rows.push({attempt_key:`${r.result_id}:${r.attempt_number}`,source:r.source,error:String(e?.message||e).slice(0,300)});}
const rate=(n,d)=>d?n/d:0;const out={schema_version:'CR0105R112-DESTROY-GAUGE-IDENTIFIABILITY-1',generation:'ROUX-MEASUREMENT-G2',status:'POSTHOC_DIAGNOSTIC_ONLY_NO_G2_GATE_CHANGE',primary_geometry_semantic_sha256:PRIMARY.semantic_sha256,prior_destroy_semantic_sha256:D1.semantic_sha256,counts:C,rates:{final_gauge_sb_success:rate(C.final_gauge_sb_success,C.eligible),prefix_unique_pair:rate(C.prefix_unique_pair,C.eligible),prefix_unique_pair_sb_success:rate(C.prefix_unique_pair_sb_success,C.eligible),prefix_success_given_unique:rate(C.prefix_unique_pair_sb_success,C.prefix_unique_pair),prefix_unique_matches_final_gauge:rate(C.prefix_unique_pair_matches_final_gauge,C.prefix_unique_pair),dynamic_center_gauge_changed_fb_to_sb:rate(C.dynamic_center_gauge_changed_fb_to_sb,C.eligible),fb_center_gauge_differs_final:rate(C.fb_center_gauge_differs_final,C.eligible)},by_source:bySource,interpretation_guard:'Final-orientation and FB-prefix gauges are posthoc mechanism diagnostics. They do not alter the frozen R1.12 G2 center-consistent operator. A future generation may prospectively define a route-global reconstruction-coordinate gauge only after a separate theory and court freeze.',post_result_gate_change:false,human_observations:0};out.semantic_sha256=sha(out);fs.writeFileSync(`${ROOT}/ROUX_G2_GAUGE_IDENTIFIABILITY_AUDIT.json`,JSON.stringify(out,null,2)+'\n');fs.writeFileSync(`${ROOT}/ROUX_G2_GAUGE_IDENTIFIABILITY_ROWS.json`,JSON.stringify({schema_version:'CR0105R112-DESTROY-GAUGE-IDENTIFIABILITY-ROWS-1',rows,human_observations:0},null,2)+'\n');console.log(JSON.stringify(out,null,2));
