#!/usr/bin/env python3
"""CUBE-REV 0.18: auditable PySAT k=25 exact PB/cover court.
Input generated by physical 3x3 cube UR-edge oracle (Node), never by a
made-up FSM. All logical strengthening is independently necessary IF k=25.
Solver status and DRUP trace are explicitly different proof levels.
"""
import argparse
import hashlib
import json
from pathlib import Path
from collections import Counter
from pysat.formula import CNF, IDPool
from pysat.card import CardEnc, EncType as CardType
from pysat.pb import PBEnc, EncType as PBType
from pysat.solvers import Glucose4

p=argparse.ArgumentParser()
p.add_argument('--instance',required=True)
p.add_argument('--out',required=True)
p.add_argument('--conflicts',type=int,default=150000)
args=p.parse_args()
assert args.conflicts>=1
data=json.loads(Path(args.instance).read_text())
assert data['schema']=='cube-rev.018.cube-physical-mstar-maximal-v1'
assert data['counts']==dict(literal=104976,partitions=1913,
                             coverageTypes=1477,maximal=1323,bases=1192)
bases=list(map(int,data['bases']))
cols=data['candidates']
n=len(cols)
mask=[int(item['mask'],16) for item in cols]
mass=[int(item['mass']) for item in cols]
positive=[i for i,c in enumerate(mass) if c>0]
assert n==1323 and len(positive)==596
assert Counter(mass)=={0:727,4:340,8:76,12:12,16:6,20:162}
assert sum(int(w) for b,w in data['dual'])==476
assert len([1 for b,w in data['dual'] if int(w)==20])==10
assert all(0<=m<=20 and m%4==0 for m in mass)
assert len(set(mask))==n

cnf=CNF()
base_coverage=[]
for i in range(len(bases)):
    clauses=[j+1 for j,z in enumerate(mask) if z>>i&1]
    if not clauses:
        raise AssertionError(f'UNMODELED_BASE_{i}')
    base_coverage.append(clauses)
    cnf.append(clauses)
pool=IDPool(start_from=n+1)
# Previously proven: any hypothetical <=25 complete dictionary has
# no zero-dual word, and exactly 10 distinct weight-20 singleton choices.
for i,c in enumerate(mass):
    if c==0:cnf.append([-i-1])
heavy_ranges={}
for base in data['heavy']:
    i=bases.index(int(base))
    selections=[j+1 for j in range(n) if mask[j]>>i&1]
    assert len(selections)==4
    assert all(mass[j-1]==20 for j in selections)
    heavy_ranges[str(base)]=selections
    cnf.extend(CardEnc.equals(lits=selections,bound=1,
                  encoding=CardType.seqcounter,vpool=pool).clauses)
nonzero_lits=[j+1 for j in positive]
cnf.extend(CardEnc.equals(lits=nonzero_lits,bound=25,
                       encoding=CardType.seqcounter,vpool=pool).clauses)
# Sound, but redundant, exact strengthening from the frozen P6 rational dual.
cnf.extend(CardEnc.atleast(
    lits=[j+1 for j,c in enumerate(mass) if c==20],bound=19,
    encoding=CardType.seqcounter,vpool=pool).clauses)
# Deficit units d=(20-c)/4; for 25 words, total <=(500-476)/4=6.
nonzero_weights=[(20-mass[j])//4 for j in positive]
keep=[(lit,w) for lit,w in zip(nonzero_lits,nonzero_weights) if w>0]
cnf.extend(PBEnc.atmost(lits=[lit for lit,w in keep],
                       weights=[w for lit,w in keep],bound=6,
                       encoding=PBType.bdd,vpool=pool).clauses)
out=Path(args.out);out.mkdir(parents=True,exist_ok=True)
cnf_path=out/'exact_k25.cnf'
cnf.to_file(str(cnf_path))
source_sha=hashlib.sha256(Path(args.instance).read_bytes()).hexdigest()
cnf_sha=hashlib.sha256(cnf_path.read_bytes()).hexdigest()
receipt={'status':'PENDING','claimed_minimum':None,
 'physical_instance_sha256':source_sha,'cnf_sha256':cnf_sha,
 'variables_original':n,'variables_cnf':cnf.nv,'clauses':len(cnf.clauses),
 'physical_bases':len(bases),'nonzero_candidates':len(positive),
 'heavy_categories':heavy_ranges,'bound_k':25,
 'defect_units_max':6,'conflict_budget':args.conflicts,
 'note':'SAT needs separate physical witness replay; UNSAT needs independent DRUP/DRAT checking against this exact CNF; UNKNOWN certifies nothing.'}
(out/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n')
print('MSTAR25_PB_CNF_GENERATED',json.dumps({k:v for k,v in receipt.items() if k not in ('heavy_categories','note')},sort_keys=True),flush=True)
with Glucose4(bootstrap_with=cnf.clauses,with_proof=True) as sat:
    sat.conf_budget(args.conflicts)
    result=sat.solve_limited(expect_interrupt=False)
    if result is True:
        chosen=[i for i in range(n) if i+1 in set(sat.get_model())]
        assert len(chosen)==25
        covered=0
        for i in chosen:covered|=mask[i]
        assert covered.bit_count()==1192
        assert sum((20-mass[i])//4 for i in chosen)<=6
        names=[cols[i]['word'] for i in chosen]
        receipt['status']='SAT_WITNESS_PENDING_INDEPENDENT_PHYSICAL_REPLAY'
        (out/'sat_witness.json').write_text(json.dumps({
         'selected_candidates':chosen,'four_turn_words':names,
         'original_source_masks':bases},indent=2)+'\n')
        print('MSTAR25_SAT_DECODED_REPLAY_PENDING',flush=True)
    elif result is False:
        trace=sat.get_proof()
        if trace is None or not trace or trace[-1].strip()!='0':
            raise RuntimeError('UNSAT returned without final empty DRUP clause')
        proof_path=out/'exact_k25.drup'
        proof_path.write_text('\n'.join(trace)+'\n')
        receipt['status']='UNSAT_SOLVER_REPORTED_EXTERNAL_PROOF_CHECK_PENDING'
        receipt['proof_sha256']=hashlib.sha256(proof_path.read_bytes()).hexdigest()
        receipt['proof_lines']=len(trace)
        print('MSTAR25_UNSAT_DRUP_EMITTED_BUT_NOT_YET_VERIFIED',len(trace),flush=True)
    else:
        receipt['status']='UNKNOWN_CONFLICT_BUDGET'
        print('MSTAR25_UNKNOWN_BUDGET_NOT_A_LOWER_BOUND',args.conflicts,flush=True)
(out/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n')
