#!/usr/bin/env python3
"""CUBE-REV 0.19: exact, ordering-independent five-turn fractional cover court.
Full original source masks, not unstable reduced column indices, identify witnesses.
Inputs are physical source generated by sticker-cube and physical partitions emitted
by independently generated legal five-action word enumeration.
"""
import argparse,hashlib,json
from pathlib import Path
from fractions import Fraction
from itertools import product
p=argparse.ArgumentParser()
for k in ('physical','partitions','full_cert','five_cert','output'):p.add_argument('--'+k,required=True)
a=p.parse_args()
raw=Path(a.physical).read_bytes();source=json.loads(raw)
sha=hashlib.sha256(raw).hexdigest()
assert sha=='9f2119738f92f56485897c1894d2cb721a3d6b0498c5aa14832c71f18b20e2f1'
bases=source['bases'];assert len(bases)==1192
base_index={m:i for i,m in enumerate(bases)}

def mask_from_blocks(blocks):
 assert len(blocks)==len(set(blocks))
 total=0
 for b in blocks:assert b>0 and not(total&b);total|=b
 assert total==(1<<12)-1
 out=0
 for i,source_set in enumerate(bases):
  if all((source_set&b).bit_count()<=1 for b in blocks):out|=1<<i
 return out
physical_covers=set();raw_partitions=0
for line in Path(a.partitions).read_text().splitlines():
 word, sep,blockstr=line.partition('|');assert sep and len(word.split())==5
 blocks=tuple(map(int,blockstr.split()))
 physical_covers.add(mask_from_blocks(blocks))
 raw_partitions+=1
assert raw_partitions==14938 and len(physical_covers)==14446
# This group acts on original source ROW LABELS, regardless of candidate order.
coords=[(1,1,0),(0,1,1),(-1,1,0),(0,1,-1),
        (1,-1,0),(0,-1,1),(-1,-1,0),(0,-1,-1),
        (1,0,1),(-1,0,1),(-1,0,-1),(1,0,-1)]
slot_index={v:i for i,v in enumerate(coords)}
row_perms=[]
for axes in ((0,1,2),(1,0,2)):
 for signs in product((-1,1),repeat=3):
  pp=[slot_index[tuple(signs[k]*pos[axes[k]] for k in range(3))]
      for pos in coords]
  rp=[]
  for mask in bases:
   transformed=sum(1<<pp[k] for k in range(12) if mask>>k&1)
   assert transformed in base_index
   rp.append(base_index[transformed])
  row_perms.append(rp)
assert len(row_perms)==16

def translate(mask,rp):
 out=0
 while mask:
  lo=mask&-mask
  out|=1<<rp[lo.bit_length()-1]
  mask-=lo
 return out

def audit(name,path,expected,source_rows,expected_support):
 c=json.loads(Path(path).read_text())
 assert c['physical_source_sha256']==sha
 assert Fraction(c['fractional_lp_optimum'])==expected
 assert c['group_order']==16
 weights={};assembled=[]
 for block in c['primal_source_coverage_masks']:
  representative=int(block['representative_full_1192_coverage_hex'],16)
  assert representative in physical_covers
  orbit={translate(representative,g) for g in row_perms}
  assert len(orbit)==block['orbit_size'] and orbit<=physical_covers
  coefficient=Fraction(block['weight'])
  assert coefficient>0
  for w in orbit:
   assert w not in weights
   weights[w]=coefficient
  assembled.append((len(orbit),str(coefficient)))
 assert len(weights)==expected_support
 primal_total=sum(weights.values())
 assert primal_total==expected
 for row in source_rows:
  covered=sum(w for mask,w in weights.items() if (mask>>row)&1)
  assert covered>=1,('FRACTIONAL_PRIMAL_ROW_FAIL',name,row,covered)
 dual=c.get('dual_original_source_rows_weighted_numerator',c.get('dual_original_source_rows_scaled'))
 denominator=int(c['dual_common_denom']);dual={int(k):int(v) for k,v in dual.items()}
 assert all(i in source_rows and z>0 for i,z in dual.items())
 assert Fraction(sum(dual.values()),denominator)==expected
 maxmass=0
 for mask in physical_covers:
  mass=sum(z for row,z in dual.items() if (mask>>row)&1)
  assert mass<=denominator,('DUAL_EXCEEDS_COLUMN_CAPACITY',name,mass)
  maxmass=max(maxmass,mass)
 assert maxmass==denominator
 print('CUBE_REV_019_L5_ORDER_INVARIANT_EXACT_FRACTIONAL_PROOF_PASS',name,
       'objective',str(expected),'real_physical_masks',len(physical_covers),
       'rows',len(source_rows),'fractional_word_support',len(weights),
       'primal_orbits',len(assembled),'positive_dual_rows',len(dual),
       'denominator',denominator,flush=True)
 return {'objective':str(expected),'physical_cover_types':len(physical_covers),'physical_word_orbits':len(assembled),'fractional_physical_word_count':len(weights),'dual_positive_source_rows':len(dual),'dual_max_capacity':maxmass,'all_source_constraints_integer_checked':True}
full=audit('ALL_1192',a.full_cert,Fraction(16,3),set(range(1192)),96)
five=audit('FIVE_ONLY_480',a.five_cert,Fraction(185,39),{i for i,b in enumerate(bases) if b.bit_count()==5},106)
assert Fraction(full['objective'])-Fraction(five['objective'])==Fraction(23,39)
receipt={'schema':'cube-rev.019.P8.order-independent-fractional-court','physical_source_sha256':sha,'all':full,'five':five,'additive_fractional_cost_of_64_mixed_four_state_requirements':'23/39','status':'EXACT_RATIONAL_PRIMAL_DUAL_CHECKED_NOT_INTEGER_MINIMUM'}
Path(a.output).write_text(json.dumps(receipt,indent=2)+'\n')
print('CUBE_REV_019_L5_64_FOUR_STATE_RESTRICTIONS_RAISE_EXACT_FRACTIONAL_OPTIMUM_BY_23_OVER_39_PASS',flush=True)